(function(z){
var Dk=function(a){this.O=window.document;this.h=this.te=window;this.R=a;new z.zd;this.oa=!1;this.lc=this.Cb=null;this.U=[];this.Ac=!1;this.G={};this.G.va=0;this.G.Cl="";this.G.Bl="";this.G.nc=null;this.Kd=this.Jd=0;this.ad=/\w/i;this.F={};this.F.parentId="WACDocumentPanelContent";this.F.positionId="Selected";this.F.seq="1";this.F.words=[];this.F.words.push("The");this.F.words.push("In");this.F.words.push("I");this.F.words.push("It");this.F.words.push("He");this.F.words.push("This");this.F.words.push("A");
this.F.words.push("But");this.F.words.push("As");this.F.words.push("For");this.lf=z.S.a().bind(this,this.uf);this.mf=z.S.a().bind(this,this.Lh);this.Ka=this.ia=null};
var Ek=function(a,b){var c=window.document;void 0!==b&&(c=b.contentDocument);var d=z.S.a().bind(a,a.dd);c.addEventListener("mousedown",d,!0);d=z.S.a().bind(a,a.ph);c.addEventListener("mousemove",d,!0);c.addEventListener("keydown",a.cd.bind(a),!0);c.addEventListener("keyup",a.ve.bind(a),!0);d=z.S.a().bind(a,a.qh);c.addEventListener("mouseup",d,!0);c=z.S.a().bind(a,a.ff);window.addEventListener("scroll",c,!1);c=z.S.a().bind(a,a.mh);z.E(window,"resize",c)};
var Fk=function(){this.Ob="rwGooglePredictionDictionaryDetails";this.oc="rwGooglePredictionResponseDetails";window.m_webReaderElem=window.document.getElementById("webReaderModule");window.m_extensionPath=window.m_webReaderElem.getAttribute("data-root");this.Kf(window.m_extensionPath+"assets/distiller/domdistiller.js");this.Kf(window.m_extensionPath+"assets/HTMLParser/HTMLParser.js",this.Do.bind(this));this.Z={};this.la=this.Ha=null;var a=[];a.push("Web");a.push(window.location.href);window.window.thPostMessage({type:"1757FROM_PAGERW4G",
key:"function",method:"BarShown",parameters:a},"*")};var Gk=function(a,b){b.addEventListener("load",function(){this.Z.stop();this.Z.addEventsToFrame(b);Ek(this.la,b)}.bind(a))};var Hk=function(a,b,c){a.Z.mouseOverEvent(b,c)};var Ik=function(){return new window.Promise(function(a){window.result=window.org.chromium.distiller.DomDistiller.applyWithOptions({});a({title:window.result[1],html:window.result[2][1]})})};var Jk=function(a){return a.Z.getPredictionCoordinates()};var Kk=function(a){a.Z.isEditable()};
z.f=Dk.prototype;z.f.dd=function(a){null!==this.Ka&&((0,window.clearTimeout)(this.Ka),this.Ka=null);var b=this;this.Ka=(0,window.setTimeout)(function(){b.lf(a)},300)};z.f.play=function(){z.T.a().k("onWRPlay",!0)};
z.f.ph=function(a){try{var b=this;Hk(this.R,a,function(){b.play()});-1==a.target.className.indexOf("texthelp-toolbarbutton")&&-1==a.target.parentNode.className.indexOf("texthelp-toolbarbutton")&&-1==a.target.className.indexOf("th-RW4GC-toolbar")&&-1==a.target.parentNode.className.indexOf("th-RW4GC-toolbar")||this.R.Z.clearHoverSpeak()}catch(c){}};
z.f.cd=function(a){if(a.ctrlKey&&47<a.keyCode&&58>a.keyCode){var b=[];b.push(a);null!==this.lb&&((0,window.clearTimeout)(this.lb),this.lb=null);this.lb=(0,window.setTimeout)(function(){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(b)}.bind(this),10);z.Rj()&&(a.preventDefault(),a.stopPropagation());this.R.cd(a);if(Kk(this.R))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{a=Jk(this.R);var c=window.document.getElementById("rwGooglePredictionDictionaryDetails");
c&&(c.style.left=a.left,c.style.top=a.top);this.oa&&this.Ma("")}}};z.f.ve=function(a){var b=[];b.push(a.keyCode);z.T.a().k("onKeyUpEvent",b);null!==this.ia&&((0,window.clearTimeout)(this.ia),this.ia=null);17===a.keyCode?this.Te=this.Hh?!1:!0:(this.ia=(0,window.setTimeout)(this.mf,100),this.Te=!1)};z.f.Jn=function(a){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(a)};
z.f.Ma=function(){null!==this.ia&&((0,window.clearTimeout)(this.ia),this.ia=null);this.ia=(0,window.setTimeout)(this.mf,0)};
z.f.Lh=function(){this.ia=null;if(this.oa){var a=this.R.Me();if(null==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=z.V.a().M().prediction.results,c=z.V.a().M().language.services;this.G.va++;999<this.G.va&&(this.G.va=0);var d='"'+z.S.a().mg(a.context)+'","'+b+'","en_US"',e='{ "parent":"document.body", "position":"'+this.R.Ob+'","addSpace":false,"seq":"'+this.G.va+'"}';z.S.a().Bh(this.G.va);this.G.nc=a;e=z.qd(e);d=[];d[0]=a.context;d[1]=b;d[2]=c;if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();
else e.context=d,window.thPostMessage({method:"thPrediction",type:"1757FROM_PAGERW4G",payload:e},"*")}}};z.f.qh=function(){var a=window.document.getElementById("th-RW4GC-picture-dictionary"),b=window.document.getElementById("th-RW4GC-translator");if(null!=window.document.getElementById("th-RW4GC-dictionary")||null!=a||null!=b)a=this.R.vb(),null!=a&&""!=a&&z.T.a().k("onWordChanged",[])};
z.f.ff=function(){var a=this.R.Aa();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,"document.body")};z.f.mh=function(){var a=this.R.Aa();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,"document.body")};
z.f.uf=function(a){this.R.dd(a);if(Kk(this.R))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{a=Jk(this.R);var b=window.document.getElementById("rwGooglePredictionDictionaryDetails");b&&(b.style.left=a.left,b.style.top=a.top);this.oa&&this.Ma("")}};
z.f.gf=function(a){try{this.R.Z.predictionInsertText(a[0]);var b=z.S.a().Xa();a=[];a.push("prediction insert");a.push(b.Email);a.push(b.Email.split("@")[1]);window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",parameters:a},"*");this.Ma("")}catch(c){z.S.a().b(c)}};
z.f.Md=function(a){try{var b=window.document.getElementById("rwGooglePredictionDictionaryDetails");if(!b){var c=window.document.body,b=window.document.createElement("div");b.setAttribute("id","rwGooglePredictionDictionaryDetails");b.className="rwGooglePredictionDictionaryDetails";b.style.position="absolute";c.appendChild(b);var d=window.document.createElement("div");d.setAttribute("id","rwGooglePredictionResponseDetails");d.className="rwGooglePredictionResponseDetails";c.appendChild(d)}this.oa=a[0];
if(Kk(this.R)){var e=Jk(this.R);b.style.left=e.left;b.style.top=e.top;this.oa&&(a=[],a.push("kix-appview-editor"),this.Ma(""),z.T.a().k("onOpenPredictionWindow",a))}else window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose()}catch(g){z.S.a().b(g)}};z.f.mj=function(){try{var a=z.J("kix-cursor-caret",this.h);null!==a&&(z.S.a().fireEvent(a,"click"),a.focus())}catch(b){z.S.a().b(b)}};z.f.Oo=function(a){a=a[0];this.R.Z.hoverSpeakEnabled(a);a||z.T.a().k("onWRStop",!0)};z.Yj.qj="HTMLParser";z.B(Fk,z.Oj);z.f=Fk.prototype;z.f.Kf=function(a,b){var c=window.document.documentElement.getElementsByTagName("body")[0];if(null==c||void 0==c)c=window.document.body;var d=window.document.createElement("script");d.src=a;d.async=!0;d.onload=d.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(d.onload=d.onreadystatechange=null,c.removeChild(d),void 0!=b&&b())};c.appendChild(d)};
z.f.nq=function(a){var b=[];a.forEach(function(a){a.addedNodes.forEach(function(a){if("IFRAME"==a.nodeName)b.push(a);else if(0<a.childNodes.length)for(var c=0;c<a.childNodes.length;c++)"IFRAME"==a.childNodes[c].nodeName&&b.push(a.childNodes[c])}.bind(this))}.bind(this));for(a=0;a<b.length;a++)Gk(this,b[a])};
z.f.Do=function(){var a=window.document.querySelector("#thSpeechStreamTBPlaceHolder").getAttribute("data-root"),b=window.document.querySelector("#thWebReaderPlaceHolder").getAttribute("dynamic-frames");this.Z=new window.textHelp.parsers.HTMLParserAPI(!0,a+"assets/HTMLParser/");var a=this.la=new Dk(this),c=window.frames;if(0<c.length)for(var d=0;d<c.length;d++)try{Ek(a,c[d])}catch(e){}c=z.S.a().bind(a,a.dd);a.O.addEventListener("mousedown",c,!0);c=z.S.a().bind(a,a.ph);a.O.addEventListener("mousemove",
c,!0);a.O.addEventListener("keydown",a.cd.bind(a),!0);a.O.addEventListener("keyup",a.ve.bind(a),!0);c=z.S.a().bind(a,a.qh);a.O.addEventListener("mouseup",c,!0);z.T.a().j("onclicktospeak",a.Oo,a);z.T.a().j("onPredictionChange",a.gf,a);z.T.a().j("onWRPredictionStateChanged",a.Md,a);"true"==b&&(this.Ss=window.document.body,this.mq=new window.MutationObserver(this.nq.bind(this)),this.mq.observe(this.Ss,{childList:!0,subtree:!0}))};z.f.Og=function(){return this.Z.hiliteSelection()};z.f.Yc=function(a){this.Z.highlightSelection(a)};
z.f.Hf=function(){return this.Z.hasSelection()};z.f.Ks=function(){if(!(-1<window.location.href.indexOf(".texthelp.com/simplify/"))){var a=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().language.services;window.open("https://rw.texthelp.com/simplify/home/simplify?locale\x3d"+(0,window.encodeURIComponent)(a)+"\x26simplify\x3d"+window.location.href,"_newtab")}};z.f.vb=function(){return this.Z.getWord()};z.f.getSelection=function(){return this.Z.getSelection()};z.f.wb=function(a){try{this.Z.hiliteWord(a)}catch(b){}};
z.f.wg=function(){this.Z.clearBrowserSelection()};
z.f.Oc=function(a,b,c){a=this.Z.collectHighlights(b,c);b=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("ch_documentTitle");a={highlights:a,title:window.document.getElementsByTagName("title")[0].innerHTML,url:window.location.href,docTitle:b};this.qk=window.textHelp.webreaderapi.EventBusSingleton.getInst().subscribe("onCollectHighlightsWeb",this.gl,this);window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"CollectHighlights",parameters:a},"*")};
z.f.gl=function(){try{window.textHelp.webreaderapi.EventBusSingleton.getInst().unsubscribe(this.qk),this.dt.focus()}catch(a){window.console.error(a.stack)}};z.f.stop=function(){this.Z.stop()};z.f.he=function(a,b){var c=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().speechoptions.continousreading;b(this.Z.hiliteNextSentence(c))};z.f.sc=function(){this.Z.clearHighlights()};
z.f.Af=function(a,b,c){a=this.Z.collectVocabs(a,b,c);b=window.textHelp.webreader.ConfigurationSingleton.getInst().getConfiguration();c={};c.words=a;c.locale=b.locale;c.user=b.serversettings.user;c.translations={};c.translations.docTitle=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_document_title");c.translations.title=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_title");c.translations.heading=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_heading");
c.translations.symbol=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_symbol");c.translations.notes=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_notes");c.translations.meaning=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_meaning");c.locale=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().language.services;window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",
method:"Vocab",parameters:c},"*")};z.f.Vc=function(a){a(this.Z.getSelectionLocal())};z.f.ui=function(a){Ik().then(this.jp).then(function(b){window.title=b.title;window.html=b.html;a({documentTitle:window.title,html:window.html})})};z.f.jp=function(a){var b=window.document.createElement("body");b.innerHTML=a.html;for(var c=b.querySelectorAll("img"),d=0;d<c.length;d++){var e=c[d];"https:"!==e.getAttribute("src").substr(0,6).toLowerCase()&&b.removeChild(e)}return Object.assign({},a,{html:b.innerHTML})};
z.f.ma=function(){this.Z.clearSelection_()};z.f.fd=function(){throw Error("Not implemented");};z.f.ed=function(){throw Error("Not implemented");};z.f.Vc=function(a){a(this.Z.getSelectionLocal())};z.f.Ji=function(a){this.Z.predictionInsertText(a)};z.f.Me=function(){try{var a=[];a.context="";a.word="";a.cursorindex="";a.spaceatstart=!1;a.spaceatend=!1;a.prepunc="";a.postpunc="";a.selectRight=0;a.selectLeft=0;a.prechar="";a.currentchar="";a.postchar="";a.context=this.Z.getPredictionSentence()}catch(b){}return a};
z.f.qh=function(a){this.Z.onMouseUp(a)};z.f.dd=function(a){this.Z.onMouseDown(a)};z.f.cd=function(a){this.Z.onKeyDown(a)};z.f.ph=function(a){try{this.Z.onMouseOver(a)}catch(b){}};z.f.Ah=function(a){try{this.Ha=a}catch(b){z.S.a().b(b)}};z.f.Ub=function(){try{return this.Ha.name}catch(a){z.S.a().b(a)}};z.f.Sb=function(){try{return this.Ha.bar}catch(a){z.S.a().b(a)}};
z.f.Aa=function(){try{var a=this.Z.getPredictionCoordinates(),b={x:10,y:10};b.x=(0,window.parseInt)(a.left.substring(0,a.left.length-2))-32;b.y=(0,window.parseInt)(a.top.substring(0,a.top.length-2))+2;return b}catch(c){z.S.a().b(c)}};z.t("textHelp.parsers.HTMLParser",Fk);Fk.prototype.getParserName=Fk.prototype.Ub;Fk.prototype.getBarConfigFromParser=Fk.prototype.Sb;Fk.prototype.setParserConfig=Fk.prototype.Ah;Fk.prototype.getPredictionPosition=Fk.prototype.Aa;z.Lf("HTMLParser");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_HTMLParser.js