(function(z){
var Zj=function(a){return z.Za.concat.apply(z.Za,arguments)};var ak=function(a,b,c){this.fc=a||null;this.Lp=!!c};var bk=function(a){if(!a.Ba&&(a.Ba=new z.Wc,a.za=0,a.fc))for(var b=a.fc.split("\x26"),c=0;c<b.length;c++){var d=b[c].indexOf("\x3d"),e=null,g=null;0<=d?(e=b[c].substring(0,d),g=b[c].substring(d+1)):e=b[c];e=(0,window.decodeURIComponent)(e.replace(/\+/g," "));e=ck(a,e);a.add(e,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};
var ck=function(a,b){var c=String(b);a.Lp&&(c=c.toLowerCase());return c};var dk=function(a){var b=z.Pc(a);if("undefined"==typeof b)throw Error("Keys are undefined");var c=new ak(null,0,void 0);a=z.Oc(a);for(var d=0;d<b.length;d++){var e=b[d],g=a[d];if(z.ia(g)){var h=c;h.remove(e);0<g.length&&(h.fc=null,h.Ba.set(ck(h,e),z.$a(g)),h.za+=g.length)}else c.add(e,g)}return c};
var ek=function(){window.m_webReaderElem=window.document.getElementById("webReaderModule");window.m_extensionPath=window.m_webReaderElem.getAttribute("data-root");var a=window.document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href=window.m_extensionPath+"assets/checkit/checkit.css";window.m_webReaderElem.appendChild(a);this.Kf(window.m_extensionPath+"assets/checkit/gdciip.js",function(){this.Kf(window.m_extensionPath+"assets/checkit/ciip.js",function(){this.Kf(window.m_extensionPath+
"assets/checkit/ciiprw4gc.js",function(){}.bind(this))}.bind(this))}.bind(this));z.T.a().j("onGetCheckItOnOff",this.Fq,this)};
var fk=function(a){this.h=this.te=this.O=null;null!=z.J("docs-texteventtarget-iframe")&&null!=z.J("docs-texteventtarget-iframe")&&(this.O=z.J("docs-texteventtarget-iframe").contentDocument,this.te=z.J("docs-texteventtarget-iframe").contentWindow,this.h=z.J("kix-appview-editor"),this.R=a,new z.zd,this.oa=!1,this.lc=this.Cb=this.lb=null,this.U=[],this.Ac=!1,this.G={},this.G.va=0,this.G.Cl="",this.G.Bl="",this.G.nc=null,this.Kd=this.Jd=0,this.ad=/\w/i,this.F={},this.F.parentId="kix-appview-editor",this.F.positionId=
"kix-cursor",this.F.seq="1",this.mf=z.S.a().bind(this,this.Lh),this.lf=z.S.a().bind(this,this.uf),this.Ka=this.ia=null,this.Hh=this.Te=!1,this.$g=null)};var gk=function(a){this.la=a;this.Xm="";this.Dc=this.bj=0;this.cn=this.Yf=this.lh="";this.Qk=null;a=window.location.pathname.split("/");this.Yi=a[a.length-2];this.dn=""};
var hk=function(a){try{var b=new z.zd;z.E(b,"complete",z.S.a().bind(a,a.xq));var c=dk(new z.Wc({Authorization:"Bearer "+a.Dc}));b.send("https://www.googleapis.com/drive/v2/files?q\x3dtitle%3D'TexthelpVoiceNoteConfig'\x26spaces\x3dappDataFolder","GET",null,c)}catch(d){z.S.a().b(d)}};var ik=function(a,b,c){try{var d=new z.zd;null!==c&&z.E(d,"complete",c);var e=dk(new z.Wc({Authorization:"Bearer "+a.Dc}));d.send("https://www.googleapis.com/drive/v2/files/"+b,"GET",null,e)}catch(g){z.S.a().b(g)}};
var jk=function(a){try{var b=new z.zd;z.E(b,"complete",z.S.a().bind(a,a.Gq));var c=dk(new z.Wc({Authorization:"Bearer "+a.Dc}));b.send("https://www.googleapis.com/drive/v2/files/"+a.Yi+"/properties/voicenotefolder","GET",null,c)}catch(d){z.S.a().b(d)}};var kk=function(a){try{var b=new window.FileReader;b.readAsDataURL(a.Xm);b.onloadend=z.S.a().bind(a,a.rq)}catch(c){z.S.a().b(c)}};var lk=function(a){try{z.S.a().fireEvent(a,"mousedown"),z.S.a().fireEvent(a,"mouseup"),z.S.a().fireEvent(a,"click")}catch(b){z.S.a().b(b)}};
var rk=function(a,b){this.R=a;this.la=b;this.Zc=null;this.af=this.Xk=!1;this.T=this.$a=null;this.kh=0;this.bl=null;z.E(window.document,"mouseover",this.ph,!0,this);z.E(window.document,"mouseout",this.Uq,!0,this);null!=z.J("docs-texteventtarget-iframe")&&(this.O=z.J("docs-texteventtarget-iframe").contentDocument,this.Xl=z.S.a().bind(this,this.ol),this.Yl=z.S.a().bind(this,this.pl),this.Lo=z.S.a().bind(this,this.ll))};
var sk=function(a,b){try{(0,window.clearTimeout)(a.kh),a.af=!0,a.kh=(0,window.setTimeout)(a.Yl,250),b.play()}catch(c){z.S.a().b(c)}};
var Y=function(){this.hd="kix-selection-overlay";this.De="kix-selection-overlay-mac";this.oc="kix-appview-editor";this.Ob="kix-cursor";this.Ce="kix-cursor-caret";this.ea="kix-lineview";this.fb="kix-lineview-text-block";this.Sj="kix-paragraphrenderer";this.Oh="kix-page";this.lg="thRWGDns";this.kg="thCTag";this.xa=this.lg+":"+this.kg;this.I="textHELPWR";this.p="thWord";this.Da="thSpace";this.wf=100;this.Rf=this.Ha=null;this.Xe=-1;this.ue=0;this.kc=z.ij.a().sd();this.mb=this.kc.sentences.wordEnds;this.pa=
[];this.Pk=[];this.Wf=0;this.Mf=null;this.jh=!1;this.ad=/\w/i;this.Yb=/[\u200B-\u200D\uFEFF\u25A0-\u27A2]/g;this.h=z.J(this.oc);this.qe=[];this.Sf=this.Ga=null;this.Bb=-1;this.Ye=!1;this.Kb=null;this.$e=z.S.a().bind(this,this.Ld);z.S.a();this.la=new fk(this);this.hq=new rk(this,this.la);window.addEventListener("message",this.$e,!1);z.T.a().j("onSpeechStateChanged",this.Pn,this);this.Zb=null;var a=this.la;if(null!=a.O){var b=z.S.a().bind(a,a.ve);a.O.addEventListener("keyup",b,!0);b=z.S.a().bind(a,
a.oh);a.O.addEventListener("keypress",b,!0);b=z.S.a().bind(a,a.cd);a.O.addEventListener("keydown",b,!0);b=z.S.a().bind(a,a.dd);z.E(window.document,"click",b,!0);b=z.S.a().bind(a,a.qh);z.E(window.document,"mouseup",b);b=z.S.a().bind(a,a.ff);z.E(a.h,"scroll",b);b=z.S.a().bind(a,a.mh);z.E(window,"resize",b);z.T.a().j("onPredictionChange",a.gf,a);z.T.a().j("onWRPredictionStateChanged",a.Md,a);z.T.a().j("onSpeechRecognitionChange",a.sh,a);z.T.a().j("onFocusOnCursor",a.mj,a)}new ek};
var tk=function(a,b){var c={};c.vg=z.J(a.Ce);if(null==c.vg)return c;c.Wd=z.Q(c.vg);var d=z.Ij(c.vg,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d/2,10),e=0;a.P(c.vg,"kix-cursor-italic")&&(e=d/Math.tan(Math.PI/180*77));c.Wd.y+=d;c.Wd.x+=e+(c.vg.offsetWidth/2+.5);c.element=uk(a,c.Wd.x,c.Wd.y,b);return c};
var uk=function(a,b,c,d){a=a.Cf(b,c);b=null;for(c=0;c<a.length;c++){if("string"==typeof a[c].className&&void 0!==a[c].className&&-1<a[c].className.indexOf(d))if(-1<a[c].className.indexOf("kix-lineview-content"))b=a[c];else return a[c];if("kix-lineview"==a[c].className)return a[c]}return b};var vk=function(a,b,c){for(var d=0;d<b.length;d++)wk(a,[b[d].toLowerCase()],c)};
var wk=function(a,b,c){b=b.map(function(a){return a.toLowerCase()});for(var d=0;d<c.length;d++)for(var e=c[d],g=e.filter(function(a){return"is"==a.ty})[0].s,h=e.filter(function(a){return"is"==a.ty})[0].ibi,e=e.filter(function(a){var c="text"==a.st,d=a.sm&&a.sm.ts_bgc&&-1!=b.indexOf(a.sm.ts_bgc);return"as"==a.ty&&c&&d}),l=0;l<e.length;l++){var m=e[l].si-h;a.ck.push({text:g.substr(m,e[l].ei-h-m+1),color:e[l].sm.ts_bgc.toUpperCase()})}};
var xk=function(a,b,c,d){try{var e=new window.XMLHttpRequest;e.onreadystatechange=function(){if(4==e.readyState&&200==e.status){var a=window.document.createElement("div");a.id="th-page-reloaded";a.style.display="none";a.innerHTML=e.responseText;var g={ck:[],title:window.document.getElementsByClassName("docs-title-input")[0].getAttribute("value"),url:window.location.href},m=[];z.S.a().Kj(a.getElementsByTagName("script")).filter(function(a){return"DOCS_modelChunk \x3d ["==a.innerHTML.substr(0,19)}).forEach(function(a){a=
a.innerHTML.replace("DOCS_modelChunk \x3d ","");a=a.substr(0,a.lastIndexOf("}]; ")+2);a=JSON.parse(a);m.push(a)});2==b?vk(g,c,m):wk(g,c,m);d(g)}}.bind(a);e.open("GET",window.location.href,!0);e.send()}catch(g){z.S.a().b(g)}};
var yk=function(a,b,c){var d=b.nextSibling;null!==d?(a.Pd(d,a.h),(0,window.setTimeout)(function(){var a=z.Ge(d);if(0<a.length&&" "!==a)if(window.paragraph=z.J(this.Sj,d),null==window.paragraph)yk(this,d,c);else{if(window.nextPageLine=this.Hm(window.paragraph,!0),null!==window.nextPageLine)if(a=window.nextPageLine.closest(".kix-page-header"),null!==a){if(null!==a.nextElementSibling)if(1>a.nextElementSibling.textContent.trim().length)yk(this,d,c);else{for(var a=a.nextSibling.querySelectorAll("."+this.ea),
b=null,h=0;h<a.length;h++)0<a[h].textContent.trim().length&&(b=a[h],h=a.length);null!==b&&c(this.Fi(b))}}else c(this.Fi(window.nextPageLine))}else yk(this,d,c)}.bind(a),100)):c([])};
var zk=function(a){try{for(var b=["thrwgdns:thctag","title","desc"];void 0!=a.nodeName&&b.includes(a.nodeName.toLowerCase());)if(null!=a.parentElement)a=a.parentElement;else break;return void 0==a.nodeName?!1:"svg"==a.nodeName.toLowerCase()||"image"==a.nodeName.toLowerCase()||"desc"==a.nodeName.toLowerCase()||"title"==a.nodeName.toLowerCase()?!0:!1}catch(c){return!1}};
var Ak=function(a){for(var b=a;!a.classList.contains("kix-embeddedobject-crop");)if(null!=a.parentElement)a=a.parentElement;else break;return a.classList.contains("kix-embeddedobject-crop")?a:b};var Bk=function(a,b){try{a.Mf=z.X(a.Oh);a.Wf=a.h.scrollTop;a.Ye=!1;var c=z.S.a().bind(a,a.xj);(0,window.setTimeout)(function(){c(0,b)},0)}catch(d){z.S.a().b(d)}};
z.S.prototype.Cf=z.ca(19,function(a,b){if(void 0!==window.document.Cf)return window.document.Cf(a,b);for(var c=[],d=[],e,g;(e=window.document.elementFromPoint(a,b))&&-1===c.indexOf(e)&&null!=e;)c.push(e),d.push({value:e.style.getPropertyValue("pointer-events"),zl:e.style.getPropertyPriority("pointer-events")}),e.style.setProperty("pointer-events","none","important");for(e=d.length;g=d[--e];)c[e].style.setProperty("pointer-events",g.value?g.value:"",g.zl);return c});
z.Wc.prototype.Bf=z.ca(1,function(a){return z.Yc(this.Ec,a)});z.f=ak.prototype;z.f.Ba=null;z.f.za=null;z.f.Cm=function(){bk(this);return this.za};z.f.add=function(a,b){bk(this);this.fc=null;a=ck(this,a);var c=this.Ba.get(a);c||this.Ba.set(a,c=[]);c.push(b);this.za++;return this};z.f.remove=function(a){bk(this);a=ck(this,a);return this.Ba.Bf(a)?(this.fc=null,this.za-=this.Ba.get(a).length,this.Ba.remove(a)):!1};z.f.clear=function(){this.Ba=this.fc=null;this.za=0};
z.f.Bf=function(a){bk(this);a=ck(this,a);return this.Ba.Bf(a)};z.f.Uc=function(){bk(this);for(var a=this.Ba.ud(),b=this.Ba.Uc(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};z.f.ud=function(a){bk(this);var b=[];if(z.s(a))this.Bf(a)&&(b=Zj(b,this.Ba.get(ck(this,a))));else{a=this.Ba.ud();for(var c=0;c<a.length;c++)b=Zj(b,a[c])}return b};
z.f.set=function(a,b){bk(this);this.fc=null;a=ck(this,a);this.Bf(a)&&(this.za-=this.Ba.get(a).length);this.Ba.set(a,[b]);this.za++;return this};z.f.get=function(a,b){var c=a?this.ud(a):[];return 0<c.length?String(c[0]):b};
z.f.toString=function(){if(this.fc)return this.fc;if(!this.Ba)return"";for(var a=[],b=this.Ba.Uc(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.ud(d),g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="\x3d"+(0,window.encodeURIComponent)(String(d[g])));a.push(h)}return this.fc=a.join("\x26")};z.f.clone=function(){var a=new ak;a.fc=this.fc;this.Ba&&(a.Ba=this.Ba.clone(),a.za=this.za);return a};
z.f.extend=function(a){for(var b=0;b<arguments.length;b++)z.Qc(arguments[b],function(a,b){this.add(b,a)},this)};
ek.prototype.Kf=function(a,b){var c=window.document.documentElement.getElementsByTagName("body")[0];if(null==c||void 0==c)c=window.document.body;var d=window.document.createElement("script");d.src=a;d.async=!0;d.onload=d.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(d.onload=d.onreadystatechange=null,c.removeChild(d),void 0!=b&&b())};c.appendChild(d)};
ek.prototype.Fq=function(a){try{if(a[0]){if(null==window.texthelp.CheckitLib.checkItManagerInstance){var b=window.document.querySelector("#thSpeechStreamTBPlaceHolder").getAttribute("data-root").split("/")[2];window.texthelp.CheckitLib.checkItManagerInstance=new window.texthelp.CheckitLib.CheckItManagerRW4GC(window.location.href,b)}var c=z.V.a().M().language.ju;window.texthelp.CheckitLib.checkItManagerInstance.language=c;window.texthelp.CheckitLib.checkItManagerInstance.checkItOn();window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose()}else window.texthelp.CheckitLib.checkItManagerInstance.checkItOff()}catch(d){z.S.a().b(d)}};
ek.prototype.Bm=function(){};z.f=fk.prototype;z.f.ve=function(a){var b=[];b.push(a.keyCode);z.T.a().k("onKeyUpEvent",b);null!==this.ia&&((0,window.clearTimeout)(this.ia),this.ia=null);a.ctrlKey&&17!==a.keyCode&&(this.Hh=!0,null!==this.$g&&(0,window.clearTimeout)(this.$g),this.$g=(0,window.setTimeout)(function(){(0,window.clearTimeout)(this.$g);this.$g=null;this.Hh=!1}.bind(this),1E3));17===a.keyCode?this.Te=this.Hh?!1:!0:(this.ia=(0,window.setTimeout)(this.mf,100),this.Te=!1)};z.f.oh=function(){};
z.f.cd=function(a){if(a.ctrlKey&&47<a.keyCode&&58>a.keyCode){var b=[];b.push(a);null!==this.lb&&((0,window.clearTimeout)(this.lb),this.lb=null);this.lb=(0,window.setTimeout)(function(){this.Jn(b)}.bind(this),10);z.Rj()&&(a.preventDefault(),a.stopPropagation())}40===a.keyCode&&this.Te&&(this.Hh=this.Te=!1,a.preventDefault(),a.stopPropagation(),window.texthelp.RW4GC.thToolbarStoreInstance.onFocusBar(window.document.activeElement));this.Te=!1};z.f.Jn=function(a){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(a)};
z.f.Ma=function(){null!==this.ia&&((0,window.clearTimeout)(this.ia),this.ia=null);this.ia=(0,window.setTimeout)(this.mf,10)};
z.f.Lh=function(){this.ia=null;if(this.oa){var a=this.R.Me();if(null==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=z.V.a().M().prediction.results,c=z.V.a().M().language.services;this.G.va++;999<this.G.va&&(this.G.va=0);var d='"'+z.S.a().mg(a.context)+'","'+b+'","en_US"',e='{ "parent":"'+this.R.oc+'", "position":"'+this.R.Ob+'","addSpace":false,"seq":"'+this.G.va+'"}';z.S.a().Bh(this.G.va);this.G.nc=a;e=z.qd(e);d=[];d[0]=a.context;d[1]=b;d[2]=c;if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();
else e.context=d,window.postMessage({method:"thPrediction",type:"1757FROM_PAGERW4G",payload:e},"*")}}};z.f.qh=function(){if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose(),this.Zd();else return!0};z.f.ff=function(){try{var a=this.R.Aa();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)}catch(b){}};
z.f.mh=function(){(0,window.setTimeout)(function(){var a=this.R.Aa();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)}.bind(this),0)};z.f.uf=function(a){if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose(),this.Zd();else{var b=z.Me(a.target,"kix-lineview-text-block");null==b&&(b=z.J("kix-lineview-text-block",a.target.parentNode));null!==b&&(this.oa&&this.Ma(),this.Zd())}};
z.f.dd=function(a){null!==this.Ka&&((0,window.clearTimeout)(this.Ka),this.Ka=null);var b=this;this.Ka=(0,window.setTimeout)(function(){b.lf(a)},300)};z.f.Zd=function(){z.T.a().k("onWordChanged",[])};
z.f.gf=function(a){try{if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=this.G.nc,c=b.prepunc+a[0]+b.postpunc;this.ta("ArrowRight",b.selectRight);this.ta("Shift+ArrowLeft",b.selectLeft+b.selectRight);b.spaceatstart&&(c=" "+c);b.spaceatend&&(c+=" ");this.fg(c);b.spaceatend||this.ta("ArrowRight");var d=z.S.a().Xa();a=[];a.push("prediction insert");a.push(d.Email);a.push(d.Email.split("@")[1]);window.postMessage({type:"1757FROM_PAGERW4G",
key:"function",method:"SendEvent",parameters:a},"*");this.Ma()}}catch(e){z.S.a().b(e)}};z.f.Md=function(a){try{this.oa=a[0];var b=z.J("kix-cursor-caret",this.h);if(null!==b&&this.oa){var c=0,d=z.Q(b),e=z.Ij(b,"height"),e=e.substr(0,e.length-2),e=(0,window.parseInt)(e,10);d.y+=e/2;z.S.a().P(b,"kix-cursor-italic")&&(c=e/Math.tan(Math.PI/180*77));d.x+=c;this.bi(d.x,d.y)}this.oa&&(a=[],a.push("kix-appview-editor"),this.Ma(),z.T.a().k("onOpenPredictionWindow",a))}catch(g){z.S.a().b(g)}};
z.f.mj=function(){try{var a=z.J("kix-cursor-caret",this.h);null!==a&&(z.S.a().fireEvent(a,"click"),a.focus())}catch(b){z.S.a().b(b)}};z.f.sh=function(a){try{"scratch that"==a.toLowerCase().trim()?this.ta("CTRL+Z"):this.fg(a)}catch(b){z.S.a().b(b)}};z.f.gc=function(){this.U.keydown=this.tb("keydown",this.O);this.U.keyup=this.tb("keyup",this.O);this.U.keypress=this.tb("keypress",this.O);this.U.mousedown=this.tb("mousedown",this.h);this.U.mouseup=this.tb("mouseup",window.document);this.Ac=!0};
z.f.tb=function(a,b){try{var c=[],d;for(d in b)if(d.match(/^closure/)&&"number"!=typeof b[d]){var e=b[d];if(e){if(!this.Cb)for(var g in e){var h=e[g];if(h&&h!=b)for(var l in h){var m=h[l];m&&void 0!=m.length&&m[0].src==b&&(this.Cb=g)}}for(var n in e[this.Cb])if(n==a)for(var p=e[this.Cb][n],q=0;q<p.length;q++){if(!this.lc&&p[q].src==b)for(var u in p[q])if(p[q][u].src==b){this.lc=u;break}c.push({um:p[q],uc:p[q][this.lc]})}}}return c}catch(r){z.S.a().b(r)}};
z.f.ta=function(a,b,c){void 0==c&&(c="keydown");void 0==b&&(b=1);if(!(1>b)){this.Ac||this.gc();void 0==b&&(b=1);var d={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.O,defaultPrevented:!1,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.O.body,target:this.O.body,timeStamp:(new Date).getTime(),type:c,view:this.te,which:0};switch(a){case "SPACE":d.ctrlKey=
!0;d.keyCode=32;d.which=32;break;case "CTRL+Z":d.ctrlKey=!0;d.keyCode=90;d.which=90;break;case "Apple+Z":d.metaKey=!0;d.keyCode=90;d.which=90;break;case "Delete":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Backspace":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Newline":d.defaultPrevented=!0;d.keyCode=13;d.which=13;break;case "Home":d.keyCode=36;d.which=36;break;case "CTRL+Home":d.ctrlKey=!0;d.keyCode=36;d.which=36;break;case "Shift+ArrowLeft":d.keyCode=37;d.shiftKey=!0;d.which=
37;break;case "Shift+ArrowRight":d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "ArrowRight":d.keyCode=39;d.which=39;break;case "ArrowLeft":d.keyCode=37;d.which=37;break;case "CTRL+Shift+ArrowRight":d.ctrlKey=!0;d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "CTRL+ALT+M":d.ctrlKey=!0;d.keyCode=77;d.shiftKey=!1;d.altKey=!0;d.which=77;break;case "CMD+ALT+M":d.metaKey=!0;d.keyCode=77;d.shiftKey=!1;d.altKey=!0;d.which=77;break;case "CTRL+Shift+S":d.ctrlKey=!0;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;
d.which=83;break;case "CMD+Shift+S":d.metaKey=!0;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=83;break;case "CTRL+Shift+F":d.metaKey=!0;d.keyCode=70;d.shiftKey=!0;d.altKey=!1;d.which=70;break;case "CMD+Shift+F":d.metaKey=!0;d.keyCode=70;d.shiftKey=!0;d.altKey=!1;d.which=70;break;default:return}for(a=0;a<b;a++)for(var e in this.U[c])this.U[c][e].uc(d)}};
z.f.fg=function(a){this.Ac||this.gc();for(var b={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.O,defaultPrevented:!0,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.O.body,target:this.O.body,timeStamp:0,type:"keypress",view:this.te,which:0},c,d=0;d<a.length;d++){c=a[d];b.charCode=c.charCodeAt(0);b.keyCode=c.charCodeAt(0);b.which=c.charCodeAt(0);
b.shiftKey=c.toUpperCase()==c?!0:!1;b.timeStamp=(new Date).getTime();try{switch(b.keyCode){case 10:if(0<d){if(10!=a[d-1].charCodeAt(0)){b.charCode=13;b.keyCode=13;b.which=13;var e}}else b.charCode=13,b.keyCode=13,b.which=13;for(e in this.U.keydown)this.U.keydown[e].uc(b);break;case 13:for(e in this.U.keydown)this.U.keydown[e].uc(b);break;default:for(e in this.U.keypress)this.U.keypress[e].uc(b)}}catch(g){}}};
z.f.bi=function(a,b){this.Ac||this.gc();z.Q(this.h);if(!(a<this.h.x||a>this.h.x+this.h.offsetWidth||b<this.h.y||b>this.h.y+this.h.offsetHeight)){var c=z.S.a().bind(this,this.Cg);this.Jd=a;this.Kd=b;(0,window.setTimeout)(c,1)}};
z.f.Cg=function(){var a={altKey:!1,bubbles:!0,button:0,cancelBubble:!1,cancelable:!0,charCode:0,clientX:this.Jd,clientY:this.Kd,clipboardData:void 0,ctrlKey:!1,currentTarget:window.document,dataTransfer:null,defaultPrevented:!1,detail:1,eventPhase:0,fromElement:null,keyCode:0,layerX:0,layerY:0,metaKey:!1,offsetX:0,offsetY:0,pageX:0,pageY:0,relatedTarget:null,returnValue:!0,screenX:0,screenY:0,shiftKey:!1,srcElement:this.h,target:this.h,timeStamp:(new Date).getTime(),toElement:this.h,type:null,view:window,
which:1,x:0,y:0},b=["mousedown","mouseup"],c;for(c in b){a.type=b[c];"mouseup"==b[c]&&(a.srcElement=a.target=a.toElement=window.document);for(var d in this.U[b[c]])this.U[b[c]][d].uc(a)}};z.f=gk.prototype;z.f.pc=function(a,b){try{this.bj=z.T.a().j("onAddVoiceNoteToken",this.tr,this),window.postMessage({type:"1757FROM_PAGERW4G",key:"function",method:"AddVoiceNote",parameters:[]},"*"),this.Xm=a,this.Qk=b}catch(c){z.S.a().b(c)}};z.f.tr=function(a){try{z.T.a().ig(this.bj),this.Dc=a,hk(this)}catch(b){z.S.a().b(b)}};
z.f.xq=function(a){try{var b=JSON.parse(a.target.H.response).items;if(0==b.length)try{var c=new z.zd;z.E(c,"complete",z.S.a().bind(this,this.Cr));var d=dk(new z.Wc({Authorization:"Bearer "+this.Dc,"Content-type":"application/json"})),e='{"title": "'+z.U.a().ga("voicenote_folder")+'","mimeType": "application/vnd.google-apps.folder"}';c.send("https://www.googleapis.com/drive/v2/files","POST",e,d)}catch(g){z.S.a().b(g)}else{var h=b[0];try{this.cn=h.id,this.lh=h.description,ik(this,this.lh,z.S.a().bind(this,
this.Br))}catch(l){z.S.a().b(l)}}}catch(m){z.S.a().b(m)}};z.f.wq=function(){try{jk(this)}catch(a){z.S.a().b(a)}};
z.f.Cr=function(a){try{var b=this.lh=JSON.parse(a.target.H.response).id;try{var c=new z.zd;z.E(c,"complete",z.S.a().bind(this,this.wq));var d=dk(new z.Wc({Authorization:"Bearer "+this.Dc,"Content-type":"application/json"}));c.send("https://www.googleapis.com/drive/v2/files?q\x3dtitle%3D'TexthelpVoiceNoteConfig'","POST",'{"title": "TexthelpVoiceNoteConfig","parents": [{"id": "appfolder"}],"description": "'+b+'"}',d)}catch(e){z.S.a().b(e)}}catch(g){z.S.a().b(g)}};
z.f.Br=function(a){try{var b=JSON.parse(a.target.H.response);if(void 0!==b.error||b.labels.trashed){var c=this.cn,d=z.S.a().bind(this,this.Aq);try{var e=new z.zd;null!==d&&z.E(e,"complete",d);var g=dk(new z.Wc({Authorization:"Bearer "+this.Dc}));e.send("https://www.googleapis.com/drive/v2/files/"+c,"DELETE",null,g)}catch(h){z.S.a().b(h)}}else jk(this)}catch(l){z.S.a().b(l)}};z.f.Aq=function(){try{hk(this)}catch(a){z.S.a().b(a)}};
z.f.Gq=function(a){try{var b=JSON.parse(a.target.H.response);void 0!==b.error?ik(this,this.Yi,z.S.a().bind(this,this.In)):(this.Yf=b.value,ik(this,this.Yf,z.S.a().bind(this,this.Dr)))}catch(c){z.S.a().b(c)}};
z.f.In=function(a){try{this.dn=JSON.parse(a.target.H.response).title;try{var b=new z.zd;z.E(b,"complete",z.S.a().bind(this,this.zq));var c=dk(new z.Wc({Authorization:"Bearer "+this.Dc,"Content-type":"application/json"}));b.send("https://www.googleapis.com/drive/v2/files","POST",'{"title": "'+this.dn+'","parents": [{"id": "'+this.lh+'"}],"mimeType": "application/vnd.google-apps.folder"}',c)}catch(d){z.S.a().b(d)}}catch(e){z.S.a().b(e)}};
z.f.Dr=function(a){try{var b=JSON.parse(a.target.H.response);void 0!==b.error||b.labels.trashed?ik(this,this.Yi,z.S.a().bind(this,this.In)):kk(this)}catch(c){z.S.a().b(c)}};
z.f.zq=function(a){try{this.Yf=JSON.parse(a.target.H.response).id;var b=new z.zd;z.E(b,"complete",z.S.a().bind(this,this.xr));var c=dk(new z.Wc({Authorization:"Bearer "+this.Dc,"Content-type":"application/json"}));b.send("https://www.googleapis.com/drive/v2/files/"+this.Yi+"/properties","POST",'{"key": "voicenotefolder","value": "'+this.Yf+'"}',c)}catch(d){z.S.a().b(d)}};
z.f.xr=function(){try{var a=new z.zd;z.E(a,"complete",z.S.a().bind(this,this.lr));var b=dk(new z.Wc({Authorization:"Bearer "+this.Dc,"Content-type":"application/json"}));a.send("https://www.googleapis.com/drive/v2/files/"+this.Yf+"/permissions","POST",'{"role": "reader","type": "anyone"}',b)}catch(c){z.S.a().b(c)}};z.f.lr=function(a){try{JSON.parse(a.target.H.response),kk(this)}catch(b){z.S.a().b(b)}};
z.f.rq=function(a){try{var b=a.currentTarget.result.replace(/^data:audio\/(wav|ogg);base64,/,""),c=new z.zd;z.E(c,"complete",z.S.a().bind(this,this.qq));var d=dk(new z.Wc({Authorization:"Bearer "+this.Dc,"Content-type":'multipart/form-data; boundary\x3d"rw4g"'})),e='--rw4g\nContent-Type: application/json; charset\x3dUTF-8\n\n{"title": "'+z.U.a().ga("voicenote_filename")+'.wav", "description": "Read\x26Write for Google Chrome\u2122", "mimeType": "audio/wav","parents": [{"id": "'+this.Yf+'"}]}\n--rw4g\nContent-Type: audio/wav\nContent-Transfer-Encoding: base64\n\n'+
b+"\n--rw4g--\n";c.send("https://www.googleapis.com/upload/drive/v2/files?uploadType\x3dmultipart","POST",e,d)}catch(g){z.S.a().b(g)}};
z.f.qq=function(a){try{this.la.ta("CTRL+ALT+M",1,"keydown");this.la.ta("CTRL+ALT+M",1,"keyup");this.la.ta("CMD+ALT+M",1,"keydown");this.la.ta("CMD+ALT+M",1,"keyup");var b=window.document.activeElement;this.Qk();z.J("docos-input-buttons-post",b.parentElement);var c;var d=a.target;c=d.H?z.qd(d.H.responseText):void 0;var e=c.webContentLink.split("\x26")[0];b.value="Texthelp;"+e+";";b.focus();b.click();this.zb=null;lk(b);try{var g=z.J("docos-input-buttons-post",b.parentElement);lk(g)}catch(h){z.S.a().b(h)}}catch(l){z.S.a().b(l)}};z.f=rk.prototype;z.f.pc=function(a,b){try{null==this.bl&&(this.bl=new gk(this.la)),this.bl.pc(a,b)}catch(c){z.S.a().b(c)}};
z.f.ph=function(a){try{var b=a.target;if(void 0!=b&&void 0!=b.classList&&null!=b.classList){var c=z.Me(b,"docos-anchoreddocoview");if(null!=c){var d=z.J("docos-collapsible-replyview",c);if(null!=d&&d!=this.Zc){this.Xk=!0;var e=z.J("kix-thvoicenote-overlay");z.we(e);this.af=!1;this.T=null;this.Zc=d;if(null!=this.Zc){var g=this.Zc.innerText;if(-1!=g.indexOf("Texthelp;https://")&&null!=z.Me(this.Zc,"docos-anchoreddocoview")){var h=g.split(";")[1],e=z.J("kix-thvoicenote-overlay");null==e&&(e=z.Mi(z.Ck));
e.style.top=(0,window.parseInt)(this.Zc.offsetTop)+"px";e.style.left=(0,window.parseInt)(this.Zc.offsetLeft)+"px";e.style.width=(0,window.parseInt)(this.Zc.offsetWidth)+"px";e.style.height=(0,window.parseInt)(this.Zc.offsetHeight)+"px";e.style.background="white";e.style.visibility="visible";var l=z.J("thVNPlayback",e);this.$a={rj:l.getAttribute("data-percent")||0,size:l.getAttribute("data-size")||60,lineWidth:l.getAttribute("data-line")||4,rotate:l.getAttribute("data-rotate")||0};var m=window.document.createElement("canvas");
"undefined"!==typeof window.G_vmlCanvasManager&&window.G_vmlCanvasManager.Pt(m);this.T=m.getContext("2d");m.width=m.height=this.$a.size;m.id="thVNCanPlayback";m.className="thVNCanPlayback";l.appendChild(m);this.T.translate(this.$a.size/2,this.$a.size/2);this.T.rotate((-.5+this.$a.rotate/180)*Math.PI);this.T.translate(.5,.5);this.Ua(this.T,"#efefef",this.$a.lineWidth,1);0<this.$a.rj&&this.Ua(this.T,"#555555",this.$a.lineWidth,this.$a.rj/100);var n=z.J("thVNCanPlayback",e),p=z.J("thVNIcon",e);z.E(n,
"mouseup",this.Lo,!0,this);z.E(p,"mouseup",this.Xq,!0,this);var q=z.J("thVNAudio",e);q.src=h;this.Zc.parentElement.appendChild(e);q.onended=this.Xl}}}}}}catch(u){z.S.a().b(u)}};z.f.Uq=function(a){try{if(this.Xk){var b=a.Va.toElement;void 0!=b&&void 0!=b.classList&&null!=b.classList&&null===z.Me(b,"docos-anchoreddocoview")&&(this.Xk=!1)}}catch(c){z.S.a().b(c)}};
z.f.Xq=function(a){try{var b=z.Me(a.currentTarget,"thVNPlayback");if(null!=b){var c=z.J("thVNIcon",b);if(null!=c){var d=z.J("thVNAudio",b);if(this.af){this.af=!1;z.S.a().md(c,"thVNPause","thVNPlay");try{d.pause()}catch(e){z.S.a().b(e)}}else{this.af=!0;z.S.a().md(c,"thVNPlay","thVNPause");sk(this,d);var g=z.S.a().ra();if(null==g)return null;window.postMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:g,action:"voice note play",label:g.split("@")[1]}},"*")}}}}catch(h){z.S.a().b(h)}};
z.f.ll=function(a){try{var b=z.J("thVNAudio");if(null!=b){var c=z.Q(a.currentTarget),d,e;d=a.clientX-c.x;e=a.clientY-c.y;var g=z.mg(a.currentTarget),h=2*Math.PI,l=(0,window.parseInt)((Math.atan2(e-g.height/2,d-g.width/2)+h)%h/h*100),l=l+25;99<l&&(l-=100);b.currentTime=l/100*b.duration;sk(this,b);var m=z.Me(a.currentTarget,"thVNPlayback");if(null!=m){var n=z.J("thVNIcon",m);null!=n&&z.S.a().P(n,"thVNPlay")&&z.S.a().md(n,"thVNPlay","thVNPause")}}}catch(p){z.S.a().b(p)}};
z.f.ol=function(a){try{this.af=!1;(0,window.clearTimeout)(this.kh);this.kh=0;var b=a.currentTarget;if(null!=b){var c=b.parentElement;if(null!=c){var d=z.J("thVNIcon",c);null!=d&&(this.T.clearRect(-100,-100,200,200),this.Ua(this.T,"#efefef",this.$a.lineWidth,1),0<this.$a.rj&&this.Ua(this.T,"#555555",this.$a.lineWidth,this.$a.rj/100),z.S.a().md(d,"thVNPause","thVNPlay"))}}}catch(e){z.S.a().b(e)}};
z.f.pl=function(){try{if(this.af){var a=z.J("thVNAudio");if(null!=a){var b=(100/a.duration*a.currentTime).toFixed();this.T.clearRect(-100,-100,200,200);this.Ua(this.T,"#efefef",this.$a.lineWidth,1);this.Ua(this.T,"#555555",this.$a.lineWidth,b/100);this.kh=(0,window.setTimeout)(this.Yl,250)}}}catch(c){z.S.a().b(c)}};
z.f.Ua=function(a,b,c,d){d=Math.min(Math.max(0,d||1),1);var e=(this.$a.size-this.$a.lineWidth)/2;a.beginPath();a.arc(0,0,e,0,2*Math.PI*d,!1);a.strokeStyle=b;a.lineCap="round";a.lineWidth=c;a.stroke()};z.Yj.qj="Parser";z.B(Y,z.Oj);z.f=Y.prototype;z.f.Ah=function(a){try{this.Ha=a}catch(b){z.S.a().b(b)}};z.f.Ub=function(){try{return this.Ha.name}catch(a){z.S.a().b(a)}};z.f.Sb=function(){try{return this.Ha.bar}catch(a){z.S.a().b(a)}};z.f.Pn=function(a){this.jh=0<a.length?a[0]:!1};z.f.pc=function(a,b){try{this.hq.pc(a,b)}catch(c){z.S.a().b(c)}};
z.f.Og=function(){try{var a=this.de(),b=!1;z.S.a();for(var c=this.kc.sentences.sentenceEndExclusions,d=0;d<a.length-1;d++){var e=z.Pj(c,a[d]);if(!e){try{e=this.Pk[d]}catch(g){e=!1}void 0==e&&(e=!1)}if(!e)for(var h in this.mb)-1!==a[d].search(this.mb[h])&&(b=!0,d=a.length)}if(!b)return a;var l=z.X(this.hd);if(1>l.length&&(l=z.X(this.De),1>l.length))return this.Gi(!0);var l=Array.prototype.slice.call(l,0),m=z.S.a().bind(this,this.Gj);l.sort(m);this.ma();var n=z.Q(l[0]),p=z.Ij(l[0],"height"),p=p.substr(0,
p.length-2),p=(0,window.parseInt)(p,10);n.y+=p/2;this.Kb=z.Q(l[l.length-1]);var q=z.Ij(l[l.length-1],"width"),q=q.substr(0,q.length-2),q=(0,window.parseInt)(q,10);this.Kb.x+=q;return this.ie(n.x,n.y)}catch(u){z.S.a().b(u)}};z.f.Hf=function(){try{var a=z.X(this.hd);return 1>a.length&&(a=z.X(this.De),1>a.length)?!1:!0}catch(b){z.S.a().b(b)}};
z.f.vb=function(){try{var a=window.document.getElementById("th-RW4GC-picture-dictionary"),b=window.document.getElementById("th-RW4GC-translator"),c=window.document.getElementById("th-RW4GC-prediction");if((null!=window.document.getElementById("th-RW4GC-dictionary")||null!=a||null!=b||null!=c)&&this.jh)return"";var a=[],d=RegExp("\u200b","g"),e=z.X(this.hd);if(1>e.length){e=z.X(this.De);if(1>e.length){var g=z.J(this.Ob);if(null!==g){var h=z.Q(g),l=z.J(this.Ce),m=z.Ij(l,"height"),m=m.substr(0,m.length-
2),m=(0,window.parseInt)(m,10)/2,e=0;this.P(l,"kix-cursor-italic")&&(e=m/Math.tan(Math.PI/180*77));h.y+=m;h.x+=l.offsetWidth/2+e;var n=z.Ij(l,"display");z.P(l,"display","none");this.ie(h.x,h.y,!1);var m="",p=this.vd(h.x,h.y,0);if(null==p)return z.P(l,"display",n),this.ma(),a;h=[];h.push(p);for(var g=e=0,q=window.document.querySelectorAll(".textHELPWR"),u=0;u<q.length;u++)if(q[u]==p){if(0<u)for(g=u-1;q[g].classList.contains("thWord")&&!(h.unshift(q[g]),g--,0>g););e=u+1;if(e<q.length)for(;q[e].classList.contains("thWord")&&
!(h.push(q[e]),e++,e>=q.length););break}for(u=0;u<h.length;u++)m+=h[u].textContent;this.ma();a.push(m.replace(d,""));z.P(l,"display",n)}return a}return""}if(this.jh)return"";u=this.de();2<u.length?a.push(u[0].replace(d,"")):a.push(u.join(" ").replace(d,""));this.ma();return a}catch(r){z.S.a().b(r)}};
z.f.Cf=function(a,b){for(var c=[],d=[],e,g;(e=window.document.elementFromPoint(a,b))&&-1===c.indexOf(e)&&null!=e;)c.push(e),d.push({value:e.style.getPropertyValue("pointer-events"),zl:e.style.getPropertyPriority("pointer-events")}),e.style.setProperty("pointer-events","none","important");for(e=d.length;g=d[--e];)c[e].style.setProperty("pointer-events",g.value?g.value:"",g.zl);return c};
z.f.Me=function(){try{var a=[];a.context="";a.word="";a.cursorindex="";a.spaceatstart=!1;a.spaceatend=!1;a.prepunc="";a.postpunc="";a.selectRight=0;a.selectLeft=0;a.prechar="";a.currentchar="";a.postchar="";var b=z.J(this.Ce);z.Q(b);var c=window.document.createRange(),d=tk(this,"kix-embeddedobject-view");if(!(null!==d.element&&-1<d.element.className.indexOf("kix-embeddedobject-view"))){d=tk(this,"kix-wordhtmlgenerator-word-node");if(null==d.element&&(d=tk(this,"kix-lineview"),null==d.element))return null;
d.element=z.Me(d.element,"kix-lineview");if(null==d.element)return null;for(var e=b="",g=!1,h=window.document.createTreeWalker(d.element,window.NodeFilter.SHOW_TEXT),l=h.nextNode(),m="",n="",p=0,q=0;l;){for(var u=l.textContent.split(""),r=0;r<u.length;r++){c.setStart(l,r);c.setEnd(l,r+1);var w=c.getClientRects(),v;a:{for(var K=d.Wd.x+1,F=d.Wd.y,A=0;A<w.length;++A){var N=w[A];if(N.left<K&&N.right>K&&N.top<F&&N.bottom>F){v=N;break a}if(N.left>K){v="leftpastcaret";break a}}v=!1}"leftpastcaret"==v?(r=
u.length+10,g=!0):v?(r=u.length+10,g=!0):"\u200b"!==c.toString()&&(n=c.toString(),b+=n);p++}g||p!=d.element.textContent.length||(b=d.element.textContent,g=!0,p=b.length+1);if(g){var O=b.split(/(.*?[.?!])/g);1<O.length&&(b=O[O.length-1]);a.context=d.element.textContent.substr(0,p-1).replace(this.Yb,"").split(/(.*?[.?!])/g);for(r=a.context.length;r--;)1>a.context[r].length&&a.context.splice(r,1);for(var L=d.element.textContent.substr(0).replace(this.Yb,"").split(/(.*?[.?!])/g),r=L.length;r--;)""===
L[r]&&L.splice(r,1);0<q&&(L[0]=L[0].substr(q),a.context[0]=a.context[0].substr(q));if(1>a.context.length)for(var ma=d.element.previousSibling;ma;)10<ma.textContent.split(/\s/g).length?(m=ma.textContent+m,ma=null):(m=ma.textContent+m,ma=ma.previousSibling);0<a.context.length?(L=L[a.context.length-1],a.context=a.context[a.context.length-1],e=L.substr(a.context.length),-1!==".?!".indexOf(a.context.substr(a.context.length-2),1)&&(a.spaceatstart=!0)):L=e=a.context="";var bb=a.context.substr(a.context.length-
1);if((0==a.context.length||"\u00a0"==bb||-1!==".?!".indexOf(bb))&&!z.S.a().Tb()["Predict Ahead"])return null==this.Zb&&(this.Zb=z.J("kix-thprediction-popup")),null!==this.Zb&&(z.P(this.Zb,"display","none"),z.S.a().Ej(!1)),null;var hc=a.context.split(/\s/g);a.word=L.split(/\s/g)[hc.length-1];var Md=hc[hc.length-1].replace(this.Yb,"");a.cursorindex=Md.length;if(0==a.context.length||0==e.trim().replace(/[\u200B]/g,"").length)a.spaceatend=!0;0==a.cursorindex?(a.selectLeft=0,a.selectRight=0,a.spaceatend=
!0,a.word=""):(a.selectLeft=Md.replace(this.Yb,"").length,a.selectRight=a.word.replace(this.Yb,"").length-a.selectLeft);var ic=a.word.match(this.ad),Ia=a.word,jc=Ia.indexOf(ic);0<jc&&(a.prepunc=Ia.substring(0,jc).replace(/[\u200B]/g,""),Ia=Ia.substring(jc).replace(/[\u200B]/g,""));var Ia=Ia.split("").reverse().join(""),ic=Ia.match(this.ad),Cc=Ia.indexOf(ic);0<Cc&&(a.postpunc=Ia.substring(0,Cc),a.postpunc=a.postpunc.split("").reverse().join("").replace(/[\u200B]/g,""),Ia=Ia.substring(Cc));l=null}else zk(l.parentElement)&&
(q=b.length),l=h.nextNode()}a.context=m+a.context;a.context=a.context.replace(this.Yb,"").replace(/\u00a0/g," ");return a}}catch(cd){z.S.a().b(cd)}};
z.f.ce=function(){try{this.Wc();var a={};a.Wa=z.Je(z.X(this.p)[0]);if(!(1>a.Wa.length)){for(var b=z.J(this.oc),c=b.innerHTML.split("\x3cthrwgdns:thctag")[0],d=c.split("\x3e"),e=[],g=0;g<d.length;g++){var h=d[g];"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0])}a.Lc=e.join(" ").split(a.Wa).length-1;var l=z.X(this.p);a.Za=a.Wa;a.yc=a.Lc;a.Za=z.Je(l[l.length-1]);if(0<a.Za.length){var m=b.innerHTML.split("\x3c/thrwgdns:thctag\x3e");m[m.length-1]=null;c=m.join();c=c.substr(0,c.length-2);d=c.split("\x3e");
e=[];for(g=0;g<d.length;g++)h=d[g],"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0]);a.yc=e.join(" ").split(a.Za).length-1}this.ma();return a}}catch(n){z.S.a().b(n)}};
z.f.Yc=function(a){try{a=a.substring(1);var b=(0,window.parseInt)(a,16),b="rgb("+(b>>16&255)+","+(b>>8&255)+","+(b&255)+")",c=window.document.getElementById("bgColorButton");null==c&&(c=window.document.getElementById("textColorButton"));var d=window.document.getElementById("jfk-palette-cell-169");if(null!==c||null!==d){z.S.a().fireEvent(c,"mousedown");z.S.a().fireEvent(c,"mouseup");z.S.a().fireEvent(c,"click");var d=window.document.getElementById("jfk-palette-cell-169"),e=d.firstChild.style.backgroundColor;
d.firstChild.style.backgroundColor=b;z.S.a().fireEvent(d,"mousedown");z.S.a().fireEvent(d,"mouseup");z.S.a().fireEvent(d,"click");d.firstChild.style.backgroundColor=e}else{var g=this.ce(),h='{ "doc":"'+window.location.href+'","color":"'+a+'","startWordCount":"'+g.Lc+'", "startWord":"'+(0,window.escape)(g.Wa)+'", "endWordCount":"'+g.yc+'", "endWord":"'+(0,window.escape)(g.Za)+'"}',h=z.qd(h);window.postMessage({method:"highlightSelection",type:"1757FROM_PAGERW4G",payload:h},"*")}}catch(l){z.S.a().b(l)}};
z.f.sc=function(){try{var a=window.document.getElementById("bgColorButton");null==a&&(a=window.document.getElementById("textColorButton"));if(null!==a){z.S.a().fireEvent(a,"mousedown");z.S.a().fireEvent(a,"mouseup");z.S.a().fireEvent(a,"click");var b=window.document.getElementById("jfk-palette-cell-169"),c=b.firstChild.style.backgroundColor;b.firstChild.style.backgroundColor="rgb(255,255,255)";z.S.a().fireEvent(b,"mousedown");z.S.a().fireEvent(b,"mouseup");z.S.a().fireEvent(b,"click");b.firstChild.style.backgroundColor=
c}else{var d=this.ce(),e='{ "doc":"'+window.location.href+'","startWordCount":"'+d.Lc+'", "startWord":"'+(0,window.escape)(d.Wa)+'", "endWordCount":"'+d.yc+'", "endWord":"'+(0,window.escape)(d.Za)+'"}',e=z.qd(e);window.postMessage({method:"clearHighlights",type:"1757FROM_PAGERW4G",payload:e},"*")}}catch(g){z.S.a().b(g)}};
z.f.Wc=function(a){try{void 0==a&&(a=!0);var b=[],c=[],d=z.X(this.hd);if(1>d.length&&(d=z.X(this.De),1>d.length))return b;var d=Array.prototype.slice.call(d,0),e=z.S.a().bind(this,this.Gj);d.sort(e);for(var g=d,d=[],e=0;e<g.length;e++)a?z.S.a().Pm(g[e])&&d.push(g[e]):d.push(g[e]);if(0==d.length)return b;a=[];for(var h=g=null,l=null,e=0;e<d.length;e++){for(var h=z.X(this.ea,d[e].parentNode),m=0;m<h.length;m++)h[m]!==l&&(a.push(h[m]),l=h[m]);1>h.length&&(g=z.Me(d[e],this.ea),g!==l&&(a.push(g),l=g))}g=
e=null;for(h=0;h<a.length;h++)for(e=z.X(this.fb,a[h]),l=0;l<e.length;l++)this.Hc(e[l]),null===g&&(g=e[l]);var n;n=zk(d[0])?z.Kj(Ak(d[0]),this.h):z.Kj(d[0],this.h);var p;p=zk(d[d.length-1])?z.Kj(Ak(d[d.length-1]),this.h):z.Kj(d[d.length-1],this.h);var q=z.mg(d[d.length-1]);p.x+=q.width-4;this.$h(n);this.Zh(p);this.nf();this.pa=z.X(this.p);var u=window.document.querySelectorAll("."+this.I),d="";for(n=0;n<u.length;n++)u[n].classList.contains(this.p)?d+=u[n].textContent:(b.push(d),d="",c.push(zk(this.pa[n])));
b.push(d);c.push(zk(this.pa[n]));this.Pk=c;return b}catch(r){z.S.a().b(r)}};z.f.getSelection=function(a){try{this.Nf=a;var b=this.ce(),c='{ "doc":"'+window.location.href+'","startWordCount":"'+b.Lc+'", "startWord":"'+(0,window.escape)(b.Wa)+'", "endWordCount":"'+b.yc+'", "endWord":"'+(0,window.escape)(b.Za)+'"}',c=z.qd(c);window.postMessage({method:"getSelection",type:"1757FROM_PAGERW4G",payload:c},"*")}catch(d){z.S.a().b(d)}};
z.f.As=function(){this.h.scrollTop=this.Wf;var a=this.Wc(!1);this.ma();this.Rf(a);this.Rf=null};z.f.zs=function(){this.h.scrollTop=this.Wf;var a=this.Wc(!1);this.ma();a=a.join(" ").replace(/(\.+|\:|\!|\?)(\"*|\'*|\)*|}*|]*)(\s|\n|\r|\r\n)/gm,".\x3cbr /\x3e\x3cbr /\x3e$2").split("|");a={documentTitle:window.document.title.replace(" - Google Docs",""),html:a.join(" ")};this.Rf(a);this.Rf=null};z.f.Vc=function(a){try{this.Rf=a,Bk(this,this.As.bind(this))}catch(b){z.S.a().b(b)}};
z.f.ui=function(a){try{this.Rf=a,Bk(this,this.zs.bind(this))}catch(b){z.S.a().b(b)}};z.f.de=function(){try{var a=z.X(this.hd);if(1>a.length&&(a=z.X(this.De),1>a.length))return this.Gi(!0);var b=this.Wc();return 1>b.length&&1>a.length?this.Gi(!0):b}catch(c){z.S.a().b(c)}};z.f.wg=function(){try{this.ak();var a=z.X(this.I);if(0!==a.length)for(var b=a[0].parentNode;null!==a;){b.innerHTML=z.Je(b);a=z.X(this.I);if(0===a.length)break;b=a[0].parentNode}}catch(c){z.S.a().b(c)}};
z.f.Oc=function(a,b,c,d){try{this.xg(a,b,c,d)}catch(e){z.S.a().b(e)}};z.f.Af=function(a,b,c){try{this.yg(a,b,c)}catch(d){z.S.a().b(d)}};
z.f.Kg=function(){try{var a={trailingSpace:!1},b=this.de(),c=z.J(this.Ob);if(null!==c){var d=z.Q(c),e=z.J(this.Ce),g=z.Ij(e,"height"),g=g.substr(0,g.length-2),g=(0,window.parseInt)(g/2,10),c=0;this.P(e,"kix-cursor-italic")&&(c=g/Math.tan(Math.PI/180*77));d.y+=g;d.x+=c+(e.offsetWidth/2+.5);d.x+=1;d.y+=4;var h=this.vd(d.x,d.y,0),l=z.Q(h);l.x+=this.xh(h.offsetWidth);l.y+=this.xh(h.offsetHeight);if(l.x<d.x-2||l.y<d.y-2)a.trailingSpace=!0;a.currentWord=(0,window.parseInt)(h.className.split(" ")[2])}this.ma();
a.words=b.join(" ");return a}catch(m){z.S.a().b(m)}};z.f.wb=function(a){try{var b=function(a,b){b?a.classList.add("thImageHighlighted"):a.classList.remove("thImageHighlighted")};0<a&&(zk(this.pa[a-1])?b(Ak(this.pa[a-1]),!1):z.S.a().sa(this.pa[a-1],"thHighlighted"));if(zk(this.pa[a]))b(Ak(this.pa[a]),!0);else{try{this.Pd(this.pa[a],this.h)}catch(c){}z.S.a().ba(this.pa[a],"thHighlighted")}}catch(d){z.S.a().b(d)}};z.f.stop=function(){try{this.ma()}catch(a){z.S.a().b(a)}};
z.f.he=function(a,b){try{var c=null,d=z.V.a().M().speechoptions.continousreading;if(a&&!d&&null===this.Kb)this.Ga=null,this.Bb=-1,b(null);else{var e=z.Q(this.Ga);e.x+=this.Bb;for(var g=this.Ga.querySelectorAll(".kix-wordhtmlgenerator-word-node"),h=0;h<g.length;h++){var l=z.Q(g[h]).x;if(e.x>=l&&e.x<g[h].offsetWidth+l){var m=z.Q(g[h]);e.y=m.y;h=g.length}}if(-1<this.Bb)!d&&null!==this.Kb&&(e.y>this.Kb.y||e.y===this.Kb.y&&e.x>=this.Kb.x)?(this.Ga=null,this.Bb=-1,b(null)):(this.Ga=null,this.Bb=-1,b(this.ie(e.x+
5,e.y+2)));else{this.Bb=-1;if(null!==this.Sf)for(var n=this.Sf.nextElementSibling;null!==n;){if(0<n.textContent.trim().length){this.Sf=n;var p;a:{try{c=[];this.Hc(n);this.Aj();this.nf();for(var q=z.X(this.p),u=0;u<q.length;u++)c.push(z.Ge(q[u]));(0,window.setTimeout)(this.zf.bind(this),this.wf);this.pa=z.X(this.p);1===this.pa.length&&this.wb(0);p=c;break a}catch(r){z.S.a().b(r)}p=void 0}b(p);return}n=n.nextElementSibling}c=this.Ga.closest(".kix-page");if(null==c)return[];u=c.querySelectorAll("."+
this.ea);if(1==u.length)return yk(this,c,b);var w=this.Ga;p=null;for(q=0;q<u.length;q++)w==u[q]&&(window.currentCellIndex=q,q=u.length);for(q=++window.currentCellIndex;q<u.length;q++)0<u[q].textContent.trim().length&&(p=u[q],q=u.length);if(null==p)return yk(this,c,b);b(this.Fi(p));return[]}}}catch(v){z.S.a().b(v)}};
z.f.Gi=function(a){var b=z.J(this.Ob);if(null!==b){var b=z.Q(b),c=z.J(this.Ce),d=z.Ij(c,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d/2,10),e=0;this.P(c,"kix-cursor-italic")&&(e=d/Math.tan(Math.PI/180*77));b.y+=d;b.x+=e+(c.offsetWidth/2+.5);return this.ie(b.x,b.y,a)}return null};
z.f.Fk=function(a){try{var b=[];if(null!==a){var c=z.X(this.fb,a);for(a=0;a<c.length;a++)this.Hc(c[a]);this.Aj()}this.nf();for(var d=z.X(this.p),c=0;c<d.length;c++)b.push(z.Ge(d[c]));(0,window.setTimeout)(this.zf.bind(this),this.wf);this.pa=z.X(this.p);1===this.pa.length&&this.wb(0);return b}catch(e){z.S.a().b(e)}};
z.f.ie=function(a,b,c){try{void 0==c&&(c=!0);var d=[],e=[],g=this.Gg(a,b);if(null==g&&(g=this.Gg(a,b),null==g))return null;if(null!==g){this.Sf=z.Me(g,this.fb);if(null==this.Sf){var h=g.querySelectorAll("."+this.fb);if(0==h.length||1==h.length&&1==h.length&&0==h[0].textContent.trim().length)return;var l=z.Q(h[0]),m=l.x,n=m+h[0].offsetWidth;1<h.length&&(n=m+h[h.length-1].offsetWidth);return a>=n?this.ie(n-4,l.y,c):this.ie(m,l.y,c)}this.Hc(this.Sf);this.Gl(a,b)}this.nf();var p=z.X(this.p);if(0==p.length)return d;
for(a=0;a<p.length;a++)d.push(z.Ge(p[a])),e.push(zk(p[a]));(0,window.setTimeout)(this.zf.bind(this),this.wf);this.pa=z.X(this.p);1===this.pa.length&&c&&this.wb(0);this.Pk=e;return d}catch(q){z.S.a().b(q)}};
z.f.Hc=function(a){try{var b=z.J(this.fb,a);if(null===b)if(this.P(a,this.fb))b=a;else throw Error("The element has no text child.");a={};a.key=b;a.value=a.key.innerHTML;this.qe.push(a);var c=RegExp("\u200b","g"),b=b.childNodes;for(a=0;a<b.length;a++){for(var d=z.Qj(z.S.a(),b[a]),e=[],g=!1,h=0;h<d.length;h++){var l=d[h];if(g=zk(l.parentElement))try{var m;var n=l;try{for(var p=["svg","image","title","desc"];!p.includes(n.nodeName.toLowerCase());)if(null!=n.parentElement)n=n.parentElement;else break;
m=void 0==n.nodeName?"undefined":"svg"==n.nodeName.toLowerCase()||"image"==n.nodeName.toLowerCase()?"image":"desc"==n.nodeName.toLowerCase()?"desc":"title"==n.nodeName.toLowerCase()?"title":"undefined"}catch(q){m="undefined"}"desc"==m.toLowerCase()?-1==l.nodeValue.indexOf("gmath_latex")&&e.push(d[h]):e.push(d[h])}catch(u){e.push(d[h])}else e.push(d[h])}for(g=0;g<e.length;g++)if(0<e.length){for(var r=e[g].nodeValue.split(/\s/),n=h="",p=0;p<r.length;p++){var w=r[p].replace(c,"");"\x3c"===w.substr(0,
1)?(n+="\x3c"+this.xa+" class\x3d'"+this.I+"'\x3e"+w.trim()+"\x3c/"+this.xa+"\x3e",p<r.length-1&&(n+="\x3c"+this.xa+" class\x3d'"+this.I+" "+this.Da+"'\x3e\x26nbsp;\x3c/"+this.xa+"\x3e")):(" "===w||""===w)&&p<r.length-1?n+="\x3c"+this.xa+" class\x3d'"+this.I+" "+this.Da+"'\x3e\x26nbsp;\x3c/"+this.xa+"\x3e":0<w.length&&(this.Xe++,n+="\x3c"+this.xa+" class\x3d'"+this.I+" "+this.p+"'\x3e"+w.trim()+"\x3c/"+this.xa+"\x3e",p<r.length-1&&(n+="\x3c"+this.xa+" class\x3d'"+this.I+" "+this.Da+"'\x3e\x26nbsp;\x3c/"+
this.xa+"\x3e"))}var h=h+n,v=z.ne("thrwgdns:thctag");v.innerHTML=h;var K=e[g],F=K.parentNode;F&&F.replaceChild(v,K);this.Xe=-1}}}catch(A){z.S.a().b(A)}};z.f.Pd=function(a,b){try{if(void 0!=a&&void 0!=b){var c=0,d=a;if(null!=d&&void 0!=d){for(;d!==b;)null!==d.offsetTop&&void 0!==d.offsetTop&&(c+=d.offsetTop),d=d.offsetParent;c+30>b.scrollTop&&c<b.scrollTop+b.offsetHeight-30||(b.scrollTop=c-30)}}}catch(e){z.S.a().b(e)}};
z.f.ma=function(){try{if(0!==z.X(this.I).length){for(var a in this.qe)this.qe[a].key.innerHTML=this.qe[a].value;this.qe.length=0}}catch(b){z.S.a().b(b)}};
z.f.$h=function(a){try{var b=[];this.ue=0;for(var c=z.X(this.I),d=0;d<c.length;d++){var e;e=zk(c[d])?z.Kj(Ak(c[d]),this.h):z.Kj(c[d],this.h);var g=z.mg(c[d]);if(e.x+g.width<a.x)b.push(c[d]),this.P(c[d],this.p)&&this.ue++;else{for(;this.P(c[d],this.Da);)b.push(c[d]),d++;d=c.length}}if(0!==b.length){a="";var h=b[0].parentNode;3==h.firstChild.nodeType&&(a+=h.firstChild.textContent,z.we(h.firstChild));c="";for(d=0;d<b.length;d++)b[d].parentNode!==h&&(h.innerHTML=a+h.innerHTML,a="",h=b[d].parentNode),
c=z.Je(b[d]),a+=c,z.we(b[d]);0!=h.childNodes.length&&3==h.lastChild.nodeType&&(a+=h.lastChild.textContent);h.innerHTML=a+h.innerHTML}}catch(l){z.S.a().b(l)}};
z.f.Zh=function(a){try{for(var b=[],c=z.X(this.I),d=c.length-1;0<=d;--d){var e;e=zk(c[d])?z.Kj(Ak(c[d]),this.h):z.Kj(c[d],this.h);e.x+=2;if(e.x>=a.x)b.push(c[d]),this.Ga=this.nk(c[d]),zk(c[d])?this.Bb=z.Kj(Ak(c[d]),this.Ga).x:this.Bb=z.Kj(c[d],this.Ga).x;else{for(;this.P(c[d],this.Da);)b.push(c[d]),d--;d=-1}}if(0!==b.length){a="";b.reverse();c=b;for(d=b.length-1;0<=d;d--)b[d].parentNode!==c&&(c.innerHTML+=a,a="",c=b[d].parentNode),a=z.Je(b[d])+a,z.we(b[d]);z.Je(c.innerHTML);c.innerHTML+=a}}catch(g){z.S.a().b(g)}};
z.f.$j=function(a){try{var b=z.X(this.I,a),b=Array.prototype.slice.call(b,0);if(0!==b.length){a="";for(var c=b,d=b.length-1;0<=d;d--)b[d].parentNode!==c&&(c.innerHTML+=a,a="",c=b[d].parentNode),a=z.Je(b[d])+a,z.we(b[d]);c.innerHTML+=a}}catch(e){z.S.a().b(e)}};z.f.nf=function(){try{for(var a=-1,b=z.X(this.I),c=0;c<b.length;c++)this.P(b[c],this.p)&&a++,this.md(b[c],(a+this.ue).toString(),a.toString())}catch(d){z.S.a().b(d)}};
z.f.zf=function(){try{var a=z.X(this.hd);1>a.length&&(a=z.X(this.De));for(var b=0;b<a.length;b++)z.we(a[b])}catch(c){z.S.a().b(c)}};z.f.Gg=function(a,b){try{return uk(this,a,b,"kix-lineview")}catch(c){z.S.a().b(c)}};
z.f.vd=function(a,b){try{var c=z.S.a().Cf(a,b),d=c.find(function(a){return a.classList.contains(this.p)}.bind(this));if(void 0==d){var e=c.find(function(a){return a.classList.contains(this.Da)}.bind(this));if(void 0!==e){for(var g=[].slice.call(window.document.querySelectorAll("."+this.I)),h=g.findIndex(function(a){return e==a}.bind(this)),c=null,d=h;0<=d;d--)if(g[d].classList.contains(this.p)){c=g[d];break}for(var l=null,d=h;d<g.length;d++)if(g[d].classList.contains(this.p)){l=g[d];break}if(null==
l&&null==c)return null;if(null==l)return c;if(null==c)return l;var m=c.getBoundingClientRect().x+c.getBoundingClientRect().width,n=l.getBoundingClientRect().x;return a<=m+((n-m)/2+.5)?c:l}l=c[0].closest("."+this.ea);if(null==l)return d;var p=l.querySelectorAll("."+this.p);return a<=z.Q(p[0]).x?p[0]:p[p.length-1]}return d}catch(q){z.S.a().b(q)}};
z.f.xh=function(a){try{var b=z.J("kix-zoomdocumentplugin-inner",this.h);if(null==b)return a;var c=z.Ij(b,"webkitTransform");if(null==c||0==c.length)return a;c=c.substr(6,c.length-7);return a*(0,window.parseFloat)(c)}catch(d){z.S.a().b(d)}};
z.f.Gl=function(a,b){try{var c=this.vd(a,b,0);if(null===c||void 0===c){var d=z.X(this.p);if(0==d.length){this.ma();return}var e=z.Q(d[0]).x,g=e+d[0].offsetWidth;1<d.length&&(e=z.Q(d[d.length-1]).x,g=e+d[d.length-1].offsetWidth);c=d[0];a>=g&&(c=d[d.length-1])}this.Ie(c);c=this.vd(a,b,0);this.He(c)}catch(h){z.S.a().b(h)}};z.f.Aj=function(){try{var a=z.X(this.p);this.Ie(a[0]);a=z.X(this.p);null===a[0]?this.ma():0==a.length?this.ma():this.He(a[0])}catch(b){z.S.a().b(b)}};
z.f.Ie=function(a){try{var b=null,c=null,d=null,e=!1;if(this.P(a,this.p))b=a;else if(this.P(a,this.ea)){for(var g=z.X(this.fb,a),h=0;h<g.length;h++)this.Hc(g[h]);c=z.X(this.p,a);b=c[c.length-1];e=!0}else return;z.S.a();var l=this.kc.sentences.sentenceEndExclusions,g=-1;null===c&&(d=z.Me(b,this.ea),c=z.X(this.p,d));if(e)g=c.length-1;else for(var m=0;m<c.length;m++)c[m]===b&&(g=m,m=c.length);if(-1!==g){a=g;!e&&0<a&&a--;if(0<g){e=-1;for(m=a;0<=m;m--){var n=z.Pj(l,z.Ge(c[m]));n||(n=zk(c[m]));if(!n)for(var p in this.mb)-1!==
c[m].innerText.search(this.mb[p])&&(e=m,m=-1)}if(-1<e){if(c.length-1===e)this.$j(z.Me(c[e],this.ea));else{var q;q=zk(c[e+1])?z.Kj(Ak(c[e+1]),this.h):z.Kj(c[e+1],this.h);this.$h(q)}return}}null===d&&(d=z.Me(b,this.ea));this.Ie(d.previousSibling)}}catch(u){z.S.a().b(u)}};
z.f.He=function(a){try{if(null!=a){var b=null,c=null,d=null,e=!1;if(this.P(a,this.p))b=a;else if(this.P(a,this.ea)){for(var d=a,g=z.X(this.fb,a),h=0;h<g.length;h++)this.Hc(g[h]);c=z.X(this.p,a);b=c[0];e=!0}else return;z.S.a();var l=this.kc.sentences.sentenceEndExclusions;a=-1;null===c&&(d=z.Me(b,this.ea),c=z.X(this.p,d));if(e)a=0;else for(var m=0;m<c.length;m++)c[m]===b&&(a=m,m=c.length);if(-1!==a){e=-1;for(m=a;m<c.length;m++){var n=z.Pj(l,z.Ge(c[m]));n||(n=zk(c[m]));if(!n)for(var p in this.mb)-1!==
c[m].innerText.search(this.mb[p])&&(e=m,m=c.length)}-1===e&&null===d.nextSibling&&(e=c.length-1);if(e===c.length-1||0<c.length&&-1==e)this.Ga=d;if(-1<e){if(e<c.length-1){var q;q=zk(c[e+1])?z.Kj(Ak(c[e+1]),this.h):z.Kj(c[e+1],this.h);this.Zh(q)}}else null===d&&(d=z.Me(b,this.ea)),this.He(d.nextSibling)}}}catch(u){z.S.a().b(u)}};z.f.nk=function(a){try{return null===a?null:this.P(a,this.ea)?a:z.Me(a,this.ea)}catch(b){z.S.a().b(b)}};
z.f.ji=function(a,b){try{var c=window.document.createEvent("MouseEvents");c.initMouseEvent.apply(c,b);a.dispatchEvent(c)}catch(d){z.S.a().b(d)}};z.f.bk=function(){};z.f.ak=function(){try{var a=z.J(this.Ob);if(null!==a){var b=z.Q(a);this.bk(b.x,b.y)}}catch(c){z.S.a().b(c)}};z.f.xj=function(a,b){try{if(a<this.Mf.length&&!1===this.Ye){this.Pd(this.Mf[a],this.h);var c=z.S.a().bind(this,this.xj);a+=1;(0,window.setTimeout)(function(){c(a,b)},30)}else this.Ye=!0,void 0!==b&&b()}catch(d){z.S.a().b(d)}};
z.f.Ld=function(a){try{if(void 0!=a.source&&void 0!=a.data&&a.source==window&&"1757FROM_BGRW4G"==a.data.type)if("onGetSelection"==a.data.method){var b=z.qd(a.data.payload);this.Nf(b)}else if("onCollectHighlights"==a.data.method){var c=z.qd(a.data.payload);if(void 0!==c.auth)window.textHelp.webreaderapi.EventBusSingleton.getInst().publish("onShowDocsOAuthDialog",c.auth);else if("string"===typeof c){var d=null,e=z.S.a().Tc(),d=window.open(c,"_ntthch"+e);d.focus();this.jc(c)}else void 0!==c.auth?this.jc("false"):
0==c[0].highlights.length?this.jc("false"):this.jc("true")}else if("onVocabWords"==a.data.method){var g=z.qd(a.data.payload);void 0!==g.auth?window.textHelp.webreaderapi.EventBusSingleton.getInst().publish("onShowDocsOAuthDialog",g.auth):"string"===typeof g&&(d=null,e=z.S.a().Tc(),d=window.open(g,"_ntthchVc"+e),d.focus(),this.cl(g))}}catch(h){z.S.a().b(h)}};
z.f.xg=function(a,b,c){try{this.jc=a,z.U.a(),xk(this,b,c,function(a){var b=z.U.a().ga("ch_documentTitle");window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"CollectHighlights",parameters:{highlights:a.ck,title:window.document.getElementsByTagName("title")[0].innerHTML,url:window.location.href,docTitle:b}},"*")})}catch(d){z.S.a().b(d)}};
z.f.yg=function(a,b){try{xk(this,0,b,function(a){var b=[];z.S.a().Kj(a.ck).filter(function(a){if(3>a.text.trim().split(/\s/g).length)return b.push(a.text.trim()),!0});b.sort();a=window.textHelp.webreader.ConfigurationSingleton.getInst().getConfiguration();var c={};c.words=b;c.locale=a.locale;c.user=a.serversettings.user;c.translations={};c.translations.docTitle=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_document_title");c.translations.title=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_title");
c.translations.heading=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_heading");c.translations.symbol=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_symbol");c.translations.notes=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_notes");c.translations.meaning=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_meaning");c.locale=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().language.services;
window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"Vocab",parameters:c},"*")})}catch(c){z.S.a().b(c)}};z.f.Gj=function(a,b){try{var c,d;zk(a)?window.thPos=z.Kj(Ak(a),this.h):c=z.Kj(a,this.h);zk(b)?window.thPos=z.Kj(Ak(b),this.h):d=z.Kj(b,this.h);if(c.y>d.y)return 1;if(c.y<d.y)return-1;if(c.y===d.y){if(c.x<d.x)return-1;if(c.x>d.x)return 1}return 0}catch(e){z.S.a().b(e)}};
z.f.Fi=function(a){try{if(null===a)return[];this.Pd(a,this.h);var b=z.V.a().M().speechoptions.continousreading;this.Ga=null;this.Bb=-1;if(null!==a){var c=z.Q(a);if(!b&&null!==this.Kb&&c.y>this.Kb.y)return this.Ga=null,this.Bb=-1,[];var d=z.Ij(a,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d,10);c.y+=d/2;return this.Fk(a)}return[]}catch(e){z.S.a().b(e)}};
z.f.Hm=function(a,b){try{var c=a.nextSibling;!0===b&&(c=a);if(null===c)return null;for(;null!==c;){var d=z.Ge(c);if(0<d.length&&" "!==d)return z.J(this.ea,c);c=c.nextSibling}return null}catch(e){z.S.a().b(e)}};z.f.Ol=function(a){try{a.doc=window.location.href,window.postMessage({method:"updateSelection",type:"1757FROM_PAGERW4G",payload:a},"*")}catch(b){z.S.a().b(b)}};
z.f.ed=function(){try{this.la.mj(),this.la.ta("CTRL+Shift+S",1,"keydown"),this.la.ta("CTRL+Shift+S",1,"keyup"),this.la.ta("CMD+Shift+S",1,"keydown"),this.la.ta("CMD+Shift+S",1,"keyup")}catch(a){z.S.a().b(a)}};z.f.fd=function(){};z.f.Aa=function(){try{var a=z.J(this.Ob),b={x:10,y:10};if(null==a)return{x:-1,y:-1};var c=new z.H(a.offsetLeft,a.offsetTop),d=z.mg(a);b.x=c.x-d.width-a.scrollWidth-18;b.y=c.y+d.height+a.scrollHeight+6;return b}catch(e){z.S.a().b(e)}};z.t("textHelp.parsers",z.Yj);
z.t("textHelp.parsers.Parser",Y);Y.prototype.hiliteNextSentence=Y.prototype.he;Y.prototype.hiliteWord=Y.prototype.wb;Y.prototype.highlightSelection=Y.prototype.Yc;Y.hiliteWord=Y.wb;Y.prototype.getUserSettings=Y.prototype.M;Y.prototype.getSelection=Y.prototype.getSelection;Y.prototype.getSelectionLocal=Y.prototype.Vc;Y.prototype.clearHighlights=Y.prototype.sc;Y.prototype.getTextWithContext=Y.prototype.Kg;Y.prototype.updateSelection=Y.prototype.Ol;Y.prototype.startSpeechRecognition=Y.prototype.ed;
Y.prototype.stopSpeechRecognition=Y.prototype.fd;Y.prototype.getParserName=Y.prototype.Ub;Y.prototype.getBarConfigFromParser=Y.prototype.Sb;Y.prototype.getPredictionPosition=Y.prototype.Aa;z.Lf("GDocsParser");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_GDocsParser.js