(function(z){
var bm=function(a,b){z.Jc.call(this);this.Rg=a||1;this.kg=b||z.k;this.bk=(0,z.ta)(this.dt,this);this.Tk=(0,z.Ni)()};var cm=function(a,b){var c=0;(0,z.Rc)(a,function(a,e,g){b.call(void 0,a,e,g)&&++c},void 0);return c};
var dm=function(){this.Md=!1;this.bc=z.K("kix-thprediction-popup");this.jj=null;this.Vf=this.ih=this.zn=!1;this.Hs=z.S.a().bind(this,this.dr);this.Wf=this.ij=null;this.gj=!1;this.wn=null;z.T.a().j("onClosePredictionWindow",this.Fq,this);z.T.a().j("onOpenPredictionWindow",this.hr,this);z.T.a().j("onClearPredictionWindow",this.Eq,this);z.T.a().j("onPredictionKeyDownEvent",this.lr,this)};
var em=function(a){var b={},c=window,d="undefined"!=typeof a.href?a.href:String(a);a=b.target||a.target;var e=[],g;for(g in b)switch(g){case "width":case "height":case "top":case "left":e.push(g+"\x3d"+b[g]);break;case "target":case "noreferrer":break;default:e.push(g+"\x3d"+(b[g]?1:0))}g=e.join(",");if(b.noreferrer){if(b=c.open("",a,g))z.D&&-1!=d.indexOf(";")&&(d="'"+d.replace(/'/g,"%27")+"'"),b.opener=null,d=z.Da(d),b.document.write('\x3cMETA HTTP-EQUIV\x3d"refresh" content\x3d"0; url\x3d'+d+'"\x3e'),
b.document.close()}else c.open(d,a,g)};var fm=function(){return(0,z.Fj)("")};var gm=function(){return(0,z.Fj)("")};var hm=function(){return(0,z.Fj)('\x3cdiv\x3e\x3cdiv class\x3d"thchitems"\x3e\x3cdiv class\x3d"sortLabel"\x3e\x3cspan data-collecthighlights-dialog\x3d"collecthighlights_sort"\x3eSort highlights by\x3c/span\x3e\x3c/div\x3e\x3cselect id\x3d"sortSelect" class\x3d"thSelect"\x3e\x3coption value\x3d"0" data-collecthighlights-dialog\x3d"collecthighlights_color"\x3ecolor\x3c/option\x3e\x3coption value\x3d"1" data-collecthighlights-dialog\x3d"collecthighlights_position"\x3eposition\x3c/option\x3e\x3c/select\x3e\x3cdiv class\x3d"thchcolors"\x3e\x3cspan data-collecthighlights-dialog\x3d"collecthighlights_to_collect"\x3eColors to collect\x3c/span\x3e\x3cdiv\x3e\x3cdiv id\x3d"thYellowChk" class\x3d"thCollectChks thYellowChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thYellowRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3cdiv id\x3d"thBlueChk" class\x3d"thCollectChks thBlueChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thBlueRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3cdiv id\x3d"thGreenChk" class\x3d"thCollectChks thGreenChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thGreenRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3cdiv id\x3d"thPinkChk" class\x3d"thCollectChks thPinkChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thPinkRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"gdwr-modal-dialog-buttons gdwr-collect-dialog-buttons"/\x3e\x3c/div\x3e')};
var im=function(){return(0,z.Fj)('\x3cdiv\x3e\x3cdiv class\x3d"gdwr-voicenote-dialog-content"\x3e\x3cscript id\x3d\'thRecordWorker\' type\x3d\'javascript/worker\'\x3e\x3c/script\x3e\x3cdiv class\x3d"round-mic-record"\x3e\x3cdiv id\x3d"thRecorderPH" class\x3d"thRecorderPH"\x3e\x3c/div\x3e\x3ccanvas class\x3d"thMicLevelCanvas" width\x3d"134px" height\x3d"134px"\x3e\x3c/canvas\x3e\x3cdiv class\x3d"round-mic-record-circle"\x3e\x3cdiv class\x3d"round-mic-record-circle-img"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"voicenote-message-spacer"\x3e\x3c/div\x3e\x3cdiv class\x3d"round-playback"\x3e\x3cdiv class\x3d"round-playback-circle"\x3e\x3ccanvas class\x3d"round-playback-canvas"\x3e\x3c/canvas\x3e\x3cdiv class\x3d"round-micplayback-circle-img play"\x3e\x3c/div\x3e\x3cdiv class\x3d"round-countdownclock"\x3e1:00\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cspan class\x3d"gdwr-dialog-title-close gdwr-voicenote-dialog-close" role\x3d"button" tabindex\x3d"0" aria-label\x3d"Close"\x3e\x3c/span\x3e\x3cdiv class\x3d"gdwr-voicenote-add-button" role\x3d"button" tabindex\x3d"0" aria-label\x3d"Add voice note"\x3e\x3cdiv class\x3d"gdwr-dialog-title-add gdwr-voicenote-add"\x3e\x3c/div\x3e\x3cdiv class\x3d"gdwr-voicenote-add-image" data-voicenote-dialog\x3d\'voicenote_insert\'\x3eInsert\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"thVNload-bar"\x3e\x3cdiv class\x3d"thVNbar"\x3e\x3c/div\x3e\x3cdiv class\x3d"thVNbar"\x3e\x3c/div\x3e\x3cdiv class\x3d"thVNbar"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv\x3e')};
var jm=function(){return(0,z.Fj)('\x3cdiv\x3e\x3cdiv class\x3d"ch-notification"\x3e\x3cdiv class\x3d"ch-notification-content"\x3e\x3cdiv class\x3d"ch-notification-heading" data-collect-highlights-notification\x3d\'collect_highlights_notification\'\x3eCollecting highlights\x3c/div\x3e\x3cdiv class\x3d"ch-notification-msg" data-collect-highlights-notification\x3d\'collect_highlights_notification_text\'\x3eA new document containing your highlights is being created.\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};
var km=function(){return(0,z.Fj)('\x3cdiv\x3e\x3cdiv class\x3d"vl-notification"\x3e\x3cdiv class\x3d"vl-notification-content"\x3e\x3cdiv class\x3d"vl-notification-heading" data-vocab-notification\x3d\'vocab_notification\'\x3eVocabulary List\x3c/div\x3e\x3cdiv class\x3d"vl-notification-msg" data-vocab-notification\x3d\'vocab_notification_text\'\x3eA new document containing your vocabulary list is being created.\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var lm=function(){return(0,z.Fj)('\x3cdiv\x3e\x3cdiv class\x3d"mn-notification"\x3e\x3cdiv class\x3d"mn-notification-content"\x3e\x3cdiv class\x3d"mn-notification-heading"\x3eNotification\x3c/div\x3e\x3cdiv class\x3d"mn-notification-msg"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};
var mm=function(){return(0,z.Fj)('\x3cthRWGDns:thUIPred id\x3d"kix-thprediction-popup" class\x3d"kix-thprediction-popup" style\x3d "display: block; left: 0px; top: 0px;"\x3e\x3cdiv class\x3d"kix-thPredictions"\x3e\x3c/div\x3e\x3cdiv class\x3d"thPredictionArrow thPredictionArrowup" style\x3d"left: 20px; "\x3e\x3cdiv class\x3d"thPredictionArrowimplBefore"\x3e\x3c/div\x3e\x3cdiv class\x3d"thPredictionArrowimplAfter"\x3e\x3c/div\x3e\x3c/thRWGDns:thUIPred\x3e')};z.Dk=function(){return(0,z.Fj)('\x3cthRWGDns:thVoiceNoteOverlay class\x3d"kix-thvoicenote-overlay" style\x3d "visibility: hidden; left: 0px; top: 0px; width:0px; height:0px; background: ; position: absolute;"\x3e\x3cdiv class\x3d"thVNPlayback" id\x3d"thVNPlayback" data-percent\x3d"0" data-line\x3d"4"\x3e\x3caudio source class\x3d"thVNAudio" type\x3d"audio/wav"\x3e\x3c/audio\x3e\x3cdiv class\x3d"thVNButton"\x3e\x3cdiv class\x3d"thVNIcon thVNPlay"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/thRWGDns:thVoiceNoteOverlay\x3e')};
z.ej=function(a){z.Hg.call(this,a);z.U.a();this.Ob=this.cc=null;this.mj=this.lj=this.ra=!1;this.U={};this.hn=new nm;this.Gn=new om;this.Fn=this.lh=null;this.cn=!1;this.hj=null;this.sn="";this.cd=null;z.T.a().j("onBarVisibilityChanged",this.Gr,this);z.T.a().j("onWordChanged",this.$r,this);z.T.a().j("onPredictionChanged",this.kr,this);z.T.a().j("onPredictionManualClose",this.mr,this);z.T.a().j("onMessagePopup",this.Zq,this);z.T.a().j("onUILanguageChanged",this.wh,this);z.T.a().j("onShowDocsOAuthDialog",
this.tr,this);z.T.a().j("onCollectStudySkills",this.cs,this);z.T.a().j("onVoiceNotes",this.xs,this);z.T.a().j("onVocabTool",this.ws,this);z.T.a().j("onPlay",this.os,this);z.T.a().j("onStop",this.us,this);z.T.a().j("onPause",this.ks,this);z.T.a().j("onBlueHighlighter",this.as,this);z.T.a().j("onPinkHighlighter",this.ns,this);z.T.a().j("onYellowHighlighter",this.ys,this);z.T.a().j("onGreenHighlighter",this.gs,this);z.T.a().j("onClear",this.bs,this);z.T.a().j("onHelp",this.hs,this);z.T.a().j("onLogo",
this.js,this);z.T.a().j("onSpeechInput",this.ts,this);z.T.a().j("onPictureDictionary",this.ls,this);z.T.a().j("onDictionary",this.ds,this);z.T.a().j("onTranslator",this.vs,this);z.T.a().j("onScreenshotReader",this.rs,this);z.T.a().j("onScreenMasking",this.qs,this);z.T.a().j("onFactFinder",this.fs,this);z.T.a().j("onSimplify",this.ss,this);z.T.a().j("onPracticeReadingAloud",this.ps,this);this.pq=null};var pm=function(){this.Md=!1;this.Dn=z.K("thTooltip");z.K("thTooltipContentId");z.K("thTooltipArrow")};
var qm=function(){this.M=null;this.Md=!1};var rm=function(){};var sm=function(a,b){if(a)for(var c=b?a.firstChild:a.lastChild,d;c&&c.parentNode==a;){d=b?c.nextSibling:c.previousSibling;if(3==c.nodeType){var e=c.nodeValue;if(""==(0,z.Tb)(e))a.removeChild(c);else{c.nodeValue=b?e.replace(/^[\s\xa0]+/,""):e.replace(/[\s\xa0]+$/,"");break}}else break;c=d}};var tm=function(){};
var um=function(a,b,c,d,e){z.sh.call(this,a,c||tm.a(),d);this.rb(64,!0);this.pj=new z.zh(null,5);b&&this.Dh(b);this.tq=null;this.xa=new bm(500);!z.cj&&!z.dj||z.C("533.17.9")||(this.Oi=!0);this.Yo=!0;this.uq=e||z.Yh.a()};var vm=function(a,b,c){var d=a.Ia();c=c?d.n:d.eb;c.call(d,b,"action",a.Hk);c.call(d,b,"close",a.Dk);c.call(d,b,"highlight",a.Gk);c.call(d,b,"unhighlight",a.Jk)};var wm=function(a,b){var c=a.Ia();(b?c.n:c.eb).call(c,a.f(),"keydown",a.Hp)};
var xm=function(a,b){var c=a.f(),d=z.Eg(b,"activedescendant"),d=z.ge(b).getElementById(d)||b;if(!d.id){var e=z.Fg.a();d.id=z.Gg(e)}e="";d&&(e=d.id);z.R(c,"activedescendant",e);z.R(c,"owns",d.id)};var ym=function(a){z.Jc.call(this);this.Cd=[];zm(this,a)};var zm=function(a,b){b&&((0,z.Rc)(b,function(a){Am(this,a,!1)},a),z.bb(a.Cd,b))};var Am=function(a,b,c){b&&("function"==typeof a.ho?a.ho(b,c):"function"==typeof b.Pl&&b.Pl(c))};
var Bm=function(a,b,c,d,e){um.call(this,a,b,c,d,e||new z.Yh("listbox"));this.jk=this.Vc();this.Ok=null;this.Gh("listbox")};var Cm=function(a,b){a.ca=new ym;b&&z.Tg(b,function(a){Dm(a);this.ca.Gb(a)},a);Em(a)};var Em=function(a){a.ca&&a.Ia().n(a.ca,"select",a.Pp)};var Fm=function(a){var b=a.Re();a.qb(b?b.Tc():a.jk);var c=a.K.oa(a.f());c&&a.B().Zp(c)&&(null==a.Ok&&(a.Ok=z.Eg(c,"label")),b=(b=b?b.f():null)?z.Eg(b,"label"):a.Ok,z.R(c,"label",b),Gm(a))};
var Gm=function(a){var b=a.K;if(b&&(b=b.oa(a.f()))){var c=a.k;b.id||(b.id=z.Gg(z.Fg.a()));z.Cg(b,"option");z.R(c,"activedescendant",b.id);a.ca&&(c=a.ca.yk(),c=cm(c,function(a){return a instanceof z.Vh}),z.R(b,"setsize",c),z.R(b,"posinset",1+a.ca.yi()))}};var Dm=function(a){a.Gh(a instanceof z.Vh?"option":"separator")};var nm=function(){qm.call(this);this.Kd=null;this.$k=0;this.oj=!1;this.el=[];this.tn=this.Zg=this.Yg=this.Xg=this.ah=this.mq=null;z.T.a().j("onUILanguageChanged",this.wh,this)};
var om=function(){qm.call(this);z.T.a().j("onUILanguageChanged",this.wh,this);this.ue=this.$e=null;this.ve=!1;this.T=this.dj=null;this.oc=60;this.kj=this.Ec=0;this.Zi=!1;this.Yi=0;this.W=null;this.In=this.Xk=!1;this.Vg=this.se=0;this.gh=!1;this.Ab=null};
var Hm=function(a){try{var b=z.K("round-mic-record-circle");if(null!=b){var c=z.K("round-mic-record-circle-img");if(null!=c){(0,window.clearTimeout)(a.kj);a.oc=60;var d=z.K("round-countdownclock");if(null!==d){var e=Math.floor(a.oc/60),g=a.oc-60*e,h=e+":"+g;10>g&&(h=e+":0"+g);z.Ce(d,h)}a.ue.stop();a.ue.exportMonoWAV(a.gq);a.T.clearRect(-300,-300,800,800);a.Wa(a.T,"#efefef",4,1,a.Ec);a.ve=!1;a.Ab.close();a.Ab=null;z.S.a().sa(b,"recording");z.S.a().sa(c,"recording");Im();var l=z.K("voicenote-message-spacer");
z.Ce(l,"");var m=z.K("thRecorderPH");z.O(m,"display","none")}}}catch(n){z.S.a().b(n)}};
var Vm=function(a){try{var b=z.K("round-mic-record-circle");if(null!=b){var c=z.K("round-mic-record-circle-img");if(null!=c){var d=z.K("round-micplayback-circle-img");Wm(a);a.Wa(a.T,"#efefef",4,1,a.Ec);null==a.Ab&&(a.Ab=new window.AudioContext,window.navigator.Nm({audio:!0},a.lq,function(){}));a.Xk||(z.S.a().da(z.K("gdwr-voicenote-add-button"),"enabled"),a.Xk=!0);z.S.a().da(b,"recording");z.S.a().da(c,"recording");z.S.a().P(d,"stop")&&z.S.a().sa(d,"stop");z.S.a().P(d,"play")||z.S.a().da(d,"play");
a.kj=(0,window.setTimeout)(a.fn,0);Xm();var e=z.K("voicenote-message-spacer");z.Ce(e,z.U.a().ha("voicenote_recording"));var g=z.K("thRecorderPH");z.O(g,"display","block")}}}catch(h){z.S.a().b(h)}};var Ym=function(a){try{a.Zi=!0,a.se=0,a.Vg=0,a.gh=!1,a.Ab=null,a.W.play(),a.Yi=(0,window.setTimeout)(a.en,0)}catch(b){z.S.a().b(b)}};var Wm=function(a){try{a.Zi=!1,a.W.pause(),a.W.currentTime=0,a.se=0,a.Vg=0,a.gh=!1,a.Ab=null,a.T.clearRect(-300,-300,800,800),a.Wa(a.T,"#efefef",4,1,a.Ec)}catch(b){z.S.a().b(b)}};
var Im=function(){try{var a=z.K("round-micplayback-circle-img"),b=z.K("round-countdownclock");z.O(b,"display","none");z.O(a,"display","block")}catch(c){z.S.a().b(c)}};var Xm=function(){try{var a=z.K("round-micplayback-circle-img"),b=z.K("round-countdownclock");z.O(a,"display","none");z.O(b,"display","block")}catch(c){z.S.a().b(c)}};z.Zh.prototype.yk=z.ca(17,function(){var a=[];z.Tg(this,function(b){a.push(b)});return a});z.Zh.prototype.Hg=z.ca(16,function(){return z.Pg(this)});
z.Zh.prototype.Me=z.ca(15,function(a){return z.Qg(this,a)});z.Zh.prototype.Zd=z.ca(14,function(a,b){this.Df(a,b,!0)});z.Yh.prototype.sd=z.ca(13,function(a,b){return z.Be(a.f(),b)});z.Zh.prototype.sd=z.ca(12,function(a){if(this.K.sd(this,a))return!0;for(var b=0,c=z.Pg(this);b<c;b++){var d=z.Qg(this,b);if("function"==typeof d.sd&&d.sd(a))return!0}return!1});z.xh.prototype.Jm=z.ca(11,function(){return this.Ti});z.kh.prototype.Gh=z.ca(10,function(a){this.xh=a});
z.ri.prototype.Gh=z.ca(9,function(a){this.xh=a});z.Sf.prototype.xj=z.ca(6,function(){try{if(null===this.A)throw Error("The WebReaderAPI has not been created");this.A.xj()}catch(a){z.S.a().b(a)}});z.Sf.prototype.Ci=z.ca(5,function(){try{if(null===this.A)throw Error("The WebReaderAPI has not been created");this.A.Ci()}catch(a){z.S.a().b(a)}});z.Sf.prototype.Yh=z.ca(4,function(){try{if(null===this.A)throw Error("The WebReaderAPI has not been created");this.A.Yh()}catch(a){z.S.a().b(a)}});
z.Sf.prototype.Rc=z.ca(3,function(a){try{if(null===this.A)throw Error("The WebReaderAPI has not been created");this.A.Rc(a)}catch(b){window.console.error(b.stack)}});z.B(bm,z.Jc);z.f=bm.prototype;z.f.enabled=!1;z.f.xa=null;z.f.setInterval=function(a){this.Rg=a;this.xa&&this.enabled?(this.stop(),this.start()):this.xa&&this.stop()};
z.f.dt=function(){if(this.enabled){var a=(0,z.Ni)()-this.Tk;0<a&&a<.8*this.Rg?this.xa=this.kg.setTimeout(this.bk,this.Rg-a):(this.xa&&(this.kg.clearTimeout(this.xa),this.xa=null),this.dispatchEvent("tick"),this.enabled&&(this.xa=this.kg.setTimeout(this.bk,this.Rg),this.Tk=(0,z.Ni)()))}};z.f.start=function(){this.enabled=!0;this.xa||(this.xa=this.kg.setTimeout(this.bk,this.Rg),this.Tk=(0,z.Ni)())};z.f.stop=function(){this.enabled=!1;this.xa&&(this.kg.clearTimeout(this.xa),this.xa=null)};
z.f.w=function(){bm.g.w.call(this);this.stop();delete this.kg};z.f=dm.prototype;
z.f.Q=function(a,b){try{if(this.ih=this.Vf=!1,this.Md!==a){if(!this.zn){var c=z.Ki(mm);z.K(b).appendChild(c);this.bc=z.K("kix-thprediction-popup");this.jj=z.K("kix-thPredictions");var d=z.S.a().bind(this,this.cr);z.E(this.bc,"mouseover",d);var e=z.S.a().bind(this,this.ar);z.E(this.bc,"mousemove",e);var g=z.S.a().bind(this,this.$q);z.E(this.bc,"mousedown",g);this.zn=!0}a?(z.O(this.bc,"display","block"),z.S.a().Jj(!0)):(z.O(this.bc,"display","none"),z.S.a().Jj(!1));this.gj=!1;this.Md=a}}catch(h){z.S.a().b(h)}};
z.f.cr=function(a){this.Vf=!1;this.gj?(null!==this.ij&&(0,window.clearTimeout)(this.ij),this.ih=!0,this.Wf=a,this.ij=(0,window.setTimeout)(this.Hs,300),this.gj=!1):(0,window.clearTimeout)(this.ij)};
z.f.$q=function(a){a.stopPropagation();a.preventDefault();if(!this.Vf){this.Vf=!0;this.ih=!1;var b="";if("thprediction-word"==this.Wf.target.className)b=a.target.innerText.substr(3);else if("thprediction"==this.Wf.target.className)b=a.target.firstChild.innerText.substr(3);else return;0!=b.length&&(a=[],a.push(b),z.T.a().u("onPredictionChange",a))}};
z.f.dr=function(){if(("thprediction-word"===this.Wf.target.className||"thprediction"===this.Wf.target.className)&&this.ih){var a=[];a.push(this.Wf.target.innerText.substr(3));z.T.a().u("onWordChanged",a);a[0]+="-,";z.S.a().Gd.no(a)}};z.f.ar=function(){this.gj=!0};z.f.Fq=function(){try{this.Q(!1)}catch(a){z.S.a().b(a)}};
z.f.Eq=function(a){try{for(var b=z.V.a().O().prediction.results,c="",d=0;d<b;d++)c+='\x3cdiv class\x3d"thprediction"\x3e\x3cdiv class\x3d"thprediction-word"\x3e\x3c/div\x3e\x3c/div\x3e';if(null!=this.jj&&void 0!=this.jj){this.jj.innerHTML=c;var e=z.K(a.position),g=new z.H(e.offsetLeft,e.offsetTop),h=z.kg(e),l=g.y+h.height+e.scrollHeight+6+"px";z.O(this.bc,"left",g.x-h.width-e.scrollWidth-18+"px");z.O(this.bc,"top",l)}}catch(m){z.S.a().b(m)}};z.f.hr=function(){};
z.f.lr=function(a){try{if(this.Md&&!this.Vf){this.Vf=!0;this.ih=!1;var b=0;a[0].ctrlKey&&(b=48==a[0].keyCode?9:a[0].keyCode-49);b>=this.wn.length||(a=[],a.push(this.wn[b]),z.T.a().u("onPredictionChange",a))}}catch(c){z.S.a().b(c)}};fm.Vd="textHelp.fixedtoolbar.templates.Toolbar";gm.Vd="textHelp.fixedtoolbar.templates.Tooltip";hm.Vd="textHelp.fixedtoolbar.templates.CollectHighlights";im.Vd="textHelp.fixedtoolbar.templates.VoiceNote";jm.Vd="textHelp.fixedtoolbar.templates.CollectHighlightsNotification";km.Vd="textHelp.fixedtoolbar.templates.VocabNotification";lm.Vd="textHelp.fixedtoolbar.templates.MessageNotification";mm.Vd="textHelp.fixedtoolbar.templates.Prediction";z.Dk.Vd="textHelp.fixedtoolbar.templates.VoiceNoteCommentOverlay";z.B(z.ej,z.Hg);z.f=z.ej.prototype;z.f.p=function(){try{z.ej.g.p.call(this);var a=z.S.a().Qe(),b=z.J(z.S.a().Jf());if(null!=b){var c=window.document.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=a+"assets/thFixedToolbar.css";this.B().appendChild(b,c);var d=z.Ki(fm);this.B().Qk(d,window.document.body.firstChild);d=z.Ki(gm);this.B().appendChild(window.document.body,d);new pm;new dm}}catch(e){z.S.a().b(e)}};z.f.Sa=function(a){try{this.Ob=a,this.hn.Sa(""),this.Gn.Sa("")}catch(b){z.S.a().b(b)}};
z.f.Gr=function(){};z.f.$r=function(a){try{if(!this.mh){var b=window.document.getElementById("th-RW4GC-picture-dictionary"),c=window.document.getElementById("th-RW4GC-translator"),d=window.document.getElementById("th-RW4GC-prediction");if(null!=window.document.getElementById("th-RW4GC-dictionary")||null!=b||null!=c||null!=d)b="",b=0==a.length?this.Ob.xb():a[0],1>b.length||b==this.sn||(this.sn=b,window.texthelp.RW4GC.thToolbarStoreInstance.onWordChanged(b))}}catch(e){z.S.a().b(e)}};
z.f.tr=function(){try{window.open("https://script.google.com/macros/s/AKfycbyPhfA6NYF8msRlb7BF4aR8Ax_JWSDM6eAj3tjR2CpkXUMfjhk/exec","_ntthad")}catch(a){z.S.a().b(a)}};z.f.rl=function(){};
z.f.kr=function(a){try{if(z.S.a().Oa("Prediction",!0)){var b=z.S.a().Ra(),c=[];c.push("prediction lookup");c.push(b.Email);c.push(b.Email.split("@")[1]);window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",parameters:c},"*");var d=this.Ob.Ba();if(0>d.x||0>d.y)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else null==window.document.getElementById("texthelp-prediction-frame")&&(window.texthelp.RW4GC.riot.prediction=window.texthelp.RW4GC.riot.mount("texthelp-prediction")[0]),
window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionUpdate(d,a.parentId,a.words)}}catch(e){z.S.a().b(e)}};z.f.mr=function(a){try{var b=window.document.getElementsByClassName("th-prediction-image")[0];null!=b&&(this.ra=!1,a=[],a.push(this.ra),z.T.a().u("onWRPredictionStateChanged",a),z.S.a().sa(b,"enabled"))}catch(c){z.S.a().b(c)}};
z.f.Zq=function(a){try{var b=a.m.message,c=a.m.link;if(0!=b.length){var d=z.Ki(lm);a="";a=0<c.length?'\x3ca href\x3d"'+c+'" target\x3d"_blank"\x3e'+b+"\x3c/a\x3e":"\x3cdiv\x3e"+b+"\x3c/div\x3e";var e=z.te(window.document,a);z.K("mn-notification-msg",d).appendChild(e);window.notification({msg:d.innerHTML,delay:1E4,type:"success",animIn:"fadeInRight",animOut:"fadeOutDown"})}}catch(g){z.S.a().b(g)}};
z.f.wh=function(){try{for(var a=window.document.querySelectorAll("[data-fixedtoolbar-tooltip]"),b=0;b<a.length;b++){var c=a[b].getAttribute("data-fixedtoolbar-tooltip");a[b].setAttribute("tooltip",z.U.a().ha(c))}}catch(d){z.S.a().b(d)}};z.f.os=function(){try{z.S.a().Oa("Play",!0)&&(window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*"),z.V.a().Sj(),z.T.a().u("onWRPlay",[]))}catch(a){z.S.a().b(a)}};
z.f.us=function(){try{z.S.a().Oa("Stop",!0)&&(window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*"),z.T.a().u("onWRStop",[]))}catch(a){z.S.a().b(a)}};z.f.ks=function(){try{z.S.a().Oa("Pause",!0)&&(window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*"),z.T.a().u("onWRPause",[]))}catch(a){z.S.a().b(a)}};
z.f.fs=function(){try{if(z.S.a().Oa("Web Search",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ra();z.S.a().Wb()["Web Search"]?z.T.a().u("onWRFactFinder",[]):null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(b){z.S.a().b(b)}};
z.f.ss=function(){try{if(z.S.a().Oa("Simplify Page",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ra();z.S.a().Wb()["Simplify Page"]?z.T.a().u("onWRSimplify",[]):null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(b){z.S.a().b(b)}};z.f.ps=function(){try{z.T.a().u("onWRPracticeReadingAloud",[])}catch(a){z.S.a().b(a)}};
z.f.ds=function(){try{window.texthelp.RW4GC.currentDictionary={word:this.Ob.xb()};window.texthelp.RW4GC.riot.dictionary=window.texthelp.RW4GC.riot.mount("texthelp-dictionary",window.texthelp.RW4GC.currentDictionary)[0];var a=z.S.a().qa();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"dictionary",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.vs=function(){try{window.texthelp.RW4GC.currentTranslator={word:this.Ob.xb()};window.texthelp.RW4GC.riot.translator=window.texthelp.RW4GC.riot.mount("texthelp-translator",window.texthelp.RW4GC.currentTranslator)[0];var a=z.S.a().qa();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"translate",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.xs=function(){try{var a=z.S.a().Ra();if(z.S.a().Wb()["Voice Note"]){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");this.Gn.jg();var b=z.S.a().qa();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"voice note",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}catch(c){z.S.a().b(c)}};
z.f.ls=function(){try{window.texthelp.RW4GC.currentPictureDictionary={word:this.Ob.xb()};window.texthelp.RW4GC.riot.pictureDictionary=window.texthelp.RW4GC.riot.mount("texthelp-picture-dictionary",window.texthelp.RW4GC.currentPictureDictionary)[0];var a=z.S.a().qa();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"picture dictionary",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.ys=function(){try{if(z.S.a().Oa("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ra();if(z.S.a().Wb().Highlights){this.Ob.Wj();var b=z.S.a().qa();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"yellow study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.as=function(){try{if(z.S.a().Oa("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ra();if(z.S.a().Wb().Highlights){this.Ob.Yh();var b=z.S.a().qa();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"blue study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.gs=function(){try{if(z.S.a().Oa("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ra();if(z.S.a().Wb().Highlights){this.Ob.Ci();var b=z.S.a().qa();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"green study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.ns=function(){try{if(z.S.a().Oa("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ra();if(z.S.a().Wb().Highlights){this.Ob.xj();var b=z.S.a().qa();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"pink study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.bs=function(){try{if(z.S.a().Oa("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ra();if(z.S.a().Wb().Highlights){this.Ob.vc();var b=z.S.a().qa();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"clear study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.js=function(){try{window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");em("https://www.texthelp.com/products/read-write/read-write-for-google/");var a=z.S.a().qa();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"logo",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};z.f.Xn=function(){try{z.T.a().zf(this.pq),this.lh.jg(this.Ob.Kb(!1))}catch(a){z.S.a().b(a)}};
z.f.hs=function(){try{window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");em("https://support.texthelp.com/index.php?sid\x3d296\x26lang\x3den\x26action\x3dshow\x26cat\x3d5");var a=z.S.a().qa();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"help",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.rs=function(){try{if(z.S.a().Oa("Screenshot Reader",!0)){var a=z.S.a().qa();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"screenshot reader",label:a.split("@")[1]}},"*");var b=z.V.a().O();window.thPostMessage({method:"thCheckExtension",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo",Lang:b.language.services,defaultsettings:b.speechoptions}},"*")}}catch(c){z.S.a().b(c)}};
z.f.cs=function(){try{if(z.S.a().Oa("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");this.hn.jg();var a=z.S.a().qa();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"collect highlights",label:a.split("@")[1]}},"*")}}catch(b){z.S.a().b(b)}};
z.f.ws=function(){try{if(z.S.a().Oa("Vocabulary List",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().bind(this,this.Hr),b=[];b.push("#FFFF00");b.push("#00FFFF");b.push("#ADFF2F");b.push("#FF00FF");z.S.a().Gd.Gf(a,b,"untitled Vocabulary List");var c=z.S.a().qa();if(null==c)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:c,action:"vocab words",
label:c.split("@")[1]}},"*");for(var d=z.Ki(km),e=d.querySelectorAll("[data-vocab-notification]"),a=0;a<e.length;a++){var g=e[a].getAttribute("data-vocab-notification");e[a].innerText=z.U.a().ha(g)}this.Fn=window.notification({msg:d.innerHTML,delay:5E3,type:"success",animIn:"fadeInRight",animOut:"fadeOutDown"})}}catch(h){z.S.a().b(h)}};
z.f.ts=function(){try{if(z.S.a().Oa("Talk\x26Type",!0)){window.postMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");this.mj=!this.mj;var a=z.S.a().Gd.Vb();void 0===a.custom||void 0===a.custom.screenshotreadertoogle||a.custom.screenshotreadertoogle||(this.mj=!0);if(this.mj){this.Ob.jd();b=z.S.a().qa();if(null==b)return null;c=b.split("@")[1];window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,
action:"speech input",label:c}},"*")}else this.Ob.kd()}else{var b=z.S.a().qa();if(null==b)return null;var c=b.split("@")[1];window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"speech input",label:c}},"*")}}catch(d){z.S.a().b(d)}};z.f.qs=function(){try{if(z.S.a().Oa("Screen Masking",!0)){this.lj=!this.lj;var a=window.document.getElementsByClassName("th-screenmasking-image")[0];this.lj?z.S.a().da(a,"enabled"):z.S.a().sa(a,"enabled");window.textHelp.thScreenMasking.screenmasking.toggle(this.lj)}}catch(b){z.S.a().b(b)}};
z.f.Hr=function(){try{this.Fn.remove()}catch(a){z.S.a().b(a)}};z.f.Oa=function(a,b){try{var c=z.S.a().Ra();if(void 0!==c.lt)return!0;var d=z.S.a().Wb();z.V.a().Sj();return d[a]?!0:(null!==c.Redirect&&b&&window.open(c.Redirect,"_exthtb").focus(),!1)}catch(e){z.S.a().b(e)}};pm.prototype.Q=function(a){try{this.Md!==a&&(a?z.S.a().sa(this.Dn,"thTooltipHide"):z.S.a().da(this.Dn,"thTooltipHide"),this.Md=a)}catch(b){z.S.a().b(b)}};qm.prototype.Sa=function(a){try{this.nq=a;var b=this.M=new z.ri("gdwr-modal-dialog",!0);1!=b.qj&&z.yi(b,!0);var c=this.M;c.lk=!1;z.zi(c,!1);z.S.a().da(z.wi(this.M),"gdwr-"+this.nq+"-dialog")}catch(d){z.S.a().b(d)}};qm.prototype.show=function(){this.M.Q(!0);this.Md=!0};qm.prototype.S=function(){try{return this.Md}catch(a){z.S.a().b(a)}};z.B(rm,z.hh);z.ga(rm);z.f=rm.prototype;z.f.p=function(a){var b={"class":"goog-inline-block "+this.Uc(a).join(" ")},b=a.B().p("div",b,this.ki(a.Vc(),a.B()));this.Kj(b,a.Mg());z.ch(this,a,b);return b};z.f.ee=function(){return"button"};z.f.oa=function(a){return a&&a.firstChild&&a.firstChild.firstChild};z.f.ki=function(a,b){return b.p("div","goog-inline-block "+(this.L()+"-outer-box"),b.p("div","goog-inline-block "+(this.L()+"-inner-box"),a))};z.f.Tb=function(a){return"DIV"==a.tagName};
z.f.ea=function(a,b){sm(b,!0);sm(b,!1);var c;a:{c=a.B().Im(b);var d=this.L()+"-outer-box";if(c&&z.Wg(c,d)&&(c=a.B().Im(c),d=this.L()+"-inner-box",c&&z.Wg(c,d))){c=!0;break a}c=!1}c||b.appendChild(this.ki(b.childNodes,a.B()));z.Yg(b,["goog-inline-block",this.L()]);return rm.g.ea.call(this,a,b)};z.f.L=function(){return"goog-custom-button"};z.B(tm,rm);z.ga(tm);z.f=tm.prototype;z.f.oa=function(a){return tm.g.oa.call(this,a&&a.firstChild)};z.f.ea=function(a,b){var c=z.ie(window.document,"*","goog-menu",b)[0];if(c){z.og(c,!1);z.ge(c).body.appendChild(c);var d=new z.Zh;d.ea(c);a.Dh(d)}return tm.g.ea.call(this,a,b)};z.f.ki=function(a,b){return tm.g.ki.call(this,[this.createCaption(a,b),b.p("div","goog-inline-block "+(this.L()+"-dropdown"),"\u00a0")],b)};
z.f.createCaption=function(a,b){return b.p("div","goog-inline-block "+(this.L()+"-caption"),a)};z.f.L=function(){return"goog-menu-button"};z.B(um,z.sh);z.f=um.prototype;z.f.Oi=!1;z.f.Ks=!1;z.f.Ps=!1;z.f.ka=function(){um.g.ka.call(this);wm(this,!0);this.i&&vm(this,this.i,!0);z.R(this.k,"haspopup",!!this.i)};z.f.Qa=function(){um.g.Qa.call(this);wm(this,!1);if(this.i){this.Da(!1);this.i.Qa();vm(this,this.i,!1);var a=this.i.f();a&&z.xe(a)}};z.f.w=function(){um.g.w.call(this);this.i&&(this.i.aa(),delete this.i);delete this.Ds;this.xa.aa()};
z.f.je=function(a){um.g.je.call(this,a);this.Xe()&&(this.Da(!this.Ac(),a),this.i&&(a=this.Ac(),this.i.fd=a))};z.f.ke=function(a){um.g.ke.call(this,a);this.i&&!this.Xe()&&(this.i.fd=!1)};z.f.Ae=function(){this.setActive(!1);return!0};z.f.Cp=function(a){this.i&&this.i.S()&&!this.sd(a.target)&&this.Da(!1)};z.f.sd=function(a){return a&&z.Be(this.f(),a)||this.i&&this.i.sd(a)||!1};
z.f.zc=function(a){if(32==a.keyCode){if(a.preventDefault(),"keyup"!=a.type)return!0}else if("key"!=a.type)return!1;if(this.i&&this.i.S()){var b=13==a.keyCode||32==a.keyCode,c=this.i.Yb(a);return 27==a.keyCode||b&&this.Yo?(this.Da(!1),!0):c}return 40==a.keyCode||38==a.keyCode||32==a.keyCode||13==a.keyCode?(this.Da(!0,a),!0):!1};z.f.Hk=function(){this.Da(!1)};z.f.Mp=function(){this.Xe()||this.Da(!1)};z.f.Te=function(a){this.Oi||this.Da(!1);um.g.Te.call(this,a)};
z.f.Oe=function(){this.i||this.Dh(new z.Zh(this.B(),this.uq));return this.i||null};z.f.Dh=function(a){var b=this.i;if(a!=b&&(b&&(this.Da(!1),this.Z&&vm(this,b,!1),delete this.i),this.Z&&z.R(this.k,"haspopup",!!a),a)){this.i=a;z.Lg(a,this);a.Q(!1);var c=this.Oi;(a.Uh=c)&&a.Ud(!0);this.Z&&vm(this,a,!0)}return b};z.f.Gb=function(a){this.Oe().He(a,!0)};z.f.Zd=function(a,b){this.Oe().Df(a,b,!0)};z.f.removeItem=function(a){(a=this.Oe().removeChild(a,!0))&&a.aa()};
z.f.Me=function(a){return this.i?z.Qg(this.i,a):null};z.f.Hg=function(){return this.i?z.Pg(this.i):0};z.f.Q=function(a,b){var c=um.g.Q.call(this,a,b);c&&!this.S()&&this.Da(!1);return c};z.f.Fb=function(a){um.g.Fb.call(this,a);this.isEnabled()||this.Da(!1)};
z.f.Da=function(a,b){um.g.Da.call(this,a);if(this.i&&!!(this.X&64)==a){if(a){if(!this.i.Z)if(this.Ks){var c;c=this.f();(c=void 0!=c.nextElementSibling?c.nextElementSibling:z.ze(c.nextSibling))?z.Ng(this.i,c.parentNode,c):this.i.ta(this.f().parentNode)}else this.i.ta();this.Fo=z.fg(this.f());this.em=z.mg(this.f());this.yj();c=!!b&&(13==b.keyCode||32==b.keyCode);this.i.Nc(b&&(40==b.keyCode||38==b.keyCode)||c&&this.Ps?0:-1)}else{this.setActive(!1);this.i.fd=!1;if(c=this.f())z.R(c,"activedescendant",
""),z.R(c,"owns","");null!=this.uj&&(this.uj=void 0,(c=this.i.f())&&z.jg(c,"",""))}this.i.Q(a,!1,b);if(!this.td){c=this.Ia();var d=a?c.n:c.eb;d.call(c,z.Pe(this.B()),"mousedown",this.Cp,!0);this.Oi&&d.call(c,this.i,"blur",this.Mp);d.call(c,this.xa,"tick",this.zr);a?this.xa.start():this.xa.stop()}}this.i&&this.i.f()&&this.i.k.removeAttribute("aria-hidden")};
z.f.yj=function(){if(this.i.Z){var a=this.pj;this.pj.element=this.Ds||this.f();var b=this.i.f();this.i.S()||(b.style.visibility="hidden",z.og(b,!0));!this.uj&&this.pj.Jm&&this.pj.Ti&32&&(this.uj=z.kg(b));a.gg(b,a.ji^1,this.tq,this.uj);this.i.S()||(z.og(b,!1),b.style.visibility="visible")}};
z.f.zr=function(){var a=z.mg(this.f()),b=z.fg(this.f()),c=this.em;(c=!(c==a||c&&a&&c.left==a.left&&c.width==a.width&&c.top==a.top&&c.height==a.height))||(c=this.Fo,c=!(c==b||c&&b&&c.top==b.top&&c.right==b.right&&c.bottom==b.bottom&&c.left==b.left));c&&(this.em=a,this.Fo=b,this.yj())};z.f.Gk=function(a){(a=a.target.f())&&xm(this,a)};z.f.Hp=function(a){z.dh(this,32)&&this.Fa()&&this.i&&this.i.S()&&a.stopPropagation()};
z.f.Jk=function(){if(!z.Ih(this.i)){var a=this.f();z.R(a,"activedescendant","");z.R(a,"owns","")}};z.f.Dk=function(a){if(this.Ac()&&a.target instanceof z.Vh){a=a.target;var b=a.f();a.S()&&a.X&2&&null!=b&&xm(this,b)}};z.ih("goog-menu-button",function(){return new um(null)});z.B(ym,z.Jc);z.f=ym.prototype;z.f.Td=null;z.f.ho=null;z.f.Hg=function(){return this.Cd.length};z.f.Me=function(a){return this.Cd[a]||null};z.f.Gb=function(a){this.Zd(a,this.Hg())};z.f.Zd=function(a,b){a&&(Am(this,a,!1),z.cb(this.Cd,b,0,a))};z.f.removeItem=function(a){a&&z.Ya(this.Cd,a)&&a==this.Td&&(this.Td=null,this.dispatchEvent("select"))};z.f.Re=function(){return this.Td};z.f.yk=function(){return z.$a(this.Cd)};z.f.uf=function(a){a!=this.Td&&(Am(this,this.Td,!1),this.Td=a,Am(this,a,!0));this.dispatchEvent("select")};
z.f.yi=function(){var a=this.Td;return a?(0,z.Wa)(this.Cd,a):-1};z.f.lo=function(a){this.uf(this.Me(a))};z.f.clear=function(){var a=this.Cd;if(!z.ia(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0;this.Td=null};z.f.w=function(){ym.g.w.call(this);delete this.Cd;this.Td=null};z.B(Bm,um);z.f=Bm.prototype;z.f.ca=null;z.f.ka=function(){Bm.g.ka.call(this);Fm(this);Em(this)};z.f.Ub=function(a){Bm.g.Ub.call(this,a);(a=this.Tc())?(this.jk=a,Fm(this)):this.Re()||this.lo(0)};z.f.w=function(){Bm.g.w.call(this);this.ca&&(this.ca.aa(),this.ca=null);this.jk=null};z.f.Hk=function(a){this.uf(a.target);Bm.g.Hk.call(this,a);a.stopPropagation();this.dispatchEvent("action")};z.f.Pp=function(){var a=this.Re();Bm.g.bb.call(this,a&&a.la());Fm(this)};
z.f.Dh=function(a){var b=Bm.g.Dh.call(this,a);a!=b&&(this.ca&&this.ca.clear(),a&&(this.ca?z.Tg(a,function(a){Dm(a);this.ca.Gb(a)},this):Cm(this,a)));return b};z.f.Gb=function(a){Dm(a);Bm.g.Gb.call(this,a);this.ca?this.ca.Gb(a):Cm(this,this.Oe());Gm(this)};z.f.Zd=function(a,b){Dm(a);Bm.g.Zd.call(this,a,b);this.ca?this.ca.Zd(a,b):Cm(this,this.Oe())};z.f.removeItem=function(a){Bm.g.removeItem.call(this,a);this.ca&&this.ca.removeItem(a)};
z.f.uf=function(a){if(this.ca){var b=this.Re();this.ca.uf(a);a!=b&&this.dispatchEvent("change")}};z.f.lo=function(a){this.ca&&this.uf(this.ca.Me(a))};z.f.bb=function(a){if(null!=a&&this.ca)for(var b=0,c;c=this.ca.Me(b);b++)if(c&&"function"==typeof c.la&&c.la()==a){this.uf(c);return}this.uf(null)};z.f.la=function(){var a=this.Re();return a?a.la():null};z.f.Re=function(){return this.ca?this.ca.Re():null};z.f.yi=function(){return this.ca?this.ca.yi():-1};
z.f.Da=function(a,b){Bm.g.Da.call(this,a,b);this.Ac()?this.Oe().Nc(this.yi()):Gm(this)};z.ih("goog-select",function(){return new Bm(null)});qm.prototype.S=function(){try{return this.M.S()}catch(a){z.S.a().b(a)}};z.B(nm,qm);z.f=nm.prototype;
z.f.Sa=function(){nm.g.Sa.call(this,"collecthighlights");this.qq=z.S.a().bind(this,this.Sq);z.Ci(this.M);var a=z.Ki(hm),b=this.M;b.Oj="Collect Highlights";b.cb&&z.Ce(b.cb,"Collect Highlights");this.M.qb(a.innerHTML);this.el[0]=this.Us;this.el[1]=this.Vs;this.Kd=z.K("thSelect");z.E(this.Kd,"mouseup",this.ur,!1,this);this.ah=new z.Fl;this.ah.ea(z.J("thYellowChk"));this.Xg=new z.Fl;this.Xg.ea(z.J("thBlueChk"));this.Yg=new z.Fl;this.Yg.ea(z.J("thGreenChk"));this.Zg=new z.Fl;this.Zg.ea(z.J("thPinkChk"));
this.Ed=new z.sh("Cancel");this.Ed.da("gdwr-dialog-button");this.Fd=new z.sh("OK");this.Fd.da("gdwr-dialog-button");this.Ed.ta(z.K("gdwr-collect-dialog-buttons"));this.Fd.ta(z.K("gdwr-collect-dialog-buttons"));z.E(this.Ed,"action",this.qh,!1,this);z.E(this.Fd,"action",this.uh,!1,this)};
z.f.jg=function(){try{this.oj=!0;this.show();var a=z.V.a().O();this.Kd[a.collecthighlights.sortAlgorithm].selected=!0;void 0==a.collecthighlights.yellow&&(a.collecthighlights.yellow=!0);void 0==a.collecthighlights.green&&(a.collecthighlights.green=!0);void 0==a.collecthighlights.blue&&(a.collecthighlights.blue=!0);void 0==a.collecthighlights.pink&&(a.collecthighlights.pink=!0);this.ah.qc(a.collecthighlights.yellow);this.Xg.qc(a.collecthighlights.blue);this.Yg.qc(a.collecthighlights.green);this.Zg.qc(a.collecthighlights.pink)}catch(b){z.S.a().b(b)}};
z.f.ur=function(){try{if(!this.oj&&this.$k!==this.Kd.selectedIndex){var a=z.V.a().O();a.collecthighlights.sortAlgorithm=this.Kd.selectedIndex;z.V.a().Ej(a);if(!this.oj){try{var b=this.mq,c=z.J("collecthighlightsFrame");this.$k=this.Kd.selectedIndex;for(var a="\x3cdiv\x3e",d=0;d<b.length;d++){var e=b[d];e.highlights.sort(this.el[this.$k]);for(var g=0;g<e.highlights.length;g++)var h=e.highlights[g],a=a+('\x3cspan style\x3d"background-color:'+h.bgcolor+";color:"+h.fgcolor+';"\x3e'+h.text+"\x3c/span\x3e\x3cbr\x3e\x3cbr\x3e");
a+="\x3cdiv\x3e"+e.title+"\x3c/div\x3e\x3cdiv\x3e"+e.author+"\x3cbr\x3e"+e.link+"\x3c/div\x3e\x3c/div\x3e"}c.contentWindow.postMessage("content:"+(a+"\x3c/div\x3e"),z.S.a().Qe());this.oj=!1}catch(l){z.S.a().b(l)}window.document.createRange().selectNodeContents(window.document.body)}}}catch(m){z.S.a().b(m)}};z.f.Us=function(a,b){try{return a.colorOrder>b.colorOrder?1:a.colorOrder<b.colorOrder?-1:0}catch(c){z.S.a().b(c)}};z.f.Vs=function(a,b){try{return a.start>b.start?1:a.start<b.start?-1:0}catch(c){z.S.a().b(c)}};
z.f.qh=function(){try{this.M.Q(!1)}catch(a){z.S.a().b(a)}};
z.f.uh=function(){try{this.M.Q(!1);var a=z.V.a().O();a.collecthighlights.sortAlgorithm=this.Kd.selectedIndex;a.collecthighlights.yellow=this.ah.Lb();a.collecthighlights.green=this.Yg.Lb();a.collecthighlights.blue=this.Xg.Lb();a.collecthighlights.pink=this.Zg.Lb();z.V.a().Ej(a);var a=1,b=this.Kd[this.Kd.selectedIndex].value;"0"===b?a=2:"1"===b&&(a=1);b=[];this.ah.Lb()&&b.push("#FFFF00");this.Xg.Lb()&&b.push("#00FFFF");this.Yg.Lb()&&b.push("#ADFF2F");this.Zg.Lb()&&b.push("#FF00FF");z.S.a().Gd.Rc(this.qq,
a,b,"Highlights Untitled");for(var c=z.Ki(jm),d=c.querySelectorAll("[data-collect-highlights-notification]"),a=0;a<d.length;a++){var e=d[a].getAttribute("data-collect-highlights-notification");d[a].innerText=z.U.a().ha(e)}this.tn=window.notification({msg:c.innerHTML,type:"success",animIn:"fadeInRight",delay:5E3,animOut:"fadeOutDown"})}catch(g){z.S.a().b(g)}};z.f.Sq=function(){try{this.tn.remove()}catch(a){z.S.a().b(a)}};
z.f.wh=function(){try{var a=this.M,b=z.U.a().ha("collect_highlights_dialog_heading");a.Oj=b;a.cb&&z.Ce(a.cb,b);for(var c=window.document.querySelectorAll("[data-collecthighlights-dialog]"),a=0;a<c.length;a++){var d=c[a].getAttribute("data-collecthighlights-dialog");c[a].innerText=z.U.a().ha(d)}var e=z.U.a().ha("dialog_OK");this.Fd.qb(e);var g=z.U.a().ha("dialog_Cancel");this.Ed.qb(g)}catch(h){z.S.a().b(h)}};z.B(om,qm);z.f=om.prototype;
z.f.Sa=function(){om.g.Sa.call(this,"voicenote");var a=window.document.getElementById("thSpeechStreamTBPlaceHolder"),b=a.getAttribute("data-root");if(!this.In){var c=window.document.createElement("script");c.src=b+"assets/recorder.js";c.async=!0;c.id="thRecordWorker";c.onload=c.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(c.onload=c.onreadystatechange=null,a.removeChild(c))};c.textContent='function init(e){sampleRate\x3de.sampleRate}function record(e){recBuffersL.push(e[0]),recBuffersR.push(e[1]),recLength+\x3de[0].length}function exportWAV(e){var t\x3dmergeBuffers(recBuffersL,recLength),r\x3dmergeBuffers(recBuffersR,recLength),n\x3dinterleave(t,r),a\x3dencodeWAV(n),f\x3dnew Blob([a],{type:e});this.postMessage(f)}function exportMonoWAV(e){var t\x3dmergeBuffers(recBuffersL,recLength),r\x3dencodeWAV(t,!0),n\x3dnew Blob([r],{type:e});this.postMessage(n)}function getBuffers(){var e\x3d[];e.push(mergeBuffers(recBuffersL,recLength)),e.push(mergeBuffers(recBuffersR,recLength)),this.postMessage(e)}function clear(){recLength\x3d0,recBuffersL\x3d[],recBuffersR\x3d[]}function mergeBuffers(e,t){for(var r\x3dnew Float32Array(t),n\x3d0,a\x3d0;a\x3ce.length;a++)r.set(e[a],n),n+\x3de[a].length;return r}function interleave(e,t){for(var r\x3de.length+t.length,n\x3dnew Float32Array(r),a\x3d0,f\x3d0;r\x3ea;)n[a++]\x3de[f],n[a++]\x3dt[f],f++;return n}function interleaveForceMono(e){for(var t\x3de.length,r\x3dnew Float32Array(t),n\x3d0,a\x3d0;t\x3en;)r[n++]\x3d.25*(e[a++]+e[a++]+e[a++]+e[a++]);return r}function floatTo16BitPCM(e,t,r){for(var n\x3d0;n\x3cr.length;n++,t+\x3d2){var a\x3dMath.max(-1,Math.min(1,r[n]));e.setInt16(t,0\x3ea?32768*a:32767*a,!0)}}function writeString(e,t,r){for(var n\x3d0;n\x3cr.length;n++)e.setUint8(t+n,r.charCodeAt(n))}function encodeWAV(e,t){var r\x3dnew ArrayBuffer(44+2*e.length),n\x3dnew DataView(r);return writeString(n,0,"RIFF"),n.setUint32(4,32+2*e.length,!0),writeString(n,8,"WAVE"),writeString(n,12,"fmt "),n.setUint32(16,16,!0),n.setUint16(20,1,!0),n.setUint16(22,t?1:2,!0),n.setUint32(24,sampleRate,!0),n.setUint32(28,2*sampleRate,!0),n.setUint16(32,2,!0),n.setUint16(34,16,!0),writeString(n,36,"data"),n.setUint32(40,2*e.length,!0),floatTo16BitPCM(n,44,e),n}var recLength\x3d0,recBuffersL\x3d[],recBuffersR\x3d[],sampleRate;this.onmessage\x3dfunction(e){switch(e.data.command){case"init":init(e.data.config);break;case"record":record(e.data.buffer);break;case"exportWAV":exportWAV(e.data.type);break;case"exportMonoWAV":exportMonoWAV(e.data.type);break;case"getBuffers":getBuffers();break;case"clear":clear()}};';a.appendChild(c);
this.In=!0}z.Ci(this.M);b=z.Ki(im);this.M.qb(b.innerHTML);b=z.K("gdwr-modal-dialog-title",this.M.f());z.O(b,"visibility","hidden");this.W=new window.Audio;z.E(z.K("gdwr-voicenote-add-button"),"click",this.uh,!1,this);z.E(z.K("gdwr-voicenote-dialog-close"),"click",this.qh,!1,this);this.lq=z.S.a().bind(this,this.Ys);this.hq=z.S.a().bind(this,this.qp);z.S.a();this.gq=z.S.a().bind(this,this.Aq);this.en=z.S.a().bind(this,this.vl);this.dn=z.S.a().bind(this,this.ul);z.S.a();this.kq=z.S.a().bind(this,this.or);
this.fn=z.S.a().bind(this,this.pr);this.jq=z.S.a().bind(this,this.ir);this.iq=z.S.a().bind(this,this.sl);z.E(z.K("round-mic-record"),"click",this.kq,!1,this);z.E(z.K("round-micplayback-circle-img"),"click",this.jq,!1,this);z.E(z.K("round-playback-canvas"),"mouseup",this.iq,!0,this)};
z.f.jg=function(){try{this.M.Q(!0);this.Kl();var a=z.K("thVNload-bar",this.M.f());z.O(a,"display","none");null==this.Ab&&(window.AudioContext=window.AudioContext||window.webkitAudioContext,window.navigator.Nm=window.navigator.Nm||window.navigator.webkitGetUserMedia,window.URL=window.URL||window.webkitURL,this.W.onended=this.cm);if(null==this.T){var b=z.K("round-playback-canvas");b.width=b.height;this.T=b.getContext("2d");this.T.translate(b.height/2,b.height/2);this.T.rotate(-.5*Math.PI);this.T.translate(.5,
.5);this.Ec=b.height-20;this.Wa(this.T,"#efefef",4,1,this.Ec);b=z.K("thMicLevelCanvas");this.Jd=b.getContext("2d");this.W.onended=this.dn}null==this.W.onended&&(this.W.onended=this.dn)}catch(c){z.S.a().b(c)}};z.f.qh=function(){try{this.ve&&Hm(this);if(this.Zi){var a=z.K("round-micplayback-circle-img");z.S.a().sa(a,"stop");z.S.a().da(a,"play");Wm(this)}this.M.Q(!1);this.ue=this.Ab=null}catch(b){z.S.a().b(b)}};
z.f.uh=function(){try{if(this.ve)try{var a=z.K("round-mic-record-circle");if(null!=a){var b=z.K("round-mic-record-circle-img");if(null!=b){(0,window.clearTimeout)(this.kj);this.oc=60;var c=z.K("round-countdownclock");if(null!==c){var d=Math.floor(this.oc/60),e=this.oc-60*d,g=d+":"+e;10>e&&(g=d+":0"+e);z.Ce(c,g)}this.ue.stop();this.T.clearRect(-300,-300,800,800);this.Wa(this.T,"#efefef",4,1,this.Ec);this.ve=!1;this.Ab.close();this.Ab=null;z.S.a().sa(a,"recording");z.S.a().sa(b,"recording");Im();var h=
z.K("voicenote-message-spacer");z.Ce(h,"");var l=z.K("thRecorderPH");z.O(l,"display","none")}}}catch(m){z.S.a().b(m)}if(this.Xk){var n=z.K("thVNload-bar",this.M.f());z.O(n,"display","block");this.ue.exportMonoWAV(z.S.a().bind(this,this.Nq))}}catch(p){z.S.a().b(p)}};
z.f.pr=function(){try{var a=z.K("round-countdownclock");60==this.oc&&z.O(a,"display","block");--this.oc;var b=100/60*this.oc,c=Math.floor(this.oc/60),d=this.oc-60*c,e=c+":"+d;10>d&&(e=c+":0"+d);this.T.clearRect(-300,-300,800,800);this.Wa(this.T,"#efefef",4,1,this.Ec);0<b&&100>b&&this.Wa(this.T,"#FD3269",4,b/100,this.Ec);z.Ce(a,e);0==this.oc?Hm(this):this.kj=(0,window.setTimeout)(this.fn,1E3)}catch(g){z.S.a().b(g)}};
z.f.ir=function(){try{var a=z.K("round-micplayback-circle-img");z.S.a().P(a,"play")?(z.S.a().sa(a,"play"),z.S.a().da(a,"stop"),Ym(this)):(z.S.a().sa(a,"stop"),z.S.a().da(a,"play"),Wm(this))}catch(b){z.S.a().b(b)}};z.f.or=function(){try{this.ve?Hm(this):Vm(this)}catch(a){z.S.a().b(a)}};z.f.Nq=function(a){try{if(this.gh){var b=z.K("voicenote-message-spacer");z.Ce(b,z.U.a().ha("voicenote_nomic"))}else(window.URL||window.webkitURL).createObjectURL(a),z.S.a().Gd.sc(a,z.S.a().bind(this,this.Ir))}catch(c){z.S.a().b(c)}};
z.f.Ir=function(){try{this.M.Q(!1),this.Ab=null}catch(a){z.S.a().b(a)}};z.f.Aq=function(a){try{if(this.gh){var b=z.K("voicenote-message-spacer");z.Ce(b,z.U.a().ha("voicenote_nomic"))}else{0<this.W.src.length&&(window.URL||window.webkitURL).revokeObjectURL(this.W.src);var c=(window.URL||window.webkitURL).createObjectURL(a);this.W.src=c}}catch(d){z.S.a().b(d)}};z.f.qp=function(){try{this.Ab.createBufferSource()}catch(a){z.S.a().b(a)}};
z.f.Kl=function(){try{z.O(z.wi(this.M),"left","0px"),z.O(z.wi(this.M),"top","0px"),z.O(z.wi(this.M),"width","100%"),z.O(z.wi(this.M),"height","140px")}catch(a){z.S.a().b(a)}};z.f.wh=function(){try{for(var a=window.document.querySelectorAll("[data-voicenote-dialog]"),b=0;b<a.length;b++){var c=a[b].getAttribute("data-voicenote-dialog");a[b].innerText=z.U.a().ha(c)}}catch(d){z.S.a().b(d)}};
z.f.Ys=function(a){try{var b=this.Ab.createMediaStreamSource(a);this.ue=new window.Recorder(b);this.$e=this.Ab.createAnalyser();this.$e.qu=.3;this.$e.Ot=1024;b.connect(this.$e);this.ue.record();this.ve=!0;this.ue.getBuffers(this.hq);this.dj=new window.Uint8Array(this.$e.fftSize);this.$e.getByteTimeDomainData(this.dj);this.ym()}catch(c){z.S.a().b(c)}};
z.f.vl=function(){try{if(this.Zi){var a=(100/this.W.duration*this.W.currentTime).toFixed();this.T.clearRect(-300,-300,800,800);this.Wa(this.T,"#efefef",4,1,this.Ec);0<a&&100>a&&this.Wa(this.T,"#555555",4,a/100,this.Ec);this.Yi=(0,window.setTimeout)(this.en,250)}}catch(b){z.S.a().b(b)}};
z.f.ul=function(){try{var a=z.K("round-micplayback-circle-img");z.S.a().sa(a,"stop");z.S.a().da(a,"play");Wm(this);(0,window.clearTimeout)(this.Yi);this.Yi=0;this.T.clearRect(-300,-300,800,800);this.Wa(this.T,"#efefef",4,1,this.Ec)}catch(b){z.S.a().b(b)}};
z.f.sl=function(a){try{if(!this.ve){var b=z.Q(a.currentTarget),c={};c.x=a.clientX-b.x;c.y=a.clientY-b.y;var d=z.kg(a.currentTarget);a={};a.x=d.width/2;a.y=d.height/2;var e=2*Math.PI,g=(Math.atan2(c.y-a.y,c.x-a.x)+e)%e,h=(0,window.parseInt)(g/e*100),h=h+25;99<h&&(h-=100);this.W.currentTime=h/100*this.W.duration;var l=z.K("round-micplayback-circle-img");z.S.a().sa(l,"play");z.S.a().da(l,"stop");Ym(this)}}catch(m){z.S.a().b(m)}};
z.f.ym=function(){try{if(this.ve)if(250<this.Vg)this.gh=!0,this.Jd.clearRect(-200,-200,400,400),Hm(this);else{(0,window.requestAnimationFrame)(z.S.a().bind(this,this.ym));this.$e.getByteTimeDomainData(this.dj);var a=this.dj[0];this.se<a-127&&129<a?this.se+=20:this.se>a-127&&(this.Jd.clearRect(-200,-200,400,400),this.se--);this.Jd.globalAlpha=.5;this.Jd.beginPath();this.Jd.arc(67,67,46+this.se,0,2*Math.PI,!1);this.Jd.arc(67,67,20,0,2*Math.PI,!0);this.Jd.fillStyle="#FD3269";this.Jd.fill();128==a?this.Vg++:
this.Vg=0}else this.Jd.clearRect(-200,-200,400,400)}catch(b){z.S.a().b(b)}};z.f.Wa=function(a,b,c,d,e){d=Math.min(Math.max(0,d||1),1);e=(e-c)/2;a.beginPath();a.arc(0,0,e,0,2*Math.PI*d,!1);a.strokeStyle=b;a.lineCap="round";a.lineWidth=c;a.stroke()};z.Kf("FixedToolbar");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_FixedToolbar.js