(function(z){
var Zj=function(a){return z.Za.concat.apply(z.Za,arguments)};var ak=function(a,b,c){this.hc=a||null;this.Vp=!!c};var bk=function(a){if(!a.Ca&&(a.Ca=new z.Wc,a.Aa=0,a.hc))for(var b=a.hc.split("\x26"),c=0;c<b.length;c++){var d=b[c].indexOf("\x3d"),e=null,g=null;0<=d?(e=b[c].substring(0,d),g=b[c].substring(d+1)):e=b[c];e=(0,window.decodeURIComponent)(e.replace(/\+/g," "));e=ck(a,e);a.add(e,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};
var ck=function(a,b){var c=String(b);a.Vp&&(c=c.toLowerCase());return c};var dk=function(a){var b=z.Pc(a);if("undefined"==typeof b)throw Error("Keys are undefined");var c=new ak(null,0,void 0);a=z.Oc(a);for(var d=0;d<b.length;d++){var e=b[d],g=a[d];if(z.ia(g)){var h=c;h.remove(e);0<g.length&&(h.hc=null,h.Ca.set(ck(h,e),z.$a(g)),h.Aa+=g.length)}else c.add(e,g)}return c};
var ek=function(a){this.h=this.we=this.N=null;null!=z.K("docs-texteventtarget-iframe")&&null!=z.K("docs-texteventtarget-iframe")&&(this.N=z.K("docs-texteventtarget-iframe").contentDocument,this.we=z.K("docs-texteventtarget-iframe").contentWindow,this.h=z.K("kix-appview-editor"),this.R=a,new z.xd,this.ra=!1,this.nc=this.Cb=this.mb=null,this.U=[],this.Dc=!1,this.G={},this.G.wa=0,this.G.Il="",this.G.Hl="",this.G.pc=null,this.Od=this.Nd=0,this.ed=/\w/i,this.F={},this.F.parentId="kix-appview-editor",this.F.positionId=
"kix-cursor",this.F.seq="1",this.rf=z.S.a().bind(this,this.Qh),this.qf=z.S.a().bind(this,this.Af),this.Ka=this.ia=null,this.Mh=this.Ye=!1,this.bh=null)};var fk=function(a){this.ma=a;this.bn="";this.Gc=this.hj=0;this.jn=this.ag=this.oh="";this.Wk=null;a=window.location.pathname.split("/");this.bj=a[a.length-2];this.kn=""};
var gk=function(a){try{var b=new z.xd;z.E(b,"complete",z.S.a().bind(a,a.Iq));var c=dk(new z.Wc({Authorization:"Bearer "+a.Gc}));b.send("https://www.googleapis.com/drive/v2/files?q\x3dtitle%3D'TexthelpVoiceNoteConfig'\x26spaces\x3dappDataFolder","GET",null,c)}catch(d){z.S.a().b(d)}};var hk=function(a,b,c){try{var d=new z.xd;null!==c&&z.E(d,"complete",c);var e=dk(new z.Wc({Authorization:"Bearer "+a.Gc}));d.send("https://www.googleapis.com/drive/v2/files/"+b,"GET",null,e)}catch(g){z.S.a().b(g)}};
var ik=function(a){try{var b=new z.xd;z.E(b,"complete",z.S.a().bind(a,a.Pq));var c=dk(new z.Wc({Authorization:"Bearer "+a.Gc}));b.send("https://www.googleapis.com/drive/v2/files/"+a.bj+"/properties/voicenotefolder","GET",null,c)}catch(d){z.S.a().b(d)}};var jk=function(a){try{var b=new window.FileReader;b.readAsDataURL(a.bn);b.onloadend=z.S.a().bind(a,a.Cq)}catch(c){z.S.a().b(c)}};var kk=function(a){try{z.S.a().fireEvent(a,"mousedown"),z.S.a().fireEvent(a,"mouseup"),z.S.a().fireEvent(a,"click")}catch(b){z.S.a().b(b)}};
var lk=function(a,b){this.R=a;this.ma=b;this.ad=null;this.ff=this.bl=!1;this.T=this.ab=null;this.nh=0;this.hl=null;z.E(window.document,"mouseover",this.sh,!0,this);z.E(window.document,"mouseout",this.br,!0,this);null!=z.K("docs-texteventtarget-iframe")&&(this.N=z.K("docs-texteventtarget-iframe").contentDocument,this.cm=z.S.a().bind(this,this.ul),this.dm=z.S.a().bind(this,this.vl),this.Uo=z.S.a().bind(this,this.sl))};
var mk=function(a,b){try{(0,window.clearTimeout)(a.nh),a.ff=!0,a.nh=(0,window.setTimeout)(a.dm,250),b.play()}catch(c){z.S.a().b(c)}};
var Y=function(){this.md="kix-selection-overlay";this.Ge="kix-selection-overlay-mac";this.rc="kix-appview-editor";this.Rb="kix-cursor";this.Fe="kix-cursor-caret";this.fa="kix-lineview";this.fb="kix-lineview-text-block";this.Xj="kix-paragraphrenderer";this.Th="kix-page";this.ng="thRWGDns";this.mg="thCTag";this.ya=this.ng+":"+this.mg;this.I="textHELPWR";this.o="thWord";this.Ea="thSpace";this.Cf=100;this.Tf=this.Ha=null;this.bf=-1;this.xe=0;this.mc=z.gj.a().Ib();this.nb=this.mc.sentences.wordEnds;this.pa=
[];this.Vk=[];this.Zf=0;this.Pf=null;this.mh=!1;this.ed=/\w/i;this.ac=/[\u200B-\u200D\uFEFF\u25A0-\u27A2]/g;this.h=z.K(this.rc);this.te=[];this.Uf=this.Ga=null;this.Bb=-1;this.cf=!1;this.Mb=null;this.ef=z.S.a().bind(this,this.Pd);z.S.a();this.ma=new ek(this);this.sq=new lk(this,this.ma);window.addEventListener("message",this.ef,!1);z.T.a().j("onSpeechStateChanged",this.Wn,this);this.bc=null;var a=this.ma;if(null!=a.N){var b=z.S.a().bind(a,a.ye);a.N.addEventListener("keyup",b,!0);b=z.S.a().bind(a,
a.rh);a.N.addEventListener("keypress",b,!0);b=z.S.a().bind(a,a.gd);a.N.addEventListener("keydown",b,!0);b=z.S.a().bind(a,a.hd);z.E(window.document,"click",b,!0);b=z.S.a().bind(a,a.th);z.E(window.document,"mouseup",b);b=z.S.a().bind(a,a.lf);z.E(a.h,"scroll",b);b=z.S.a().bind(a,a.ph);z.E(window,"resize",b);z.T.a().j("onPredictionChange",a.mf,a);z.T.a().j("onWRPredictionStateChanged",a.nf,a);z.T.a().j("onSpeechRecognitionChange",a.vh,a);z.T.a().j("onFocusOnCursor",a.rj,a)}};
var uk=function(a,b){var c={};c.wg=z.K(a.Fe);if(null==c.wg)return c;c.$d=z.Q(c.wg);var d=z.Gj(c.wg,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d/2,10),e=0;a.P(c.wg,"kix-cursor-italic")&&(e=d/Math.tan(Math.PI/180*77));c.$d.y+=d;c.$d.x+=e+(c.wg.offsetWidth/2+.5);c.element=vk(a,c.$d.x,c.$d.y,b);return c};
var vk=function(a,b,c,d){a=a.If(b,c);b=null;for(c=0;c<a.length;c++){if("string"==typeof a[c].className&&void 0!==a[c].className&&-1<a[c].className.indexOf(d))if(-1<a[c].className.indexOf("kix-lineview-content"))b=a[c];else return a[c];if("kix-lineview"==a[c].className)return a[c]}return b};var wk=function(a,b,c){for(var d=0;d<b.length;d++)xk(a,[b[d].toLowerCase()],c)};
var xk=function(a,b,c){b=b.map(function(a){return a.toLowerCase()});for(var d=0;d<c.length;d++)for(var e=c[d],g=e.filter(function(a){return"is"==a.ty})[0].s,h=e.filter(function(a){return"is"==a.ty})[0].ibi,e=e.filter(function(a){var c="text"==a.st,d=a.sm&&a.sm.ts_bgc&&-1!=b.indexOf(a.sm.ts_bgc);return"as"==a.ty&&c&&d}),l=0;l<e.length;l++){var m=e[l].si-h;a.hk.push({text:g.substr(m,e[l].ei-h-m+1),color:e[l].sm.ts_bgc.toUpperCase()})}};
var yk=function(a,b,c,d){try{var e=new window.XMLHttpRequest;e.onreadystatechange=function(){if(4==e.readyState&&200==e.status){var a=window.document.createElement("div");a.id="th-page-reloaded";a.style.display="none";a.innerHTML=e.responseText;var g={hk:[],title:window.document.getElementsByClassName("docs-title-input")[0].getAttribute("value"),url:window.location.href},m=[];z.S.a().Pj(a.getElementsByTagName("script")).filter(function(a){return"DOCS_modelChunk \x3d ["==a.innerHTML.substr(0,19)}).forEach(function(a){a=
a.innerHTML.replace("DOCS_modelChunk \x3d ","");a=a.substr(0,a.lastIndexOf("}]; ")+2);a=JSON.parse(a);m.push(a)});2==b?wk(g,c,m):xk(g,c,m);d(g)}}.bind(a);e.open("GET",window.location.href,!0);e.send()}catch(g){z.S.a().b(g)}};
var zk=function(a,b,c){var d=b.nextSibling;null!==d?(a.Sd(d,a.h),(0,window.setTimeout)(function(){var a=z.He(d);if(0<a.length&&" "!==a)if(window.paragraph=z.K(this.Xj,d),null==window.paragraph)zk(this,d,c);else{if(window.nextPageLine=this.Mm(window.paragraph,!0),null!==window.nextPageLine)if(a=window.nextPageLine.closest(".kix-page-header"),null!==a){if(null!==a.nextElementSibling)if(1>a.nextElementSibling.textContent.trim().length)zk(this,d,c);else{for(var a=a.nextSibling.querySelectorAll("."+this.fa),
b=null,h=0;h<a.length;h++)0<a[h].textContent.trim().length&&(b=a[h],h=a.length);null!==b&&c(this.Ji(b))}}else c(this.Ji(window.nextPageLine))}else zk(this,d,c)}.bind(a),100)):c([])};
var Ak=function(a){try{for(var b=["thrwgdns:thctag","title","desc"];void 0!=a.nodeName&&b.includes(a.nodeName.toLowerCase());)if(null!=a.parentElement)a=a.parentElement;else break;return void 0==a.nodeName?!1:"svg"==a.nodeName.toLowerCase()||"image"==a.nodeName.toLowerCase()||"desc"==a.nodeName.toLowerCase()||"title"==a.nodeName.toLowerCase()?!0:!1}catch(c){return!1}};
var Bk=function(a){for(var b=a;!a.classList.contains("kix-embeddedobject-crop");)if(null!=a.parentElement)a=a.parentElement;else break;return a.classList.contains("kix-embeddedobject-crop")?a:b};var Ck=function(a,b){try{a.Pf=z.X(a.Th);a.Zf=a.h.scrollTop;a.cf=!1;var c=z.S.a().bind(a,a.Cj);(0,window.setTimeout)(function(){c(0,b)},0)}catch(d){z.S.a().b(d)}};
z.S.prototype.If=z.ca(18,function(a,b){if(void 0!==window.document.If)return window.document.If(a,b);for(var c=[],d=[],e,g;(e=window.document.elementFromPoint(a,b))&&-1===c.indexOf(e)&&null!=e;)c.push(e),d.push({value:e.style.getPropertyValue("pointer-events"),Fl:e.style.getPropertyPriority("pointer-events")}),e.style.setProperty("pointer-events","none","important");for(e=d.length;g=d[--e];)c[e].style.setProperty("pointer-events",g.value?g.value:"",g.Fl);return c});
z.Wc.prototype.Hf=z.ca(1,function(a){return z.Yc(this.Hc,a)});z.f=ak.prototype;z.f.Ca=null;z.f.Aa=null;z.f.Hm=function(){bk(this);return this.Aa};z.f.add=function(a,b){bk(this);this.hc=null;a=ck(this,a);var c=this.Ca.get(a);c||this.Ca.set(a,c=[]);c.push(b);this.Aa++;return this};z.f.remove=function(a){bk(this);a=ck(this,a);return this.Ca.Hf(a)?(this.hc=null,this.Aa-=this.Ca.get(a).length,this.Ca.remove(a)):!1};z.f.clear=function(){this.Ca=this.hc=null;this.Aa=0};
z.f.Hf=function(a){bk(this);a=ck(this,a);return this.Ca.Hf(a)};z.f.Xc=function(){bk(this);for(var a=this.Ca.zd(),b=this.Ca.Xc(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};z.f.zd=function(a){bk(this);var b=[];if(z.t(a))this.Hf(a)&&(b=Zj(b,this.Ca.get(ck(this,a))));else{a=this.Ca.zd();for(var c=0;c<a.length;c++)b=Zj(b,a[c])}return b};
z.f.set=function(a,b){bk(this);this.hc=null;a=ck(this,a);this.Hf(a)&&(this.Aa-=this.Ca.get(a).length);this.Ca.set(a,[b]);this.Aa++;return this};z.f.get=function(a,b){var c=a?this.zd(a):[];return 0<c.length?String(c[0]):b};
z.f.toString=function(){if(this.hc)return this.hc;if(!this.Ca)return"";for(var a=[],b=this.Ca.Xc(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.zd(d),g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="\x3d"+(0,window.encodeURIComponent)(String(d[g])));a.push(h)}return this.hc=a.join("\x26")};z.f.clone=function(){var a=new ak;a.hc=this.hc;this.Ca&&(a.Ca=this.Ca.clone(),a.Aa=this.Aa);return a};
z.f.extend=function(a){for(var b=0;b<arguments.length;b++)z.Qc(arguments[b],function(a,b){this.add(b,a)},this)};z.f=ek.prototype;
z.f.ye=function(a){var b=[];b.push(a.keyCode);z.T.a().u("onKeyUpEvent",b);null!==this.ia&&((0,window.clearTimeout)(this.ia),this.ia=null);a.ctrlKey&&17!==a.keyCode&&(this.Mh=!0,null!==this.bh&&(0,window.clearTimeout)(this.bh),this.bh=(0,window.setTimeout)(function(){(0,window.clearTimeout)(this.bh);this.bh=null;this.Mh=!1}.bind(this),1E3));17===a.keyCode?this.Ye=this.Mh?!1:!0:(this.ia=(0,window.setTimeout)(this.rf,100),this.Ye=!1)};z.f.rh=function(){};
z.f.gd=function(a){if(a.ctrlKey&&47<a.keyCode&&58>a.keyCode){var b=[];b.push(a);null!==this.mb&&((0,window.clearTimeout)(this.mb),this.mb=null);this.mb=(0,window.setTimeout)(function(){this.Qn(b)}.bind(this),10);z.Pj()&&(a.preventDefault(),a.stopPropagation())}40===a.keyCode&&this.Ye&&(this.Mh=this.Ye=!1,a.preventDefault(),a.stopPropagation(),window.texthelp.RW4GC.thToolbarStoreInstance.onFocusBar(window.document.activeElement));this.Ye=!1};z.f.Qn=function(a){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(a)};
z.f.Ma=function(){null!==this.ia&&((0,window.clearTimeout)(this.ia),this.ia=null);this.ia=(0,window.setTimeout)(this.rf,10)};
z.f.Qh=function(){this.ia=null;if(this.ra){var a=this.R.Pe();if(null==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=z.V.a().O().prediction.results,c=z.V.a().O().language.services;this.G.wa++;999<this.G.wa&&(this.G.wa=0);var d='"'+z.S.a().og(a.context)+'","'+b+'","en_US"',e='{ "parent":"'+this.R.rc+'", "position":"'+this.R.Rb+'","addSpace":false,"seq":"'+this.G.wa+'"}';z.S.a().Fh(this.G.wa);this.G.pc=a;e=z.od(e);d=[];d[0]=a.context;d[1]=b;d[2]=c;if(null!==z.K("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();
else e.context=d,window.postMessage({method:"thPrediction",type:"1757FROM_PAGERW4G",payload:e},"*")}}};z.f.th=function(){if(null!==z.K("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose(),this.ce();else return!0};z.f.lf=function(){try{var a=this.R.Ba();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)}catch(b){}};
z.f.ph=function(){(0,window.setTimeout)(function(){var a=this.R.Ba();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)}.bind(this),0)};z.f.Af=function(a){if(null!==z.K("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose(),this.ce();else{var b=z.Ne(a.target,"kix-lineview-text-block");null==b&&(b=z.K("kix-lineview-text-block",a.target.parentNode));null!==b&&(this.ra&&this.Ma(),this.ce())}};
z.f.hd=function(a){null!==this.Ka&&((0,window.clearTimeout)(this.Ka),this.Ka=null);var b=this;this.Ka=(0,window.setTimeout)(function(){b.qf(a)},300)};z.f.ce=function(){z.T.a().u("onWordChanged",[])};
z.f.mf=function(a){try{if(null!==z.K("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=this.G.pc,c=b.prepunc+a[0]+b.postpunc;this.ua("ArrowRight",b.selectRight);this.ua("Shift+ArrowLeft",b.selectLeft+b.selectRight);b.spaceatstart&&(c=" "+c);b.spaceatend&&(c+=" ");this.ig(c);b.spaceatend||this.ua("ArrowRight");var d=z.S.a().Ra();a=[];a.push("prediction insert");a.push(d.Email);a.push(d.Email.split("@")[1]);window.postMessage({type:"1757FROM_PAGERW4G",
key:"function",method:"SendEvent",parameters:a},"*");this.Ma()}}catch(e){z.S.a().b(e)}};z.f.nf=function(a){try{this.ra=a[0];var b=z.K("kix-cursor-caret",this.h);if(null!==b){var c=0,d=z.Q(b),e=z.Gj(b,"height"),e=e.substr(0,e.length-2),e=(0,window.parseInt)(e,10);d.y+=e/2;z.S.a().P(b,"kix-cursor-italic")&&(c=e/Math.tan(Math.PI/180*77));d.x+=c;this.hi(d.x,d.y)}this.ra&&(a=[],a.push("kix-appview-editor"),this.Ma(),z.T.a().u("onOpenPredictionWindow",a))}catch(g){z.S.a().b(g)}};
z.f.rj=function(){try{var a=z.K("kix-cursor-caret",this.h);null!==a&&(z.S.a().fireEvent(a,"click"),a.focus())}catch(b){z.S.a().b(b)}};z.f.vh=function(a){try{"scratch that"==a.toLowerCase().trim()?this.ua("CTRL+Z"):this.ig(a)}catch(b){z.S.a().b(b)}};z.f.ic=function(){this.U.keydown=this.vb("keydown",this.N);this.U.keyup=this.vb("keyup",this.N);this.U.keypress=this.vb("keypress",this.N);this.U.mousedown=this.vb("mousedown",this.h);this.U.mouseup=this.vb("mouseup",window.document);this.Dc=!0};
z.f.vb=function(a,b){try{var c=[],d;for(d in b)if(d.match(/^closure/)&&"number"!=typeof b[d]){var e=b[d];if(e){if(!this.Cb)for(var g in e){var h=e[g];if(h&&h!=b)for(var l in h){var m=h[l];m&&void 0!=m.length&&m[0].src==b&&(this.Cb=g)}}for(var n in e[this.Cb])if(n==a)for(var p=e[this.Cb][n],q=0;q<p.length;q++){if(!this.nc&&p[q].src==b)for(var s in p[q])if(p[q][s].src==b){this.nc=s;break}c.push({Am:p[q],xc:p[q][this.nc]})}}}return c}catch(r){z.S.a().b(r)}};
z.f.ua=function(a,b,c){void 0==c&&(c="keydown");void 0==b&&(b=1);if(!(1>b)){this.Dc||this.ic();void 0==b&&(b=1);var d={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.N,defaultPrevented:!1,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.N.body,target:this.N.body,timeStamp:(new Date).getTime(),type:c,view:this.we,which:0};switch(a){case "SPACE":d.ctrlKey=
!0;d.keyCode=32;d.which=32;break;case "CTRL+Z":d.ctrlKey=!0;d.keyCode=90;d.which=90;break;case "Apple+Z":d.metaKey=!0;d.keyCode=90;d.which=90;break;case "Delete":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Backspace":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Newline":d.defaultPrevented=!0;d.keyCode=13;d.which=13;break;case "CTRL+Home":d.ctrlKey=!0;d.keyCode=36;d.which=36;break;case "Shift+ArrowLeft":d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "ArrowRight":d.keyCode=
39;d.which=39;break;case "ArrowLeft":d.keyCode=37;d.which=37;break;case "CTRL+Shift+ArrowRight":d.ctrlKey=!0;d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "CTRL+ALT+M":d.ctrlKey=!0;d.keyCode=77;d.shiftKey=!1;d.altKey=!0;d.which=77;break;case "CMD+ALT+M":d.metaKey=!0;d.keyCode=77;d.shiftKey=!1;d.altKey=!0;d.which=77;break;case "CTRL+Shift+S":d.ctrlKey=!0;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=83;break;case "CMD+Shift+S":d.metaKey=!0;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=83;break;
case "CTRL+Shift+F":d.metaKey=!0;d.keyCode=70;d.shiftKey=!0;d.altKey=!1;d.which=70;break;case "CMD+Shift+F":d.metaKey=!0;d.keyCode=70;d.shiftKey=!0;d.altKey=!1;d.which=70;break;default:return}for(a=0;a<b;a++)for(var e in this.U[c])this.U[c][e].xc(d)}};
z.f.ig=function(a){this.Dc||this.ic();for(var b={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.N,defaultPrevented:!0,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.N.body,target:this.N.body,timeStamp:0,type:"keypress",view:this.we,which:0},c,d=0;d<a.length;d++){c=a[d];b.charCode=c.charCodeAt(0);b.keyCode=c.charCodeAt(0);b.which=c.charCodeAt(0);
b.shiftKey=c.toUpperCase()==c?!0:!1;b.timeStamp=(new Date).getTime();try{switch(b.keyCode){case 10:if(0<d){if(10!=a[d-1].charCodeAt(0)){b.charCode=13;b.keyCode=13;b.which=13;var e}}else b.charCode=13,b.keyCode=13,b.which=13;for(e in this.U.keydown)this.U.keydown[e].xc(b);break;case 13:for(e in this.U.keydown)this.U.keydown[e].xc(b);break;default:for(e in this.U.keypress)this.U.keypress[e].xc(b)}}catch(g){}}};
z.f.hi=function(a,b){this.Dc||this.ic();z.Q(this.h);if(!(a<this.h.x||a>this.h.x+this.h.offsetWidth||b<this.h.y||b>this.h.y+this.h.offsetHeight)){var c=z.S.a().bind(this,this.Dg);this.Nd=a;this.Od=b;(0,window.setTimeout)(c,1)}};
z.f.Dg=function(){var a={altKey:!1,bubbles:!0,button:0,cancelBubble:!1,cancelable:!0,charCode:0,clientX:this.Nd,clientY:this.Od,clipboardData:void 0,ctrlKey:!1,currentTarget:window.document,dataTransfer:null,defaultPrevented:!1,detail:1,eventPhase:0,fromElement:null,keyCode:0,layerX:0,layerY:0,metaKey:!1,offsetX:0,offsetY:0,pageX:0,pageY:0,relatedTarget:null,returnValue:!0,screenX:0,screenY:0,shiftKey:!1,srcElement:this.h,target:this.h,timeStamp:(new Date).getTime(),toElement:this.h,type:null,view:window,
which:1,x:0,y:0},b=["mousedown","mouseup"],c;for(c in b){a.type=b[c];"mouseup"==b[c]&&(a.srcElement=a.target=a.toElement=window.document);for(var d in this.U[b[c]])this.U[b[c]][d].xc(a)}};z.f=fk.prototype;z.f.sc=function(a,b){try{this.hj=z.T.a().j("onAddVoiceNoteToken",this.Br,this),window.postMessage({type:"1757FROM_PAGERW4G",key:"function",method:"AddVoiceNote",parameters:[]},"*"),this.bn=a,this.Wk=b}catch(c){z.S.a().b(c)}};z.f.Br=function(a){try{z.T.a().zf(this.hj),this.Gc=a,gk(this)}catch(b){z.S.a().b(b)}};
z.f.Iq=function(a){try{var b=JSON.parse(a.target.H.response).items;if(0==b.length)try{var c=new z.xd;z.E(c,"complete",z.S.a().bind(this,this.Kr));var d=dk(new z.Wc({Authorization:"Bearer "+this.Gc,"Content-type":"application/json"})),e='{"title": "'+z.U.a().ha("voicenote_folder")+'","mimeType": "application/vnd.google-apps.folder"}';c.send("https://www.googleapis.com/drive/v2/files","POST",e,d)}catch(g){z.S.a().b(g)}else{var h=b[0];try{this.jn=h.id,this.oh=h.description,hk(this,this.oh,z.S.a().bind(this,
this.Jr))}catch(l){z.S.a().b(l)}}}catch(m){z.S.a().b(m)}};z.f.Hq=function(){try{ik(this)}catch(a){z.S.a().b(a)}};
z.f.Kr=function(a){try{var b=this.oh=JSON.parse(a.target.H.response).id;try{var c=new z.xd;z.E(c,"complete",z.S.a().bind(this,this.Hq));var d=dk(new z.Wc({Authorization:"Bearer "+this.Gc,"Content-type":"application/json"}));c.send("https://www.googleapis.com/drive/v2/files?q\x3dtitle%3D'TexthelpVoiceNoteConfig'","POST",'{"title": "TexthelpVoiceNoteConfig","parents": [{"id": "appfolder"}],"description": "'+b+'"}',d)}catch(e){z.S.a().b(e)}}catch(g){z.S.a().b(g)}};
z.f.Jr=function(a){try{var b=JSON.parse(a.target.H.response);if(void 0!==b.error||b.labels.trashed){var c=this.jn,d=z.S.a().bind(this,this.Lq);try{var e=new z.xd;null!==d&&z.E(e,"complete",d);var g=dk(new z.Wc({Authorization:"Bearer "+this.Gc}));e.send("https://www.googleapis.com/drive/v2/files/"+c,"DELETE",null,g)}catch(h){z.S.a().b(h)}}else ik(this)}catch(l){z.S.a().b(l)}};z.f.Lq=function(){try{gk(this)}catch(a){z.S.a().b(a)}};
z.f.Pq=function(a){try{var b=JSON.parse(a.target.H.response);void 0!==b.error?hk(this,this.bj,z.S.a().bind(this,this.Pn)):(this.ag=b.value,hk(this,this.ag,z.S.a().bind(this,this.Lr)))}catch(c){z.S.a().b(c)}};
z.f.Pn=function(a){try{this.kn=JSON.parse(a.target.H.response).title;try{var b=new z.xd;z.E(b,"complete",z.S.a().bind(this,this.Kq));var c=dk(new z.Wc({Authorization:"Bearer "+this.Gc,"Content-type":"application/json"}));b.send("https://www.googleapis.com/drive/v2/files","POST",'{"title": "'+this.kn+'","parents": [{"id": "'+this.oh+'"}],"mimeType": "application/vnd.google-apps.folder"}',c)}catch(d){z.S.a().b(d)}}catch(e){z.S.a().b(e)}};
z.f.Lr=function(a){try{var b=JSON.parse(a.target.H.response);void 0!==b.error||b.labels.trashed?hk(this,this.bj,z.S.a().bind(this,this.Pn)):jk(this)}catch(c){z.S.a().b(c)}};
z.f.Kq=function(a){try{this.ag=JSON.parse(a.target.H.response).id;var b=new z.xd;z.E(b,"complete",z.S.a().bind(this,this.Fr));var c=dk(new z.Wc({Authorization:"Bearer "+this.Gc,"Content-type":"application/json"}));b.send("https://www.googleapis.com/drive/v2/files/"+this.bj+"/properties","POST",'{"key": "voicenotefolder","value": "'+this.ag+'"}',c)}catch(d){z.S.a().b(d)}};
z.f.Fr=function(){try{var a=new z.xd;z.E(a,"complete",z.S.a().bind(this,this.sr));var b=dk(new z.Wc({Authorization:"Bearer "+this.Gc,"Content-type":"application/json"}));a.send("https://www.googleapis.com/drive/v2/files/"+this.ag+"/permissions","POST",'{"role": "reader","type": "anyone"}',b)}catch(c){z.S.a().b(c)}};z.f.sr=function(a){try{JSON.parse(a.target.H.response),jk(this)}catch(b){z.S.a().b(b)}};
z.f.Cq=function(a){try{var b=a.currentTarget.result.replace(/^data:audio\/(wav|ogg);base64,/,""),c=new z.xd;z.E(c,"complete",z.S.a().bind(this,this.Bq));var d=dk(new z.Wc({Authorization:"Bearer "+this.Gc,"Content-type":'multipart/form-data; boundary\x3d"rw4g"'})),e='--rw4g\nContent-Type: application/json; charset\x3dUTF-8\n\n{"title": "'+z.U.a().ha("voicenote_filename")+'.wav", "description": "Read\x26Write for Google Chrome\u2122", "mimeType": "audio/wav","parents": [{"id": "'+this.ag+'"}]}\n--rw4g\nContent-Type: audio/wav\nContent-Transfer-Encoding: base64\n\n'+
b+"\n--rw4g--\n";c.send("https://www.googleapis.com/upload/drive/v2/files?uploadType\x3dmultipart","POST",e,d)}catch(g){z.S.a().b(g)}};
z.f.Bq=function(a){try{this.ma.ua("CTRL+ALT+M",1,"keydown");this.ma.ua("CTRL+ALT+M",1,"keyup");this.ma.ua("CMD+ALT+M",1,"keydown");this.ma.ua("CMD+ALT+M",1,"keyup");var b=window.document.activeElement;this.Wk();z.K("docos-input-buttons-post",b.parentElement);var c;var d=a.target;c=d.H?z.od(d.H.responseText):void 0;var e=c.webContentLink.split("\x26")[0];b.value="Texthelp;"+e+";";b.focus();b.click();this.Ab=null;kk(b);try{var g=z.K("docos-input-buttons-post",b.parentElement);kk(g)}catch(h){z.S.a().b(h)}}catch(l){z.S.a().b(l)}};z.f=lk.prototype;z.f.sc=function(a,b){try{null==this.hl&&(this.hl=new fk(this.ma)),this.hl.sc(a,b)}catch(c){z.S.a().b(c)}};
z.f.sh=function(a){try{var b=a.target;if(void 0!=b&&void 0!=b.classList&&null!=b.classList){var c=z.Ne(b,"docos-anchoreddocoview");if(null!=c){var d=z.K("docos-collapsible-replyview",c);if(null!=d&&d!=this.ad){this.bl=!0;var e=z.K("kix-thvoicenote-overlay");z.xe(e);this.ff=!1;this.T=null;this.ad=d;if(null!=this.ad){var g=this.ad.innerText;if(-1!=g.indexOf("Texthelp;https://")&&null!=z.Ne(this.ad,"docos-anchoreddocoview")){var h=g.split(";")[1],e=z.K("kix-thvoicenote-overlay");null==e&&(e=z.Ki(z.Dk));
e.style.top=(0,window.parseInt)(this.ad.offsetTop)+"px";e.style.left=(0,window.parseInt)(this.ad.offsetLeft)+"px";e.style.width=(0,window.parseInt)(this.ad.offsetWidth)+"px";e.style.height=(0,window.parseInt)(this.ad.offsetHeight)+"px";e.style.background="white";e.style.visibility="visible";var l=z.K("thVNPlayback",e);this.ab={wj:l.getAttribute("data-percent")||0,size:l.getAttribute("data-size")||60,lineWidth:l.getAttribute("data-line")||4,rotate:l.getAttribute("data-rotate")||0};var m=window.document.createElement("canvas");
"undefined"!==typeof window.G_vmlCanvasManager&&window.G_vmlCanvasManager.Xt(m);this.T=m.getContext("2d");m.width=m.height=this.ab.size;m.id="thVNCanPlayback";m.className="thVNCanPlayback";l.appendChild(m);this.T.translate(this.ab.size/2,this.ab.size/2);this.T.rotate((-.5+this.ab.rotate/180)*Math.PI);this.T.translate(.5,.5);this.Wa(this.T,"#efefef",this.ab.lineWidth,1);0<this.ab.wj&&this.Wa(this.T,"#555555",this.ab.lineWidth,this.ab.wj/100);var n=z.K("thVNCanPlayback",e),p=z.K("thVNIcon",e);z.E(n,
"mouseup",this.Uo,!0,this);z.E(p,"mouseup",this.er,!0,this);var q=z.K("thVNAudio",e);q.src=h;this.ad.parentElement.appendChild(e);q.onended=this.cm}}}}}}catch(s){z.S.a().b(s)}};z.f.br=function(a){try{if(this.bl){var b=a.Xa.toElement;void 0!=b&&void 0!=b.classList&&null!=b.classList&&null===z.Ne(b,"docos-anchoreddocoview")&&(this.bl=!1)}}catch(c){z.S.a().b(c)}};
z.f.er=function(a){try{var b=z.Ne(a.currentTarget,"thVNPlayback");if(null!=b){var c=z.K("thVNIcon",b);if(null!=c){var d=z.K("thVNAudio",b);if(this.ff){this.ff=!1;z.S.a().qd(c,"thVNPause","thVNPlay");try{d.pause()}catch(e){z.S.a().b(e)}}else{this.ff=!0;z.S.a().qd(c,"thVNPlay","thVNPause");mk(this,d);var g=z.S.a().qa();if(null==g)return null;window.postMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:g,action:"voice note play",label:g.split("@")[1]}},"*")}}}}catch(h){z.S.a().b(h)}};
z.f.sl=function(a){try{var b=z.K("thVNAudio");if(null!=b){var c=z.Q(a.currentTarget),d,e;d=a.clientX-c.x;e=a.clientY-c.y;var g=z.kg(a.currentTarget),h=2*Math.PI,l=(0,window.parseInt)((Math.atan2(e-g.height/2,d-g.width/2)+h)%h/h*100),l=l+25;99<l&&(l-=100);b.currentTime=l/100*b.duration;mk(this,b);var m=z.Ne(a.currentTarget,"thVNPlayback");if(null!=m){var n=z.K("thVNIcon",m);null!=n&&z.S.a().P(n,"thVNPlay")&&z.S.a().qd(n,"thVNPlay","thVNPause")}}}catch(p){z.S.a().b(p)}};
z.f.ul=function(a){try{this.ff=!1;(0,window.clearTimeout)(this.nh);this.nh=0;var b=a.currentTarget;if(null!=b){var c=b.parentElement;if(null!=c){var d=z.K("thVNIcon",c);null!=d&&(this.T.clearRect(-100,-100,200,200),this.Wa(this.T,"#efefef",this.ab.lineWidth,1),0<this.ab.wj&&this.Wa(this.T,"#555555",this.ab.lineWidth,this.ab.wj/100),z.S.a().qd(d,"thVNPause","thVNPlay"))}}}catch(e){z.S.a().b(e)}};
z.f.vl=function(){try{if(this.ff){var a=z.K("thVNAudio");if(null!=a){var b=(100/a.duration*a.currentTime).toFixed();this.T.clearRect(-100,-100,200,200);this.Wa(this.T,"#efefef",this.ab.lineWidth,1);this.Wa(this.T,"#555555",this.ab.lineWidth,b/100);this.nh=(0,window.setTimeout)(this.dm,250)}}}catch(c){z.S.a().b(c)}};
z.f.Wa=function(a,b,c,d){d=Math.min(Math.max(0,d||1),1);var e=(this.ab.size-this.ab.lineWidth)/2;a.beginPath();a.arc(0,0,e,0,2*Math.PI*d,!1);a.strokeStyle=b;a.lineCap="round";a.lineWidth=c;a.stroke()};z.Yj.vj="Parser";z.B(Y,z.Mj);z.f=Y.prototype;z.f.Eh=function(a){try{this.Ha=a}catch(b){z.S.a().b(b)}};z.f.Xb=function(){try{return this.Ha.name}catch(a){z.S.a().b(a)}};z.f.Vb=function(){try{return this.Ha.bar}catch(a){z.S.a().b(a)}};z.f.Wn=function(a){this.mh=0<a.length?a[0]:!1};z.f.sc=function(a,b){try{this.sq.sc(a,b)}catch(c){z.S.a().b(c)}};
z.f.Pg=function(){try{var a=this.he(),b=!1;z.S.a();for(var c=this.mc.sentences.sentenceEndExclusions,d=0;d<a.length-1;d++){var e=z.Nj(c,a[d]);if(!e){try{e=this.Vk[d]}catch(g){e=!1}void 0==e&&(e=!1)}if(!e)for(var h in this.nb)-1!==a[d].search(this.nb[h])&&(b=!0,d=a.length)}if(!b)return a;var l=z.X(this.md);if(1>l.length&&(l=z.X(this.Ge),1>l.length))return this.Ki(!0);var l=Array.prototype.slice.call(l,0),m=z.S.a().bind(this,this.Lj);l.sort(m);this.na();var n=z.Q(l[0]),p=z.Gj(l[0],"height"),p=p.substr(0,
p.length-2),p=(0,window.parseInt)(p,10);n.y+=p/2;this.Mb=z.Q(l[l.length-1]);var q=z.Gj(l[l.length-1],"width"),q=q.substr(0,q.length-2),q=(0,window.parseInt)(q,10);this.Mb.x+=q;return this.me(n.x,n.y)}catch(s){z.S.a().b(s)}};z.f.Lf=function(){try{var a=z.X(this.md);return 1>a.length&&(a=z.X(this.Ge),1>a.length)?!1:!0}catch(b){z.S.a().b(b)}};
z.f.xb=function(){try{var a=window.document.getElementById("th-RW4GC-picture-dictionary"),b=window.document.getElementById("th-RW4GC-translator"),c=window.document.getElementById("th-RW4GC-prediction");if((null!=window.document.getElementById("th-RW4GC-dictionary")||null!=a||null!=b||null!=c)&&this.mh)return"";var a=[],d=RegExp("\u200b","g"),e=z.X(this.md);if(1>e.length){e=z.X(this.Ge);if(1>e.length){var g=z.K(this.Rb);if(null!==g){var h=z.Q(g),l=z.K(this.Fe),m=z.Gj(l,"height"),m=m.substr(0,m.length-
2),m=(0,window.parseInt)(m,10)/2,e=0;this.P(l,"kix-cursor-italic")&&(e=m/Math.tan(Math.PI/180*77));h.y+=m;h.x+=l.offsetWidth/2+e;var n=z.Gj(l,"display");z.O(l,"display","none");this.me(h.x,h.y,!1);var m="",p=this.Ad(h.x,h.y,0);if(null==p)return z.O(l,"display",n),this.na(),a;h=[];h.push(p);for(var g=e=0,q=window.document.querySelectorAll(".textHELPWR"),s=0;s<q.length;s++)if(q[s]==p){if(0<s)for(g=s-1;q[g].classList.contains("thWord")&&!(h.unshift(q[g]),g--,0>g););e=s+1;if(e<q.length)for(;q[e].classList.contains("thWord")&&
!(h.push(q[e]),e++,e>=q.length););break}for(s=0;s<h.length;s++)m+=h[s].textContent;this.na();a.push(m.replace(d,""));z.O(l,"display",n)}return a}return""}if(this.mh)return"";s=this.he();2<s.length?a.push(s[0].replace(d,"")):a.push(s.join(" ").replace(d,""));this.na();return a}catch(r){z.S.a().b(r)}};
z.f.If=function(a,b){for(var c=[],d=[],e,g;(e=window.document.elementFromPoint(a,b))&&-1===c.indexOf(e)&&null!=e;)c.push(e),d.push({value:e.style.getPropertyValue("pointer-events"),Fl:e.style.getPropertyPriority("pointer-events")}),e.style.setProperty("pointer-events","none","important");for(e=d.length;g=d[--e];)c[e].style.setProperty("pointer-events",g.value?g.value:"",g.Fl);return c};
z.f.Pe=function(){try{var a=[];a.context="";a.word="";a.cursorindex="";a.spaceatstart=!1;a.spaceatend=!1;a.prepunc="";a.postpunc="";a.selectRight=0;a.selectLeft=0;a.prechar="";a.currentchar="";a.postchar="";var b=z.K(this.Fe);z.Q(b);var c=window.document.createRange(),d=uk(this,"kix-embeddedobject-view");if(!(null!==d.element&&-1<d.element.className.indexOf("kix-embeddedobject-view"))){d=uk(this,"kix-wordhtmlgenerator-word-node");if(null==d.element&&(d=uk(this,"kix-lineview"),null==d.element))return null;
d.element=z.Ne(d.element,"kix-lineview");if(null==d.element)return null;for(var e=b="",g=!1,h=window.document.createTreeWalker(d.element,window.NodeFilter.SHOW_TEXT),l=h.nextNode(),m="",n="",p=0,q=0;l;){for(var s=l.textContent.split(""),r=0;r<s.length;r++){c.setStart(l,r);c.setEnd(l,r+1);var w=c.getClientRects(),v;a:{for(var I=d.$d.x+1,F=d.$d.y,A=0;A<w.length;++A){var N=w[A];if(N.left<I&&N.right>I&&N.top<F&&N.bottom>F){v=N;break a}if(N.left>I){v="leftpastcaret";break a}}v=!1}"leftpastcaret"==v?(r=
s.length+10,g=!0):v?(r=s.length+10,g=!0):"\u200b"!==c.toString()&&(n=c.toString(),b+=n);p++}g||p!=d.element.textContent.length||(b=d.element.textContent,g=!0,p=b.length+1);if(g){var P=b.split(/(.*?[.?!])/g);1<P.length&&(b=P[P.length-1]);a.context=d.element.textContent.substr(0,p-1).replace(this.ac,"").split(/(.*?[.?!])/g);for(r=a.context.length;r--;)1>a.context[r].length&&a.context.splice(r,1);for(var L=d.element.textContent.substr(0).replace(this.ac,"").split(/(.*?[.?!])/g),r=L.length;r--;)""===
L[r]&&L.splice(r,1);0<q&&(L[0]=L[0].substr(q),a.context[0]=a.context[0].substr(q));if(1>a.context.length)for(var pa=d.element.previousSibling;pa;)10<pa.textContent.split(/\s/g).length?(m=pa.textContent+m,pa=null):(m=pa.textContent+m,pa=pa.previousSibling);0<a.context.length?(L=L[a.context.length-1],a.context=a.context[a.context.length-1],e=L.substr(a.context.length),-1!==".?!".indexOf(a.context.substr(a.context.length-2),1)&&(a.spaceatstart=!0)):L=e=a.context="";var ab=a.context.substr(a.context.length-
1);if((0==a.context.length||"\u00a0"==ab||-1!==".?!".indexOf(ab))&&!z.S.a().Wb()["Predict Ahead"])return null==this.bc&&(this.bc=z.K("kix-thprediction-popup")),null!==this.bc&&(z.O(this.bc,"display","none"),z.S.a().Jj(!1)),null;var hc=a.context.split(/\s/g);a.word=L.split(/\s/g)[hc.length-1];var Jd=hc[hc.length-1].replace(this.ac,"");a.cursorindex=Jd.length;if(0==a.context.length||0==e.trim().replace(/[\u200B]/g,"").length)a.spaceatend=!0;0==a.cursorindex?(a.selectLeft=0,a.selectRight=0,a.spaceatend=
!0,a.word=""):(a.selectLeft=Jd.replace(this.ac,"").length,a.selectRight=a.word.replace(this.ac,"").length-a.selectLeft);var ic=a.word.match(this.ed),Ja=a.word,jc=Ja.indexOf(ic);0<jc&&(a.prepunc=Ja.substring(0,jc).replace(/[\u200B]/g,""),Ja=Ja.substring(jc).replace(/[\u200B]/g,""));var Ja=Ja.split("").reverse().join(""),ic=Ja.match(this.ed),Bc=Ja.indexOf(ic);0<Bc&&(a.postpunc=Ja.substring(0,Bc),a.postpunc=a.postpunc.split("").reverse().join("").replace(/[\u200B]/g,""),Ja=Ja.substring(Bc));l=null}else Ak(l.parentElement)&&
(q=b.length),l=h.nextNode()}a.context=m+a.context;a.context=a.context.replace(this.ac,"").replace(/\u00a0/g," ");return a}}catch(bd){z.S.a().b(bd)}};
z.f.ge=function(){try{this.Zc();var a={};a.Ya=z.Ke(z.X(this.o)[0]);if(!(1>a.Ya.length)){for(var b=z.K(this.rc),c=b.innerHTML.split("\x3cthrwgdns:thctag")[0],d=c.split("\x3e"),e=[],g=0;g<d.length;g++){var h=d[g];"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0])}a.Oc=e.join(" ").split(a.Ya).length-1;var l=z.X(this.o);a.$a=a.Ya;a.Bc=a.Oc;a.$a=z.Ke(l[l.length-1]);if(0<a.$a.length){var m=b.innerHTML.split("\x3c/thrwgdns:thctag\x3e");m[m.length-1]=null;c=m.join();c=c.substr(0,c.length-2);d=c.split("\x3e");
e=[];for(g=0;g<d.length;g++)h=d[g],"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0]);a.Bc=e.join(" ").split(a.$a).length-1}this.na();return a}}catch(n){z.S.a().b(n)}};
z.f.$c=function(a){try{a=a.substring(1);var b=(0,window.parseInt)(a,16),b="rgb("+(b>>16&255)+","+(b>>8&255)+","+(b&255)+")",c=window.document.getElementById("bgColorButton");null==c&&(c=window.document.getElementById("textColorButton"));var d=window.document.getElementById("jfk-palette-cell-169");if(null!==c||null!==d){z.S.a().fireEvent(c,"mousedown");z.S.a().fireEvent(c,"mouseup");z.S.a().fireEvent(c,"click");var d=window.document.getElementById("jfk-palette-cell-169"),e=d.firstChild.style.backgroundColor;
d.firstChild.style.backgroundColor=b;z.S.a().fireEvent(d,"mousedown");z.S.a().fireEvent(d,"mouseup");z.S.a().fireEvent(d,"click");d.firstChild.style.backgroundColor=e}else{var g=this.ge(),h='{ "doc":"'+window.location.href+'","color":"'+a+'","startWordCount":"'+g.Oc+'", "startWord":"'+(0,window.escape)(g.Ya)+'", "endWordCount":"'+g.Bc+'", "endWord":"'+(0,window.escape)(g.$a)+'"}',h=z.od(h);window.postMessage({method:"highlightSelection",type:"1757FROM_PAGERW4G",payload:h},"*")}}catch(l){z.S.a().b(l)}};
z.f.vc=function(){try{var a=window.document.getElementById("bgColorButton");null==a&&(a=window.document.getElementById("textColorButton"));var b=window.document.getElementById("jfk-palette-cell-169");if(null!==a&&null!==b){z.S.a().fireEvent(a,"mousedown");z.S.a().fireEvent(a,"mouseup");z.S.a().fireEvent(a,"click");var c=b.firstChild.style.backgroundColor;b.firstChild.style.backgroundColor="rgb(255,255,255)";z.S.a().fireEvent(b,"mousedown");z.S.a().fireEvent(b,"mouseup");z.S.a().fireEvent(b,"click");
b.firstChild.style.backgroundColor=c}else{var d=this.ge(),e='{ "doc":"'+window.location.href+'","startWordCount":"'+d.Oc+'", "startWord":"'+(0,window.escape)(d.Ya)+'", "endWordCount":"'+d.Bc+'", "endWord":"'+(0,window.escape)(d.$a)+'"}',e=z.od(e);window.postMessage({method:"clearHighlights",type:"1757FROM_PAGERW4G",payload:e},"*")}}catch(g){z.S.a().b(g)}};
z.f.Zc=function(a){try{void 0==a&&(a=!0);var b=[],c=[],d=z.X(this.md);if(1>d.length&&(d=z.X(this.Ge),1>d.length))return b;var d=Array.prototype.slice.call(d,0),e=z.S.a().bind(this,this.Lj);d.sort(e);for(var g=d,d=[],e=0;e<g.length;e++)a?z.S.a().Um(g[e])&&d.push(g[e]):d.push(g[e]);if(0==d.length)return b;a=[];for(var h=g=null,l=null,e=0;e<d.length;e++){for(var h=z.X(this.fa,d[e].parentNode),m=0;m<h.length;m++)h[m]!==l&&(a.push(h[m]),l=h[m]);1>h.length&&(g=z.Ne(d[e],this.fa),g!==l&&(a.push(g),l=g))}g=
e=null;for(h=0;h<a.length;h++)for(e=z.X(this.fb,a[h]),l=0;l<e.length;l++)this.Kc(e[l]),null===g&&(g=e[l]);var n;n=Ak(d[0])?z.Ij(Bk(d[0]),this.h):z.Ij(d[0],this.h);var p;p=Ak(d[d.length-1])?z.Ij(Bk(d[d.length-1]),this.h):z.Ij(d[d.length-1],this.h);var q=z.kg(d[d.length-1]);p.x+=q.width-4;this.fi(n);this.di(p);this.sf();this.pa=z.X(this.o);var s=window.document.querySelectorAll("."+this.I),d="";for(n=0;n<s.length;n++)s[n].classList.contains(this.o)?d+=s[n].textContent:(b.push(d),d="",c.push(Ak(this.pa[n])));
b.push(d);c.push(Ak(this.pa[n]));this.Vk=c;return b}catch(r){z.S.a().b(r)}};z.f.getSelection=function(a){try{this.Qf=a;var b=this.ge(),c='{ "doc":"'+window.location.href+'","startWordCount":"'+b.Oc+'", "startWord":"'+(0,window.escape)(b.Ya)+'", "endWordCount":"'+b.Bc+'", "endWord":"'+(0,window.escape)(b.$a)+'"}',c=z.od(c);window.postMessage({method:"getSelection",type:"1757FROM_PAGERW4G",payload:c},"*")}catch(d){z.S.a().b(d)}};
z.f.Js=function(){this.h.scrollTop=this.Zf;var a=this.Zc(!1);this.na();this.Tf(a);this.Tf=null};z.f.Is=function(){this.h.scrollTop=this.Zf;var a=this.Zc(!1);this.na();a=a.join(" ").replace(/(\.+|\:|\!|\?)(\"*|\'*|\)*|}*|]*)(\s|\n|\r|\r\n)/gm,".\x3cbr /\x3e\x3cbr /\x3e$2").split("|");a={documentTitle:window.document.title.replace(" - Google Docs",""),html:a.join(" ")};this.Tf(a);this.Tf=null};z.f.Yc=function(a){try{this.Tf=a,Ck(this,this.Js.bind(this))}catch(b){z.S.a().b(b)}};
z.f.zi=function(a){try{this.Tf=a,Ck(this,this.Is.bind(this))}catch(b){z.S.a().b(b)}};z.f.he=function(){try{var a=z.X(this.md);if(1>a.length&&(a=z.X(this.Ge),1>a.length))return this.Ki(!0);var b=this.Zc();return 1>b.length&&1>a.length?this.Ki(!0):b}catch(c){z.S.a().b(c)}};z.f.xg=function(){try{this.fk();var a=z.X(this.I);if(0!==a.length)for(var b=a[0].parentNode;null!==a;){b.innerHTML=z.Ke(b);a=z.X(this.I);if(0===a.length)break;b=a[0].parentNode}}catch(c){z.S.a().b(c)}};
z.f.Rc=function(a,b,c,d){try{this.yg(a,b,c,d)}catch(e){z.S.a().b(e)}};z.f.Gf=function(a,b,c){try{this.zg(a,b,c)}catch(d){z.S.a().b(d)}};
z.f.Lg=function(){try{var a={trailingSpace:!1},b=this.he(),c=z.K(this.Rb);if(null!==c){var d=z.Q(c),e=z.K(this.Fe),g=z.Gj(e,"height"),g=g.substr(0,g.length-2),g=(0,window.parseInt)(g/2,10),c=0;this.P(e,"kix-cursor-italic")&&(c=g/Math.tan(Math.PI/180*77));d.y+=g;d.x+=c+(e.offsetWidth/2+.5);d.x+=1;d.y+=4;var h=this.Ad(d.x,d.y,0),l=z.Q(h);l.x+=this.Ah(h.offsetWidth);l.y+=this.Ah(h.offsetHeight);if(l.x<d.x-2||l.y<d.y-2)a.trailingSpace=!0;a.currentWord=(0,window.parseInt)(h.className.split(" ")[2])}this.na();
a.words=b.join(" ");return a}catch(m){z.S.a().b(m)}};z.f.yb=function(a){try{var b=function(a,b){b?a.classList.add("thImageHighlighted"):a.classList.remove("thImageHighlighted")};0<a&&(Ak(this.pa[a-1])?b(Bk(this.pa[a-1]),!1):z.S.a().sa(this.pa[a-1],"thHighlighted"));if(Ak(this.pa[a]))b(Bk(this.pa[a]),!0);else{try{this.Sd(this.pa[a],this.h)}catch(c){}z.S.a().da(this.pa[a],"thHighlighted")}}catch(d){z.S.a().b(d)}};z.f.stop=function(){try{this.na()}catch(a){z.S.a().b(a)}};
z.f.le=function(a,b){try{var c=null,d=z.V.a().O().speechoptions.continousreading;if(a&&!d&&null===this.Mb)this.Ga=null,this.Bb=-1,b(null);else{var e=z.Q(this.Ga);e.x+=this.Bb;for(var g=this.Ga.querySelectorAll(".kix-wordhtmlgenerator-word-node"),h=0;h<g.length;h++){var l=z.Q(g[h]).x;if(e.x>=l&&e.x<g[h].offsetWidth+l){var m=z.Q(g[h]);e.y=m.y;h=g.length}}if(-1<this.Bb)!d&&null!==this.Mb&&(e.y>this.Mb.y||e.y===this.Mb.y&&e.x>=this.Mb.x)?(this.Ga=null,this.Bb=-1,b(null)):(this.Ga=null,this.Bb=-1,b(this.me(e.x+
5,e.y+2)));else{this.Bb=-1;if(null!==this.Uf)for(var n=this.Uf.nextElementSibling;null!==n;){if(0<n.textContent.trim().length){this.Uf=n;var p;a:{try{c=[];this.Kc(n);this.Fj();this.sf();for(var q=z.X(this.o),s=0;s<q.length;s++)c.push(z.He(q[s]));(0,window.setTimeout)(this.Ff.bind(this),this.Cf);this.pa=z.X(this.o);1===this.pa.length&&this.yb(0);p=c;break a}catch(r){z.S.a().b(r)}p=void 0}b(p);return}n=n.nextElementSibling}c=this.Ga.closest(".kix-page");if(null==c)return[];s=c.querySelectorAll("."+
this.fa);if(1==s.length)return zk(this,c,b);var w=this.Ga;p=null;for(q=0;q<s.length;q++)w==s[q]&&(window.currentCellIndex=q,q=s.length);for(q=++window.currentCellIndex;q<s.length;q++)0<s[q].textContent.trim().length&&(p=s[q],q=s.length);if(null==p)return zk(this,c,b);b(this.Ji(p));return[]}}}catch(v){z.S.a().b(v)}};
z.f.Ki=function(a){var b=z.K(this.Rb);if(null!==b){var b=z.Q(b),c=z.K(this.Fe),d=z.Gj(c,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d/2,10),e=0;this.P(c,"kix-cursor-italic")&&(e=d/Math.tan(Math.PI/180*77));b.y+=d;b.x+=e+(c.offsetWidth/2+.5);return this.me(b.x,b.y,a)}return null};
z.f.Lk=function(a){try{var b=[];if(null!==a){var c=z.X(this.fb,a);for(a=0;a<c.length;a++)this.Kc(c[a]);this.Fj()}this.sf();for(var d=z.X(this.o),c=0;c<d.length;c++)b.push(z.He(d[c]));(0,window.setTimeout)(this.Ff.bind(this),this.Cf);this.pa=z.X(this.o);1===this.pa.length&&this.yb(0);return b}catch(e){z.S.a().b(e)}};
z.f.me=function(a,b,c){try{void 0==c&&(c=!0);var d=[],e=[],g=this.Ig(a,b);if(null==g&&(g=this.Ig(a,b),null==g))return null;if(null!==g){this.Uf=z.Ne(g,this.fb);if(null==this.Uf){var h=g.querySelectorAll("."+this.fb);if(0==h.length||1==h.length&&1==h.length&&0==h[0].textContent.trim().length)return;var l=z.Q(h[0]),m=l.x,n=m+h[0].offsetWidth;1<h.length&&(n=m+h[h.length-1].offsetWidth);return a>=n?this.me(n-4,l.y,c):this.me(m,l.y,c)}this.Kc(this.Uf);this.Ml(a,b)}this.sf();var p=z.X(this.o);if(0==p.length)return d;
for(a=0;a<p.length;a++)d.push(z.He(p[a])),e.push(Ak(p[a]));(0,window.setTimeout)(this.Ff.bind(this),this.Cf);this.pa=z.X(this.o);1===this.pa.length&&c&&this.yb(0);this.Vk=e;return d}catch(q){z.S.a().b(q)}};
z.f.Kc=function(a){try{var b=z.K(this.fb,a);if(null===b)if(this.P(a,this.fb))b=a;else throw Error("The element has no text child.");a={};a.key=b;a.value=a.key.innerHTML;this.te.push(a);var c=RegExp("\u200b","g"),b=b.childNodes;for(a=0;a<b.length;a++){for(var d=z.Oj(z.S.a(),b[a]),e=[],g=!1,h=0;h<d.length;h++){var l=d[h];if(g=Ak(l.parentElement))try{var m;var n=l;try{for(var p=["svg","image","title","desc"];!p.includes(n.nodeName.toLowerCase());)if(null!=n.parentElement)n=n.parentElement;else break;
m=void 0==n.nodeName?"undefined":"svg"==n.nodeName.toLowerCase()||"image"==n.nodeName.toLowerCase()?"image":"desc"==n.nodeName.toLowerCase()?"desc":"title"==n.nodeName.toLowerCase()?"title":"undefined"}catch(q){m="undefined"}"desc"==m.toLowerCase()?-1==l.nodeValue.indexOf("gmath_latex")&&e.push(d[h]):e.push(d[h])}catch(s){e.push(d[h])}else e.push(d[h])}for(g=0;g<e.length;g++)if(0<e.length){for(var r=e[g].nodeValue.split(/\s/),n=h="",p=0;p<r.length;p++){var w=r[p].replace(c,"");"\x3c"===w.substr(0,
1)?(n+="\x3c"+this.ya+" class\x3d'"+this.I+"'\x3e"+w.trim()+"\x3c/"+this.ya+"\x3e",p<r.length-1&&(n+="\x3c"+this.ya+" class\x3d'"+this.I+" "+this.Ea+"'\x3e\x26nbsp;\x3c/"+this.ya+"\x3e")):(" "===w||""===w)&&p<r.length-1?n+="\x3c"+this.ya+" class\x3d'"+this.I+" "+this.Ea+"'\x3e\x26nbsp;\x3c/"+this.ya+"\x3e":0<w.length&&(this.bf++,n+="\x3c"+this.ya+" class\x3d'"+this.I+" "+this.o+"'\x3e"+w.trim()+"\x3c/"+this.ya+"\x3e",p<r.length-1&&(n+="\x3c"+this.ya+" class\x3d'"+this.I+" "+this.Ea+"'\x3e\x26nbsp;\x3c/"+
this.ya+"\x3e"))}var h=h+n,v=z.oe("thrwgdns:thctag");v.innerHTML=h;var I=e[g],F=I.parentNode;F&&F.replaceChild(v,I);this.bf=-1}}}catch(A){z.S.a().b(A)}};z.f.Sd=function(a,b){try{if(void 0!=a&&void 0!=b){var c=0,d=a;if(null!=d&&void 0!=d){for(;d!==b;)null!==d.offsetTop&&void 0!==d.offsetTop&&(c+=d.offsetTop),d=d.offsetParent;c+30>b.scrollTop&&c<b.scrollTop+b.offsetHeight-30||(b.scrollTop=c-30)}}}catch(e){z.S.a().b(e)}};
z.f.na=function(){try{if(0!==z.X(this.I).length){for(var a in this.te)this.te[a].key.innerHTML=this.te[a].value;this.te.length=0}}catch(b){z.S.a().b(b)}};
z.f.fi=function(a){try{var b=[];this.xe=0;for(var c=z.X(this.I),d=0;d<c.length;d++){var e;e=Ak(c[d])?z.Ij(Bk(c[d]),this.h):z.Ij(c[d],this.h);var g=z.kg(c[d]);if(e.x+g.width<a.x)b.push(c[d]),this.P(c[d],this.o)&&this.xe++;else{for(;this.P(c[d],this.Ea);)b.push(c[d]),d++;d=c.length}}if(0!==b.length){a="";var h=b[0].parentNode;3==h.firstChild.nodeType&&(a+=h.firstChild.textContent,z.xe(h.firstChild));c="";for(d=0;d<b.length;d++)b[d].parentNode!==h&&(h.innerHTML=a+h.innerHTML,a="",h=b[d].parentNode),
c=z.Ke(b[d]),a+=c,z.xe(b[d]);0!=h.childNodes.length&&3==h.lastChild.nodeType&&(a+=h.lastChild.textContent);h.innerHTML=a+h.innerHTML}}catch(l){z.S.a().b(l)}};
z.f.di=function(a){try{for(var b=[],c=z.X(this.I),d=c.length-1;0<=d;--d){var e;e=Ak(c[d])?z.Ij(Bk(c[d]),this.h):z.Ij(c[d],this.h);e.x+=2;if(e.x>=a.x)b.push(c[d]),this.Ga=this.sk(c[d]),Ak(c[d])?this.Bb=z.Ij(Bk(c[d]),this.Ga).x:this.Bb=z.Ij(c[d],this.Ga).x;else{for(;this.P(c[d],this.Ea);)b.push(c[d]),d--;d=-1}}if(0!==b.length){a="";b.reverse();c=b;for(d=b.length-1;0<=d;d--)b[d].parentNode!==c&&(c.innerHTML+=a,a="",c=b[d].parentNode),a=z.Ke(b[d])+a,z.xe(b[d]);z.Ke(c.innerHTML);c.innerHTML+=a}}catch(g){z.S.a().b(g)}};
z.f.ek=function(a){try{var b=z.X(this.I,a),b=Array.prototype.slice.call(b,0);if(0!==b.length){a="";for(var c=b,d=b.length-1;0<=d;d--)b[d].parentNode!==c&&(c.innerHTML+=a,a="",c=b[d].parentNode),a=z.Ke(b[d])+a,z.xe(b[d]);c.innerHTML+=a}}catch(e){z.S.a().b(e)}};z.f.sf=function(){try{for(var a=-1,b=z.X(this.I),c=0;c<b.length;c++)this.P(b[c],this.o)&&a++,this.qd(b[c],(a+this.xe).toString(),a.toString())}catch(d){z.S.a().b(d)}};
z.f.Ff=function(){try{var a=z.X(this.md);1>a.length&&(a=z.X(this.Ge));for(var b=0;b<a.length;b++)z.xe(a[b])}catch(c){z.S.a().b(c)}};z.f.Ig=function(a,b){try{return vk(this,a,b,"kix-lineview")}catch(c){z.S.a().b(c)}};
z.f.Ad=function(a,b){try{var c=z.S.a().If(a,b),d=c.find(function(a){return a.classList.contains(this.o)}.bind(this));if(void 0==d){var e=c.find(function(a){return a.classList.contains(this.Ea)}.bind(this));if(void 0!==e){for(var g=[].slice.call(window.document.querySelectorAll("."+this.I)),h=g.findIndex(function(a){return e==a}.bind(this)),c=null,d=h;0<=d;d--)if(g[d].classList.contains(this.o)){c=g[d];break}for(var l=null,d=h;d<g.length;d++)if(g[d].classList.contains(this.o)){l=g[d];break}if(null==
l&&null==c)return null;if(null==l)return c;if(null==c)return l;var m=c.getBoundingClientRect().x+c.getBoundingClientRect().width,n=l.getBoundingClientRect().x;return a<=m+((n-m)/2+.5)?c:l}l=c[0].closest("."+this.fa);if(null==l)return d;var p=l.querySelectorAll("."+this.o);return a<=z.Q(p[0]).x?p[0]:p[p.length-1]}return d}catch(q){z.S.a().b(q)}};
z.f.Ah=function(a){try{var b=z.K("kix-zoomdocumentplugin-inner",this.h);if(null==b)return a;var c=z.Gj(b,"webkitTransform");if(null==c||0==c.length)return a;c=c.substr(6,c.length-7);return a*(0,window.parseFloat)(c)}catch(d){z.S.a().b(d)}};
z.f.Ml=function(a,b){try{var c=this.Ad(a,b,0);if(null===c||void 0===c){var d=z.X(this.o);if(0==d.length){this.na();return}var e=z.Q(d[0]).x,g=e+d[0].offsetWidth;1<d.length&&(e=z.Q(d[d.length-1]).x,g=e+d[d.length-1].offsetWidth);c=d[0];a>=g&&(c=d[d.length-1])}this.Le(c);c=this.Ad(a,b,0);this.Ke(c)}catch(h){z.S.a().b(h)}};z.f.Fj=function(){try{var a=z.X(this.o);this.Le(a[0]);a=z.X(this.o);null===a[0]?this.na():0==a.length?this.na():this.Ke(a[0])}catch(b){z.S.a().b(b)}};
z.f.Le=function(a){try{var b=null,c=null,d=null,e=!1;if(this.P(a,this.o))b=a;else if(this.P(a,this.fa)){for(var g=z.X(this.fb,a),h=0;h<g.length;h++)this.Kc(g[h]);c=z.X(this.o,a);b=c[c.length-1];e=!0}else return;z.S.a();var l=this.mc.sentences.sentenceEndExclusions,g=-1;null===c&&(d=z.Ne(b,this.fa),c=z.X(this.o,d));if(e)g=c.length-1;else for(var m=0;m<c.length;m++)c[m]===b&&(g=m,m=c.length);if(-1!==g){a=g;!e&&0<a&&a--;if(0<g){e=-1;for(m=a;0<=m;m--){var n=z.Nj(l,z.He(c[m]));n||(n=Ak(c[m]));if(!n)for(var p in this.nb)-1!==
c[m].innerText.search(this.nb[p])&&(e=m,m=-1)}if(-1<e){if(c.length-1===e)this.ek(z.Ne(c[e],this.fa));else{var q;q=Ak(c[e+1])?z.Ij(Bk(c[e+1]),this.h):z.Ij(c[e+1],this.h);this.fi(q)}return}}null===d&&(d=z.Ne(b,this.fa));this.Le(d.previousSibling)}}catch(s){z.S.a().b(s)}};
z.f.Ke=function(a){try{if(null!=a){var b=null,c=null,d=null,e=!1;if(this.P(a,this.o))b=a;else if(this.P(a,this.fa)){for(var d=a,g=z.X(this.fb,a),h=0;h<g.length;h++)this.Kc(g[h]);c=z.X(this.o,a);b=c[0];e=!0}else return;z.S.a();var l=this.mc.sentences.sentenceEndExclusions;a=-1;null===c&&(d=z.Ne(b,this.fa),c=z.X(this.o,d));if(e)a=0;else for(var m=0;m<c.length;m++)c[m]===b&&(a=m,m=c.length);if(-1!==a){e=-1;for(m=a;m<c.length;m++){var n=z.Nj(l,z.He(c[m]));n||(n=Ak(c[m]));if(!n)for(var p in this.nb)-1!==
c[m].innerText.search(this.nb[p])&&(e=m,m=c.length)}-1===e&&null===d.nextSibling&&(e=c.length-1);if(e===c.length-1||0<c.length&&-1==e)this.Ga=d;if(-1<e){if(e<c.length-1){var q;q=Ak(c[e+1])?z.Ij(Bk(c[e+1]),this.h):z.Ij(c[e+1],this.h);this.di(q)}}else null===d&&(d=z.Ne(b,this.fa)),this.Ke(d.nextSibling)}}}catch(s){z.S.a().b(s)}};z.f.sk=function(a){try{return null===a?null:this.P(a,this.fa)?a:z.Ne(a,this.fa)}catch(b){z.S.a().b(b)}};
z.f.oi=function(a,b){try{var c=window.document.createEvent("MouseEvents");c.initMouseEvent.apply(c,b);a.dispatchEvent(c)}catch(d){z.S.a().b(d)}};z.f.gk=function(){};z.f.fk=function(){try{var a=z.K(this.Rb);if(null!==a){var b=z.Q(a);this.gk(b.x,b.y)}}catch(c){z.S.a().b(c)}};z.f.Cj=function(a,b){try{if(a<this.Pf.length&&!1===this.cf){this.Sd(this.Pf[a],this.h);var c=z.S.a().bind(this,this.Cj);a+=1;(0,window.setTimeout)(function(){c(a,b)},30)}else this.cf=!0,void 0!==b&&b()}catch(d){z.S.a().b(d)}};
z.f.Pd=function(a){try{if(void 0!=a.source&&void 0!=a.data&&a.source==window&&"1757FROM_BGRW4G"==a.data.type)if("onGetSelection"==a.data.method){var b=z.od(a.data.payload);this.Qf(b)}else if("onCollectHighlights"==a.data.method){var c=z.od(a.data.payload);if(void 0!==c.auth)window.textHelp.webreaderapi.EventBusSingleton.getInst().publish("onShowDocsOAuthDialog",c.auth);else if("string"===typeof c){var d=null,e=z.S.a().Wc(),d=window.open(c,"_ntthch"+e);d.focus();this.lc(c)}else void 0!==c.auth?this.lc("false"):
0==c[0].highlights.length?this.lc("false"):this.lc("true")}else if("onVocabWords"==a.data.method){var g=z.od(a.data.payload);void 0!==g.auth?window.textHelp.webreaderapi.EventBusSingleton.getInst().publish("onShowDocsOAuthDialog",g.auth):"string"===typeof g&&(d=null,e=z.S.a().Wc(),d=window.open(g,"_ntthchVc"+e),d.focus(),this.il(g))}}catch(h){z.S.a().b(h)}};
z.f.yg=function(a,b,c){try{this.lc=a,z.U.a(),yk(this,b,c,function(a){var b=z.U.a().ha("ch_documentTitle");window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"CollectHighlights",parameters:{highlights:a.hk,title:window.document.getElementsByTagName("title")[0].innerHTML,url:window.location.href,docTitle:b}},"*")})}catch(d){z.S.a().b(d)}};
z.f.zg=function(a,b){try{yk(this,0,b,function(a){var b=[];z.S.a().Pj(a.hk).filter(function(a){if(3>a.text.split(/\s/g).length)return b.push(a.text.trim()),!0});b.sort();a=window.textHelp.webreader.ConfigurationSingleton.getInst().getConfiguration();var c={};c.words=b;c.locale=a.locale;c.user=a.serversettings.user;c.translations={};c.translations.docTitle=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_document_title");c.translations.title=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_title");
c.translations.heading=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_heading");c.translations.symbol=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_symbol");c.translations.notes=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_notes");c.translations.meaning=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_meaning");c.locale=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().language.services;
window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"Vocab",parameters:c},"*")})}catch(c){z.S.a().b(c)}};z.f.Lj=function(a,b){try{var c,d;Ak(a)?window.thPos=z.Ij(Bk(a),this.h):c=z.Ij(a,this.h);Ak(b)?window.thPos=z.Ij(Bk(b),this.h):d=z.Ij(b,this.h);if(c.y>d.y)return 1;if(c.y<d.y)return-1;if(c.y===d.y){if(c.x<d.x)return-1;if(c.x>d.x)return 1}return 0}catch(e){z.S.a().b(e)}};
z.f.Ji=function(a){try{if(null===a)return[];this.Sd(a,this.h);var b=z.V.a().O().speechoptions.continousreading;this.Ga=null;this.Bb=-1;if(null!==a){var c=z.Q(a);if(!b&&null!==this.Mb&&c.y>this.Mb.y)return this.Ga=null,this.Bb=-1,[];var d=z.Gj(a,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d,10);c.y+=d/2;return this.Lk(a)}return[]}catch(e){z.S.a().b(e)}};
z.f.Mm=function(a,b){try{var c=a.nextSibling;!0===b&&(c=a);if(null===c)return null;for(;null!==c;){var d=z.He(c);if(0<d.length&&" "!==d)return z.K(this.fa,c);c=c.nextSibling}return null}catch(e){z.S.a().b(e)}};z.f.Ul=function(a){try{a.doc=window.location.href,window.postMessage({method:"updateSelection",type:"1757FROM_PAGERW4G",payload:a},"*")}catch(b){z.S.a().b(b)}};
z.f.jd=function(){try{this.ma.rj(),this.ma.ua("CTRL+Shift+S",1,"keydown"),this.ma.ua("CTRL+Shift+S",1,"keyup"),this.ma.ua("CMD+Shift+S",1,"keydown"),this.ma.ua("CMD+Shift+S",1,"keyup")}catch(a){z.S.a().b(a)}};z.f.kd=function(){};z.f.Ba=function(){try{var a=z.K(this.Rb),b={x:10,y:10};if(null==a)return{x:-1,y:-1};var c=new z.H(a.offsetLeft,a.offsetTop),d=z.kg(a);b.x=c.x-d.width-a.scrollWidth-18;b.y=c.y+d.height+a.scrollHeight+6;return b}catch(e){z.S.a().b(e)}};z.u("textHelp.parsers",z.Yj);
z.u("textHelp.parsers.Parser",Y);Y.prototype.hiliteNextSentence=Y.prototype.le;Y.prototype.hiliteWord=Y.prototype.yb;Y.prototype.highlightSelection=Y.prototype.$c;Y.hiliteWord=Y.yb;Y.prototype.getUserSettings=Y.prototype.O;Y.prototype.getSelection=Y.prototype.getSelection;Y.prototype.getSelectionLocal=Y.prototype.Yc;Y.prototype.clearHighlights=Y.prototype.vc;Y.prototype.getTextWithContext=Y.prototype.Lg;Y.prototype.updateSelection=Y.prototype.Ul;Y.prototype.startSpeechRecognition=Y.prototype.jd;
Y.prototype.stopSpeechRecognition=Y.prototype.kd;Y.prototype.getParserName=Y.prototype.Xb;Y.prototype.getBarConfigFromParser=Y.prototype.Vb;Y.prototype.getPredictionPosition=Y.prototype.Ba;z.Kf("GDocsParser");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_GDocsParser.js