(function(z){
var Vk=function(a){this.h=window;this.R=a;new z.xd;this.ra=!1;this.nc=this.Cb=null;this.U=[];this.Dc=!1;this.G={};this.G.wa=0;this.G.Il="";this.G.Hl="";this.G.pc=null;this.Od=this.Nd=0;this.ed=/\w/i;this.F={};this.F.parentId="panel-right";this.F.positionId="Selected";this.F.seq="1";this.F.words=[];this.F.words.push("The");this.F.words.push("In");this.F.words.push("I");this.F.words.push("It");this.F.words.push("He");this.F.words.push("This");this.F.words.push("A");this.F.words.push("But");this.F.words.push("As");
this.F.words.push("For");this.qf=z.S.a().bind(this,this.Af);this.Gs=z.S.a().bind(this,this.it);this.Si=this.Ka=this.ia=null};
var Wk=function(a,b){try{if(null==z.K("docs-texteventtarget-iframe").contentDocument)(0,window.setTimeout)(Wk(a,b),200);else{a.N=z.K("docs-texteventtarget-iframe").contentDocument;a.we=z.K("docs-texteventtarget-iframe").contentWindow;var c=z.S.a().bind(a,a.ye);a.N.addEventListener("keyup",c,!0);var d=z.S.a().bind(a,a.rh);a.N.addEventListener("keypress",d,!0);var e=z.S.a().bind(a,a.gd);a.N.addEventListener("keydown",e,!0);var g=z.S.a().bind(a,a.hd);window.document.addEventListener("mousedown",g,!0);
window.document.addEventListener("mouseup",function(){(0,window.setTimeout)(function(){this.ce()}.bind(this),600)}.bind(a),!0);var h=z.S.a().bind(a,a.lf);z.E(a.h,"scroll",h);z.T.a().j("onPredictionChange",a.mf,a);z.T.a().j("onWRPredictionStateChanged",a.nf,a);z.T.a().j("onSpeechRecognitionChange",a.vh,a);b()}}catch(l){z.S.a().b(l)}};
var $=function(){this.md="Highlights";this.rc="WACViewPanel_EditingElement";this.fa="kix-lineview";this.fb="kix-lineview-text-block";this.Xj="kix-paragraphrenderer";this.Th="kix-page";this.ng="thRWGDns";this.mg="thCTag";this.ya=this.ng+":"+this.mg;this.I="textHELPWR";this.o="thGBWord";this.Ea="thSpace";this.Ha=null;this.bf=-1;this.Xf={};this.Xf.x=-1;this.Xf.y=-1;this.xe=0;this.mc=z.gj.a().Ib();this.nb=this.mc.sentences.wordEnds;this.pa=[];this.Zf=0;this.al=void 0;this.yh=!1;this.ed=/\w/i;this.Ta=
this.ja=null;this.pn=z.J(this.rc);this.re=window.document;this.h=window;this.te=[];this.Ga=null;this.Bb=-1;this.cf=!1;this.Mb=null;this.ze=0;this.ef=z.S.a().bind(this,this.Pd);this.ma=new Vk(this);window.addEventListener("message",this.ef,!1);var a=z.S.a().Qe(),b=this.re.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a+"assets/thFixedToolbar.css";this.re.body.appendChild(b);this.bd=this.Id=this.lb=this.nj=this.df=this.jh=this.dh=this.$f=null;Wk(this.ma,function(){}.bind(this))};
var Xk=function(a){try{var b=window.document.querySelector(".sketchy-text-selection-overlay");null==b&&(b=window.document.querySelector('rect[fill\x3d"#000"] '));if(null!==b)window.console.dir(b),Yk(a,b);else{var c=window.document.querySelector(".docs-text-ui-cursor-blink");null!==c&&(window.console.dir(c),Yk(a,c))}}catch(d){}};
var Zk=function(a){try{var b=[],c=$k(a);if(-1==c.innerHTML.indexOf("tspan"))b.push($k(a).innerHTML);else{var d=c.getElementsByTagName("tspan");a="";for(c=0;c<=d.length-1;c++)a+=d[c].innerHTML,a=a.replace(/[\u200B-\u200D\uFEFF]/g,"");b.push(a)}return b}catch(e){z.S.a().b(e)}};
var $k=function(a){var b=null;Xk(a);try{var c=[],c=a.lb.parentNode.getElementsByTagName("g")}catch(d){window.console.log(d)}for(var e=null,g=!1,h=1;h<c.length;h++)try{var g=c[h].hasAttribute("transform"),l=-10;0==g&&(l=0);if(1==g){var m=c[h].getAttribute("transform"),n=c[h].getAttribute("id"),p=c[h].getAttribute("class"),q=null,s=!1;null==n&null==p?(q=m.split(" "),s=!0):q=m.split(",");var r=q[1].replace(")",""),r=r.trim(),l=(0,window.parseInt)(r);if(1==s&&1==c[h].parentNode.hasAttribute("transform"))var q=
null,q=c[h].parentNode.getAttribute("transform").split(","),w=q[1].replace(")",""),w=w.trim(),l=l+(0,window.parseInt)(w)}a.Id=Math.round(a.Id);if(l>a.Id+5){var v=h-1;"sketchy-text-content-decoration"==c[h-1].getAttribute("class")&&(v=h-2);if(0!=c[v].getElementsByTagName("text").length){e=1==c[v].hasAttribute("id")?c[v].childNodes[0]:c[v];break}else if("image"==c[v].nodeName.toLowerCase()&&1==c[v].hasAttribute("latex")){e=c[v];break}}}catch(I){}null!=e&&void 0!=e||1!=g||(0!=c[c.length-1].getElementsByTagName("text").length?
e=1==c[c.length-1].hasAttribute("id")?c[c.length-1].childNodes[0]:c[c.length-1]:"image"==c[v].nodeName.toLowerCase()&&1==c[v].hasAttribute("latex")&&(e=c[c.length-1]));if(null==e||void 0==e)for(e=c[1],h=1;h<c.length;h++)c[h].getBBox();try{if(null!=e&&void 0!=e)for(var F=e.getElementsByTagName("text"),h=0;h<F.length;h++)(0,window.parseInt)(F[h].getAttribute("x"))<=(0,window.parseInt)(a.bd)&&(b=F[h])}catch(A){window.console.log(A)}return b};
var al=function(a,b){try{var c=[],d=[];if(null==b)if(null!=a.$f){if(null==a.lb)d=a.nj;else{var e=window.document.querySelectorAll(".sketchy-text-selection-overlay");0==e.length&&(e=window.document.querySelectorAll('rect[fill\x3d"#000"]'));0!=e.length?(d=a.lb.parentNode.parentNode.parentNode.getElementsByTagName("text"),a.ma.ic(),a.lb=null,a.ma.ua("ArrowLeft")):d=a.lb.previousSibling.getElementsByTagName("text")}a.dh>d.length-1&&(a.dh=d.length);for(var e=0,g=a.$f;g<=a.dh;g++)c[e]=d[g],e++;a.jh=c}else c=
a.lb.previousSibling.getElementsByTagName("text");else c=b,a.jh=c;d=-1;for(g=0;g<c.length;g++)c[g].getBBox().height>d&&(d=c[g].getBBox().height);for(g=0;g<c.length;g++){d=-1;for(e=g;e<c.length;e++)c[e].getBBox().height>d&&(d=c[e].getBBox().height);var h=c[g].getAttribute("x"),h=h.replace("px",""),h=(0,window.parseInt)(h),e=-1*d,l=d,m=c[g].getBBox().width;if(g!=c.length-1){var n=c[g+1].getAttribute("x"),n=n.replace("px",""),n=(0,window.parseInt)(n),p=c[g].getAttribute("x"),p=p.replace("px",""),p=(0,window.parseInt)(p);
c[g+1].getBBox().x>c[g].getBBox().x&&(m=n-p)}var q=l,s=window.document.createElement("g");s.setAttribute("class","sketchy-text-background-inner TH-Word-BackHighlightTest");s.setAttribute("transform","translate(0 "+q+")");var r=window.document.createElement("rect");r.setAttribute("x",h);r.setAttribute("y",e);r.setAttribute("width",1);r.setAttribute("height",l);r.setAttribute("fill","#ffff00");r.setAttribute("fill-opacity","1");s.appendChild(r);c[g].parentNode.parentNode.previousSibling.appendChild(s);
var w=c[g].parentNode.parentNode.previousSibling;w.innerHTML+=" ";var v=c[g].parentNode.parentNode.previousSibling.getBBox().height;v>=l+10&&(w.innerHTML+=" ",l=v);for(var I=window.document.getElementsByClassName("sketchy-text-background-inner TH-Word-BackHighlightTest"),F=0;0<I.length&&5E3>F;)I[I.length-1].remove(),F++;var A=window.document.createElement("g");A.setAttribute("class","sketchy-text-background-inner TH-Word-BackHighlight");A.setAttribute("transform","translate(0 "+q+")");window.colorRectEl=
window.document.createElement("rect");window.colorRectEl.setAttribute("x",h);window.colorRectEl.setAttribute("y",e);window.colorRectEl.setAttribute("width",m+1);window.colorRectEl.setAttribute("height",l);1!=c.length&&(window.colorRectEl.setAttribute("fill","#ffff00"),window.colorRectEl.setAttribute("fill-opacity","1"));A.appendChild(window.colorRectEl);c[g].parentNode.parentNode.previousSibling.appendChild(A);w=c[g].parentNode.parentNode.previousSibling;w.innerHTML+=" "}}catch(N){window.console.log(N)}};
var bl=function(){for(var a=[],b=0,c=window.document.getElementById("pages"),d=null,e=0;e<=c.childNodes.length-1;e++)if(-1==c.childNodes[e].getAttribute("style").indexOf("display: none")){d=c.childNodes[e];break}var g=d.querySelectorAll("[transform]");window.yCoordArray=[];for(e=0;e<g.length;e++)if(c=g[e].getAttribute("transform"),-1!=c.indexOf("matrix")&&("image"==g[e].nodeName.toLowerCase()||0<g[e].getElementsByTagName("text").length)){d=!1;if(0<g[e].getElementsByTagName("text").length)d=!0;else if("image"==
g[e].nodeName.toLowerCase()&&void 0!=g[e].href.baseVal&&0<g[e].href.baseVal.length){var h=g[e].getAttribute("latex");null!=h&&void 0!=h&&""!=h&&(d=!0)}d&&(a[b]=g[e],b++,d="",d=c.substr(c.lastIndexOf(",")+1),d=d.replace(")",""),d=(0,window.parseInt)(d),window.yCoordArray[b]=d)}window.yCoordArray.sort(function(a,b){return a-b});b=[];for(h=g=0;h<=window.yCoordArray.length-1;h++)for(e=0;e<=a.length-1;e++)if(c=a[e].getAttribute("transform"),d="",d=c.substr(c.lastIndexOf(",")+1),d=d.replace(")",""),d=(0,window.parseInt)(d),
d==window.yCoordArray[h]){c=!1;for(d=0;d<=b.length-1;d++)b[d]==a[e]&&(c=!0);c||(b[g]=a[e],g++)}return b};var cl=function(){try{for(var a=window.document.getElementsByClassName("thImageHighlightedSlides"),b=0;b<a.length;b++)dl(a[b],!1)}catch(c){z.S.a().b(c)}};var dl=function(a,b){b?a.classList.add("thImageHighlightedSlides"):a.classList.remove("thImageHighlightedSlides")};z.Qk=function(a,b,c,d){z.Rk?(z.Rk=!1,z.Sk(a,b,c,d)):window.setTimeout(z.Qk,100,a,b,c,d)};z.Sk=function(){};z.Tk=function(){};
z.Uk=function(){};var Yk=function(a,b){try{a.lb=b,a.Id=b.getAttribute("y"),a.bd=b.getAttribute("x")}catch(c){z.S.a().b(c)}};z.f=Vk.prototype;z.f.ye=function(a){null!==this.Si&&((0,window.clearTimeout)(this.Si),this.Si=null);var b=this;Xk(this.R);this.Si=(0,window.setTimeout)(function(){b.Gs(a)},500)};z.f.rh=function(){};
z.f.gd=function(a){if(a.ctrlKey&&47<a.keyCode&&58>a.keyCode){var b=[];b.push(a);null!==this.mb&&((0,window.clearTimeout)(this.mb),this.mb=null);this.mb=(0,window.setTimeout)(function(){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(b)}.bind(this),10);z.Pj()&&(a.preventDefault(),a.stopPropagation())}};z.f.it=function(a){this.ra&&this.Ma(a);this.ce()};z.f.Af=function(){this.ra&&this.Ma("")};
z.f.Ma=function(a){window.console.log("textHelp.parsers.GoogleBooksEventsManager.prototype.updatePrediction");this.ia=null;if(this.ra){void 0==a&&(a="");var b=this.R.Pe(a);"string"==typeof a&&(6<a.length||" "==a.substr(a.length-1,1))&&(b.context=a);if(null==b)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{a=z.V.a().O().prediction.results;var c=z.V.a().O().language.services;this.G.wa++;999<this.G.wa&&(this.G.wa=0);var d='"'+z.S.a().og(b.context)+'","'+a+'","'+c+'"',e='{ "parent":"panel-right", "position":"'+
this.R.Rb+'","addSpace":true,"seq":"'+this.G.wa+'"}';z.S.a().Fh(this.G.wa);this.G.pc=b;e=z.od(e);d=[];d[0]=b.context;d[1]=a;d[2]=c;if(null!==z.K("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else e.context=d,window.postMessage({method:"thPrediction",type:"1757FROM_PAGERW4G",payload:e},"*")}}};
z.f.hd=function(a){window.console.log("GoogleSlidesEventsManager.prototype.onMouseDown"+a);null!==this.Ka&&((0,window.clearTimeout)(this.Ka),this.Ka=null);var b=this;window.console.log("ActiveElement: "+window.document.activeElement);"thprediction-word"!=a.target.className&&(this.Ka=(0,window.setTimeout)(function(){b.qf(a)},600))};z.f.lf=function(){var a=this.R.Ba();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)};
z.f.ph=function(){var a=this.R.Ba();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)};z.f.ce=function(){z.T.a().u("onWordChanged",[])};z.f.mf=function(a){try{var b=this.G.pc,c=b.prepunc+a[0]+b.postpunc;this.ig(c+" ");var d=z.S.a().Ra();a=[];a.push("prediction insert");a.push(d.Email);a.push(d.Email.split("@")[1]);window.postMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",parameters:a},"*")}catch(e){z.S.a().b(e)}};
z.f.nf=function(a){try{if(this.ra=a[0])a=[],a.push("panel-right"),this.Ma(""),z.T.a().u("onOpenPredictionWindow",a)}catch(b){z.S.a().b(b)}};
z.f.vh=function(a){try{window.console.log("speech recog "+a);var b=(a+" ").split(""),c=window.document.getElementsByClassName("docs-texteventtarget-iframe");window.console.log("2");var d=c[0].contentDocument;window.console.log("2 end");window.console.log("3");var e=c[0].contentDocument.createEventObject?c[0].contentDocument.createEventObject():c[0].contentDocument.createEvent("Events");window.console.log("3 end");e.initEvent&&e.initEvent("keypress",!0,!0);for(a=0;a<b.length;a++)e.keyCode=b[a].charCodeAt(0),
e.which=b[a].charCodeAt(0),d.dispatchEvent?d.dispatchEvent(e):d.fireEvent("onkeydown",e)}catch(g){z.S.a().b(g)}};z.f.ic=function(){this.U.keydown=this.vb("keydown",this.N);this.U.keypress=this.vb("keypress",this.N);this.U.mousedown=this.vb("mousedown",window.document);this.U.mouseup=this.vb("mouseup",window.document);this.Dc=!0};
z.f.vb=function(a,b){try{var c=[],d;for(d in b)if(d.match(/^closure/)&&"number"!=typeof b[d]){var e=b[d];if(e){if(!this.Cb)for(var g in e){var h=e[g];if(h&&h!=b)for(var l in h){var m=h[l];m&&void 0!=m.length&&m[0].src==b&&(this.Cb=g)}}for(var n in e[this.Cb])if(n==a)for(var p=e[this.Cb][n],q=0;q<p.length;q++){if(!this.nc&&p[q].src==b)for(var s in p[q])if(p[q][s].src==b){this.nc=s;break}c.push({Am:p[q],xc:p[q][this.nc]})}}}return c}catch(r){z.S.a().b(r)}};
z.f.ua=function(a,b,c){window.console.log("fireKeyDownEvent");void 0==c&&(c="keydown");this.ic();void 0==b&&(b=1);var d={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.N,defaultPrevented:!1,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.N.body,target:this.N.body,timeStamp:(new Date).getTime(),type:"keydown",view:this.we,which:0};switch(a){case "CTRL+Z":d.ctrlKey=
!0;d.keyCode=90;d.which=90;break;case "Apple+Z":d.metaKey=!0;d.keyCode=90;d.which=90;break;case "Backspace":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Newline":d.defaultPrevented=!0;d.keyCode=13;d.which=13;break;case "CTRL+Home":d.ctrlKey=!0;d.keyCode=36;d.which=36;break;case "Shift+ArrowLeft":d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "ArrowRight":d.keyCode=39;d.which=39;break;case "ArrowLeft":d.keyCode=37;d.which=37;break;case "AppleAlt+ArrowLeft":d.altKey=!0;d.keyCode=37;d.which=
37;break;case "CTRL+ArrowLeft":d.ctrlKey=!0;d.keyCode=37;d.which=37;break;case "AppleAlt+Shift+ArrowRight":d.altKey=!0;d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "CTRL+Shift+ArrowRight":d.ctrlKey=!0;d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "AppleAlt+Shift+ArrowLeft":d.altKey=!0;d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "CTRL+Shift+ArrowLeft":d.ctrlKey=!0;d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "CTRL+Shift+S":d.ctrlKey=!0;d.charCode=83;d.keyCode=83;d.shiftKey=!0;d.altKey=
!1;d.which=83;d.code="KeyS";d.key="s";break;case "CMD+Shift+S":d.metaKey=!0;d.charCode=83;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=83;d.code="KeyS";d.key="s";break;case "ESC":d.keyCode=27,d.which=27;case "s":d.keyCode=83,d.which=83;default:return}for(a=0;a<b;a++)for(var e in this.U[c])this.U[c][e].xc(d)};
z.f.ig=function(a){window.getSelection();var b=this.G.pc.context,c=a.split(""),d=window.document.getElementsByClassName("docs-texteventtarget-iframe");window.console.log("4");var e=d[0].contentDocument;window.console.log("4 end");window.console.log("5");d=d[0].contentDocument.createEventObject?d[0].contentDocument.createEventObject():d[0].contentDocument.createEvent("Events");window.console.log("5 end");d.initEvent&&d.initEvent("keypress",!0,!0);if(" "!=b.substr(b.length-1,1)){this.ic();var g=0<=
window.navigator.platform.toUpperCase().indexOf("MAC"),h=this.R,l="";try{$k(h);for(var m=$k(h).parentNode.children,n=null,p=!1,q=0;q<m.length;q++)(0,window.parseInt)(m[q].getAttribute("x"))>(0,window.parseInt)(h.bd)-2&&(null==n&&(n=m[q]),l=l+m[q].innerHTML+" ",p=!0);0==p&&(l=m[m.length-1].innerHTML)}catch(s){window.console.log(s),l=""}""!=l?1==g?(this.ua("AppleAlt+ArrowLeft"),this.ua("AppleAlt+Shift+ArrowRight")):(this.ua("CTRL+ArrowLeft"),this.ua("CTRL+Shift+ArrowRight")):1==g?this.ua("AppleAlt+Shift+ArrowLeft"):
this.ua("CTRL+Shift+ArrowLeft")}for(m=0;m<c.length;m++)d.keyCode=c[m].charCodeAt(0),d.which=c[m].charCodeAt(0),e.dispatchEvent?e.dispatchEvent(d):e.fireEvent("onkeydown",d);try{" "!=b.substr(b.length-1,1)&&""!=b?(b=b.substring(0,b.lastIndexOf(" ")),this.Ma(b+" "+a)):this.Ma(b+a)}catch(r){window.console.log(r)}};
z.f.hi=function(a,b){this.Dc||this.ic();z.Q(this.h);if(!(a<this.h.x||a>this.h.x+this.h.offsetWidth||b<this.h.y||b>this.h.y+this.h.offsetHeight)){var c=z.S.a().bind(this,this.Dg);this.Nd=a;this.Od=b;(0,window.setTimeout)(c,1)}};
z.f.Dg=function(){this.ic();var a={altKey:!1,bubbles:!0,button:0,cancelBubble:!1,cancelable:!0,charCode:0,clientX:this.Nd,clientY:this.Od,clipboardData:void 0,ctrlKey:!1,currentTarget:window.document,dataTransfer:null,defaultPrevented:!1,detail:1,eventPhase:0,fromElement:null,keyCode:0,layerX:0,layerY:0,metaKey:!1,offsetX:0,offsetY:0,pageX:0,pageY:0,relatedTarget:null,returnValue:!0,screenX:0,screenY:0,shiftKey:!1,srcElement:this.h,target:this.h,timeStamp:(new Date).getTime(),toElement:this.h,type:null,
view:window,which:1,x:0,y:0},b=["mousedown","mouseup"],c;for(c in b){a.type=b[c];"mouseup"==b[c]&&(a.srcElement=a.target=a.toElement=window.document);for(var d in this.U[b[c]])this.U[b[c]][d].xc(a)}};z.Yj.vj="GoogleSlidesParser";z.B($,z.Mj);z.f=$.prototype;z.f.Eh=function(a){try{this.Ha=a}catch(b){z.S.a().b(b)}};z.f.Xb=function(){try{return this.Ha.name}catch(a){z.S.a().b(a)}};z.f.Vb=function(){try{return this.Ha.bar}catch(a){z.S.a().b(a)}};z.f.Wn=function(a){this.mh=0<a.length?a[0]:!1};
z.f.Pg=function(){try{var a=z.S.a().Qe(),b=this.re.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a+"assets/thFixedToolbar.css";this.re.body.appendChild(b);var c=this.he();al(this);z.S.a();for(var d=this.mc.sentences.sentenceEndExclusions,a=0;a<c.length-1;a++)if(!z.Nj(d,c[a]))for(var e in this.nb)-1!==c[a].search(this.nb[e])&&(a=c.length);return c}catch(g){z.S.a().b(g)}};z.f.Lf=function(){return!0};
z.f.xb=function(){try{var a=this.Yc();if(void 0!==a&&null!==a){if(1==a.length)return a[0]=a[0].replace(/[\u200B-\u200D\uFEFF]/g,""),a;if(2==a.length)return a[0]=a[0].replace(/[\u200B-\u200D\uFEFF]/g,""),a[1]=a[1].replace(/[\u200B-\u200D\uFEFF]/g,""),[a.join(" ")]}return Zk(this)}catch(b){z.S.a().b(b)}};
z.f.Pe=function(){Xk(this);var a="",b="",c=0;try{$k(this);for(var d=$k(this).parentNode.children,e=!1,e=!0,g=null,h=0;h<d.length;h++)(0,window.parseInt)(d[h].getAttribute("x"))<(0,window.parseInt)(this.bd)&&(null==g&&(g=d[h]),a=a+d[h].innerHTML+" ",b=d[h].innerHTML,c=h);if(1==e)for(var l=d[0].parentNode.parentNode.parentNode.parentNode.parentNode.getElementsByTagName("text"),h=0;h<l.length;h++)if(g==l[h]){0<h&&(a=l[h-2].innerHTML+" "+l[h-1].innerHTML+" "+a);break}Math.round((0,window.parseInt)(this.bd))>
Math.round((0,window.parseInt)(d[c].getAttribute("x"))+(0,window.parseInt)(d[c].getBBox().width))+1||(a=a.substring(0,a.length-1))}catch(m){window.console.log(m)}try{var n=this.lb.getBoundingClientRect();null!=n&&0!=n.left&&(this.Xf.x=n.left+n.width-22,this.Xf.y=n.top+n.height)}catch(p){window.console.log(p)}c=[];c.context=a;c.word=b;c.cursorindex="";c.spaceatstart=!1;c.spaceatend=!1;c.prepunc="";c.postpunc="";c.selectRight=0;c.selectLeft=0;c.prechar="";c.currentchar="";c.postchar="";return c};
z.f.ge=function(){try{this.Zc();var a={};a.Ya=z.Ke(z.X(this.o)[0]);if(!(1>a.Ya.length)){for(var b=z.J(this.rc),c=b.innerHTML.split("\x3cthrwgdns:thctag")[0],d=c.split("\x3e"),e=[],g=0;g<d.length;g++){var h=d[g];"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0])}a.Oc=e.join(" ").split(a.Ya).length-1;var l=z.X(this.o);a.$a=a.Ya;a.Bc=a.Oc;a.$a=z.Ke(l[l.length-1]);if(0<a.$a.length){var m=b.innerHTML.split("\x3c/thrwgdns:thctag\x3e");m[m.length-1]=null;c=m.join();c=c.substr(0,c.length-2);d=c.split("\x3e");
e=[];for(g=0;g<d.length;g++)h=d[g],"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0]);a.Bc=e.join(" ").split(a.$a).length-1}this.na();return a}}catch(n){z.S.a().b(n)}};
z.f.$c=function(a){try{a=a.substring(1);var b=(0,window.parseInt)(a,16);a="rgb("+(b>>16&255)+","+(b>>8&255)+","+(b&255)+")";var c=window.document.getElementById("textColorButton"),d=window.document.getElementById("jfk-palette-cell-577");if(null!==c||null!==d){c=window.document.getElementById("textColorButton");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(c,"mousedown");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(c,"mouseup");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(c,
"click");var d=window.document.getElementById("jfk-palette-cell-577"),e=d.firstChild.style.backgroundColor;d.firstChild.style.backgroundColor=a;window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(d,"mousedown");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(d,"mouseup");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(d,"click");d.firstChild.style.backgroundColor=e}}catch(g){z.S.a().b(g)}};
z.f.vc=function(){try{var a=window.document.getElementById("textColorButton"),b=window.document.createEvent("MouseEvents");b.initMouseEvent("mousedown",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null);a.dispatchEvent(b);var c=window.document.getElementById("textBackgroundColorButton"),b=window.document.createEvent("MouseEvents");b.initMouseEvent("mouseup",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null);c.dispatchEvent(b);for(var d=window.document.getElementsByClassName("goog-menuitem-label"),a=null,e=0;e<=d.length-
1;e++)if("Transparent"==d[e].innerText&&c.parentNode==d[e].parentNode.parentNode.parentNode){a=d[e].parentNode.parentNode;break}b=window.document.createEvent("MouseEvents");b.initMouseEvent("mousedown",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null);a.dispatchEvent(b);b=window.document.createEvent("MouseEvents");b.initMouseEvent("mouseup",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null);a.dispatchEvent(b);b=window.document.createEvent("MouseEvents");b.initMouseEvent("mousedown",!0,!0,window,0,0,0,0,0,!1,!1,
!1,!1,0,null);a.dispatchEvent(b);b=window.document.createEvent("MouseEvents");b.initMouseEvent("mouseup",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null);a.dispatchEvent(b)}catch(g){z.S.a().b(g)}};
z.f.rp=function(a){try{var b=window.document.getElementsByTagName("rect"),c=window.document.getElementById("pages"),d=c.getElementsByTagName("image"),e=!1,g=window.document.getElementById("speakernotes-workspace").querySelector(".docs-text-ui-cursor-blink");null!==g&&(this.lb=g,this.Id=g.getAttribute("y"),this.bd=g.getAttribute("x"),e=!0);if(0!=b.length&&!e)for(var h=0;h<b.length-1;){if(-1!=b[h].outerHTML.indexOf("docs-text-ui-cursor-blink")){e=!0;this.lb=b[h];this.Id=b[h].getAttribute("y");this.bd=
b[h].getAttribute("x");break}for(g=0;g<=c.childNodes.length-1;g++)c.childNodes[g].contains(this.lb)&&"none"==c.childNodes[g].style.display&&(this.bd=this.Id=this.lb=null);if(b[h].hasAttribute("fill")&&"#000"==b[h].getAttribute("fill")){e=!0;this.lb=b[h];this.Id=b[h].getAttribute("y");this.bd=b[h].getAttribute("x");break}h++}if(!e)for(h=0;h<d.length;h++){for(var l=d[h],m=l.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.getElementsByTagName("g"),b=0;b<m.length;b++){for(var n=
m[b].getElementsByTagName("path"),c=0;c<n.length;c++){var p=n[c];if(p.hasAttribute("stroke")&&"#000"!=p.getAttribute("stroke")){e=!0;this.lb=l;this.Id=l.getAttribute("y");this.bd=l.getAttribute("x");break}}if(e)break}if(e)break}a([]);return window.words}catch(q){z.S.a().b(q)}};
z.f.getSelection=function(a){try{this.Qf=a;var b=this.ge(),c='{ "doc":"'+window.location.href+'","startWordCount":"'+b.Oc+'", "startWord":"'+(0,window.escape)(b.Ya)+'", "endWordCount":"'+b.Bc+'", "endWord":"'+(0,window.escape)(b.$a)+'"}',c=z.od(c);window.postMessage({method:"getSelection",type:"1757FROM_PAGERW4G",payload:c},"*")}catch(d){z.S.a().b(d)}};
z.f.Zc=function(){try{Xk(this);var a=null,b=null,c=null,d=null;try{a:{for(var e=window.document.getElementById("pages").getElementsByTagName("image"),g=0;g<e.length;g++)for(var h=e[g],l=h.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.getElementsByTagName("g"),m=0;m<l.length;m++)for(var n=l[m].getElementsByTagName("path"),p=0;p<n.length;p++){var q=n[p];if(q.hasAttribute("stroke")&&"#000"!=q.getAttribute("stroke")){b=h;break a}}b=null}null==b&&(a=$k(this));1>a.textContent.length&&
(b=null);if(null!=a){var s=window.document.querySelectorAll('rect[fill\x3d"#000"]');0==s.length&&(s=window.document.querySelectorAll(".sketchy-text-selection-overlay"));for(var d=0!=s.length?this.lb.parentNode.parentNode.parentNode.getElementsByTagName("text"):this.lb.previousSibling.getElementsByTagName("text"),r=0;r<d.length;r++)if(d[r]==a){c=r;break}}else if(null!=b){if(this.nj=null,this.df=b,b.hasAttribute("spoken")&&(F=b.getAttribute("spoken"),""!=F))return window.lineOfWords=F.split(" ")}else{var w=
bl(),v=w[0].getElementsByTagName("text");0==v.length&&(window.console.log("Crivens! It's getSelectionOnly"),v=w[0]);this.nj=v;a=v[0];d=v;c=0}}catch(I){w=bl(),v=w[0].getElementsByTagName("text"),0==v.length&&(window.console.log("Crivens! It's getSelectionOnly"),v=w[0]),this.nj=v,a=v[0],d=v,c=0}var F="";if(-1==d[c].innerHTML.indexOf("tspan"))F=d[c].innerHTML;else{for(var A=a.getElementsByTagName("tspan"),N="",P=0;P<=A.length-1;P++)N+=A[P].innerHTML;F=N}this.$f=-1;a=null;b=!1;0<c&&d[c].parentNode.parentNode.parentNode.parentNode!=
d[c-1].parentNode.parentNode.parentNode.parentNode&&(b=!0);if(1!=b)for(r=c-1;-1<r;r--){var L="";if(-1==d[r].innerHTML.indexOf("tspan"))L=d[r].innerHTML;else{A=d[r].getElementsByTagName("tspan");N="";for(P=0;P<=A.length-1;P++)N+=A[P].innerHTML;L=N}if(-1==L.indexOf(".")&&-1==L.indexOf("!")&&-1==L.indexOf("?")){if(null!=a&&d[r].parentNode.parentNode.parentNode.parentNode!=a)break;F=L+" "+F;this.$f=r;a=d[r].parentNode.parentNode.parentNode.parentNode}else break}if(-1==this.$f||1==b)this.$f=c;a=null;b=
!1;d.length-1>=c&&(d.length-1==c?b=!0:d[c].parentNode.parentNode.parentNode.parentNode!=d[c+1].parentNode.parentNode.parentNode.parentNode&&(b=!0));L="";if(-1==d[c].innerHTML.indexOf("tspan"))L=d[c].innerHTML;else{A=d[c].getElementsByTagName("tspan");N="";for(P=0;P<=A.length-1;P++)N+=A[P].innerHTML;L=N}if(-1!=L.indexOf(".")||-1!=L.indexOf("!")||-1!=L.indexOf("?")||1==b)this.dh=c;else for(r=c+1;r<d.length&&(null==a||d[r].parentNode.parentNode.parentNode.parentNode==a);r++){L="";if(-1==d[r].innerHTML.indexOf("tspan"))L=
d[r].innerHTML;else{A=d[r].getElementsByTagName("tspan");N="";for(P=0;P<=A.length-1;P++)N+=A[P].innerHTML;L=N}F=F+" "+L;this.dh=r;a=d[r].parentNode.parentNode.parentNode.parentNode;if(-1!=L.indexOf(".")||-1!=L.indexOf("!")||-1!=L.indexOf("?"))break}return window.lineOfWords=F.split(" ")}catch(pa){z.S.a().b(pa)}};
z.f.getSelection=function(a){try{this.Qf=a;var b=this.ge(),c='{ "doc":"'+window.location.href+'","startWordCount":"'+b.Oc+'", "startWord":"'+(0,window.escape)(b.Ya)+'", "endWordCount":"'+b.Bc+'", "endWord":"'+(0,window.escape)(b.$a)+'"}',c=z.od(c);window.postMessage({method:"getSelection",type:"1757FROM_PAGERW4G",payload:c},"*")}catch(d){z.S.a().b(d)}};
z.f.Yc=function(a){try{var b=[],c=window.document.querySelectorAll('rect[fill\x3d"#000"]');0==c.length&&(c=window.document.querySelectorAll(".sketchy-text-selection-overlay"));if(0!=c.length)for(var d=0;d<c.length;d++)for(var e=c[d].parentNode.getElementsByTagName("text"),g=0;g<e.length;g++){var h=e[g].getBBox().x+1,l=(0,window.parseInt)(c[d].getAttribute("x")),m=e[g].getBBox().x+e[g].getBBox().width,n=(0,window.parseInt)(c[d].getAttribute("x"))+(0,window.parseInt)(c[d].getAttribute("width"));if(m>=
l&&m<=n||h>=l&&h<=n)if(-1==e[g].innerHTML.indexOf("tspan"))b.push(e[g].innerHTML);else{for(var p=e[g].getElementsByTagName("tspan"),q="",s=0;s<=p.length-1;s++)q+=p[s].innerHTML;b.push(q)}}else b=Zk(this);void 0!==a&&a(b);return b}catch(r){z.S.a().b(r)}};
z.f.zi=function(a){try{var b=[],c=window.document.querySelectorAll('rect[fill\x3d"#000"]');0==c.length&&(c=window.document.querySelectorAll(".sketchy-text-selection-overlay"));if(0!=c.length){for(var d=0;d<c.length;d++)for(var e=c[d].parentNode.getElementsByTagName("text"),g=0;g<e.length;g++){var h=e[g].getBBox().x+1,l=(0,window.parseInt)(c[d].getAttribute("x")),m=e[g].getBBox().x+e[g].getBBox().width,n=(0,window.parseInt)(c[d].getAttribute("x"))+(0,window.parseInt)(c[d].getAttribute("width"));if(m>=
l&&m<=n||h>=l&&h<=n)if(-1==e[g].innerHTML.indexOf("tspan"))b.push(e[g].innerHTML);else{for(var p=e[g].getElementsByTagName("tspan"),q="",s=0;s<=p.length-1;s++)q+=p[s].innerHTML;b.push(q)}}var r=b.join(" ").replace(/(\.+|\:|\!|\?)(\"*|\'*|\)*|}*|]*)(\s|\n|\r|\r\n)/gm,".\x3cbr /\x3e\x3cbr /\x3e$2").split("|"),w={documentTitle:window.document.title.replace(" - Google Slides",""),html:r.join(" ")}}else w={documentTitle:window.document.title,html:""};a(w)}catch(v){z.S.a().b(v)}};z.f.he=function(){try{return this.Zc()}catch(a){z.S.a().b(a)}};
z.f.xg=function(){};z.f.Rc=function(a,b,c,d){try{this.yg(a,b,c,d)}catch(e){z.S.a().b(e)}};
z.f.Gf=function(a,b,c){try{b=[];var d=window.document.getElementById("WACViewPanel");d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb"]');for(var e=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(255, 0, 255)"]')),g=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(255, 255, 0)"]')),h=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(0, 255, 0)"]')),l=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(0, 255, 255)"]')),
m=window.document.getElementById("WACViewPanel_EditingElement_WrappingDiv"),d=0,n="",d=0;d<e.length;++d)if(!m.contains(e[d].parentNode)){var p;p=e[d].nextSibling?e[d].nextSibling:e[d].parentNode.nextSibling;if("rgb(255, 0, 255)"===p.style.backgroundColor)n+=e[d].text;else{n+=e[d].text;if(0<n.length){var q;q=0>n.indexOf(" ")?n:n.substr(0,n.indexOf(" "));0>b.indexOf(q)&&b.push(q)}n=""}}d=0;e="";for(d=0;d<g.length;++d)m.contains(g[d].parentNode)||(p=g[d].nextSibling?g[d].nextSibling:g[d].parentNode.nextSibling,
"rgb(255, 255, 0)"===p.style.backgroundColor?e+=g[d].text:(e+=g[d].text,0<e.length&&(q=0>e.indexOf(" ")?e:e.substr(0,e.indexOf(" ")),0>b.indexOf(q)&&b.push(q)),e=""));d=0;g="";for(d=0;d<h.length;++d)m.contains(h[d].parentNode)||(p=h[d].nextSibling?h[d].nextSibling:h[d].parentNode.nextSibling,"rgb(0, 255, 0)"===p.style.backgroundColor?g+=h[d].text:(g+=h[d].text,0<g.length&&(q=0>g.indexOf(" ")?g:g.substr(0,g.indexOf(" ")),0>b.indexOf(q)&&b.push(q)),g=""));d=0;h="";for(d=0;d<l.length;++d)m.contains(l[d].parentNode)||
(p=l[d].nextSibling?l[d].nextSibling:l[d].parentNode.nextSibling,"rgb(0, 255, 255)"===p.style.backgroundColor?h+=l[d].text:(h+=l[d].text,0<h.length&&(q=0>h.indexOf(" ")?h:h.substr(0,h.indexOf(" ")),0>b.indexOf(q)&&b.push(q)),h=""));this.zg(a,b,c)}catch(s){z.S.a().b(s)}};z.f.Lg=function(){};
z.f.yb=function(a){try{var b=null,c=window.document.getElementById("TH-Word-highlight");null!=c&&c.remove();var d=window.document.getElementById("TH-Word-highlightFont");if(null!=d&&void 0!=d){if(-1==d.innerHTML.indexOf("tspan")){var e=d.getAttribute("style"),e=e.replace("fill:white","");d.setAttribute("style",e)}else for(var g=d.getElementsByTagName("tspan"),h=0;h<=g.length-1;h++)e=g[h].getAttribute("style"),e=e.replace("fill:white",""),g[h].setAttribute("style",e);d.removeAttribute("id")}b=this.jh;
if(null==b){var l=window.document.getElementsByClassName("thImageHighlightedSlides");0<l.length&&(this.df=l[0])}else if(void 0!=b[a]){var m=b[a].getAttribute("style"),n=b[a].getAttribute("x"),n=n.replace("px",""),n=(0,window.parseInt)(n),p=b[a].parentNode.parentNode.previousSibling.getBBox().height,c=-1*p,q=b[a].getBBox().width,s=window.document.createElement("g");s.setAttribute("class","sketchy-text-background-inner TH-Word-HighlightTest");s.setAttribute("transform","translate(0 "+p+")");var r=window.document.createElement("rect");
r.setAttribute("x",n);r.setAttribute("y",c);r.setAttribute("width",1);r.setAttribute("height",p);r.setAttribute("fill","#ffff00");r.setAttribute("fill-opacity","1");s.appendChild(r);b[a].parentNode.parentNode.previousSibling.appendChild(s);var w=b[a].parentNode.parentNode.previousSibling;w.innerHTML+=" ";for(var v=window.document.getElementsByClassName("sketchy-text-background-inner TH-Word-HighlightTest"),s=0;0<v.length&&5E3>s;)v[v.length-1].remove(),s++;if(-1==b[a].innerHTML.indexOf("tspan"))b[a].setAttribute("style",
m+";fill:white");else for(g=b[a].getElementsByTagName("tspan"),h=0;h<=g.length-1;h++)m=g[h].getAttribute("style"),g[h].setAttribute("style",m+";fill:white");b[a].setAttribute("id","TH-Word-highlightFont");var I=window.document.createElement("g");I.setAttribute("class","sketchy-text-background-inner");I.setAttribute("id","TH-Word-highlight");I.setAttribute("transform","translate(0 "+p+")");window.colorRectEl=window.document.createElement("rect");window.colorRectEl.setAttribute("x",n);window.colorRectEl.setAttribute("y",
c);window.colorRectEl.setAttribute("width",q);window.colorRectEl.setAttribute("height",p);window.colorRectEl.setAttribute("fill","#0000ff");window.colorRectEl.setAttribute("fill-opacity","1");window.colorRectEl.setAttribute("rx","2");window.colorRectEl.setAttribute("ry","2");I.appendChild(window.colorRectEl);b[a].parentNode.parentNode.previousSibling.appendChild(I);w=b[a].parentNode.parentNode.previousSibling;w.innerHTML+=" ";this.df=b[a]}}catch(F){z.S.a().b(F)}};
z.f.stop=function(){try{this.na(),cl()}catch(a){z.S.a().b(a)}};
z.f.le=function(a,b){try{if(this.yh)return cl(),b(null),null;var c=z.V.a().O().speechoptions.continousreading;if(a&&!c)cl(),b(null);else{window.postMessage({command:"GBooksSelection",type:"1757FROM_PAGERW4G",speech:"nextSentence",highlightWordIndex:-1},"*");for(var d=bl(),c="",e=[],g=0,h=null,l=null,m=null,n=0;n<=d.length-1;n++)if("image"==d[n].nodeName){if(d[n]==this.df){m=d[n+1];break}}else if(1==d[n].contains(this.df)){var p=d[n].getElementsByTagName("text"),m=this.df==p[p.length-1]?d[n+1]:d[n];
break}d=[];if(void 0!=m){d="image"==m.nodeName?m:m.getElementsByTagName("text");if("image"!=d.nodeName){for(n=l=0;n<=d.length-1;n++)if(this.df==d[n]){l=n;l++;break}for(n=l;n<=d.length-1&&(null==h||d[n].parentNode.parentNode.parentNode.parentNode==h);n++){l="";if(-1==d[n].innerHTML.indexOf("tspan"))l=d[n].innerHTML;else{for(var q=d[n].getElementsByTagName("tspan"),m="",p=0;p<=q.length-1;p++)m+=q[p].innerHTML;l=m}c=""==c?l:c+" "+l;e[g]=d[n];g++;h=d[n].parentNode.parentNode.parentNode.parentNode;if(-1!=
l.indexOf(".")||-1!=l.indexOf("!")||-1!=l.indexOf("?"))break}al(this,e)}else if(d.hasAttribute("spoken")){c=d.getAttribute("spoken");if(""==c){cl();b(null);return}q=d;try{cl(),dl(q,!0),this.jh=null}catch(s){window.console.log(s)}}else{cl();b(null);return}b(c.split(" "))}else cl(),b(null)}}catch(r){z.S.a().b(r)}};
z.f.na=function(){try{for(var a=window.document.getElementsByClassName("sketchy-text-background-inner TH-Word-BackHighlight"),b=0;0<a.length&&5E3>b;)a[a.length-1].remove(),b++;var c=window.document.getElementById("TH-Word-highlight");null!=c&&c.remove();var d=window.document.getElementById("TH-Word-highlightFont");if(null!=d){var e=d.getAttribute("style"),e=e.replace("fill:white","");d.setAttribute("style",e);d.removeAttribute("id")}this.jh=null}catch(g){z.S.a().b(g)}};
z.f.oi=function(a,b){try{var c=window.document.createEvent("MouseEvents");c.initMouseEvent.apply(c,b);a.dispatchEvent(c)}catch(d){z.S.a().b(d)}};
z.f.Pd=function(a){try{if(void 0!=a.source&&void 0!=a.data&&a.source==window)if("1757FROM_BGRW4G"==a.data.type)if("onGetSelection"==a.data.method){var b=z.od(a.data.payload);this.Qf(b)}else if("GBooksSelectionReturn"===a.data.method&&(0,window.alert)(a.data.fu),"onCollectHighlights"==a.data.method){var c=z.od(a.data.payload);if("string"===typeof c){var d=null,e=z.S.a().Wc(),d=window.open(c,"_ntthch"+e);d.focus();this.lc(c)}else 0==c[0].highlights.length?this.lc("false"):this.lc("true")}else{if("onVocabWords"==
a.data.method){var g=z.od(a.data.payload);"string"===typeof g&&(d=null,e=z.S.a().Wc(),d=window.open(g,"_ntthchVc"+e),d.focus(),this.il(g))}}else if(a.data&&"EQUATIO_MATHJAX_RESPOND_SPOKEN_TEXT"===a.data.type)try{for(b=0;b<this.al.length;b++){var h=this.al[b];try{if(h.J==a.data.id){this.al.splice(b,1);h.setAttribute("spoken",a.data.text);break}}catch(l){}}}catch(m){}}catch(n){z.S.a().b(n)}};z.f.yg=function(a){try{this.lc=a,z.S.a().Wc()}catch(b){z.S.a().b(b)}};z.Rk=!0;z.f=$.prototype;
z.f.zg=function(a,b,c){try{var d=[];this.il=a;var e=z.S.a().Wc();c=c+" "+e;var g=new window.XMLHttpRequest;a="https://webservices-us.texthelp.com/v1.11.0/vocab?json\x3d{%22u%22:%22RWOfficeApps%22,%22e%22:%229yvydZ1FQn%22,%22b%22:";for(var e="",h=0;h<b.length;h++)e=h===b.length-1?e+"%22"+b[h]+"%22]}":0===h?e+"[%22"+b[h]+"%22,":e+"%22"+b[h]+"%22,";g.open("POST",a+e);g.setRequestHeader("Accept","application/json;odata\x3dverbose");g.onreadystatechange=function(){var a="";if(4==this.readyState&&200==
this.status&&(a=this.getResponseHeader("Content-Type"),"application/json"==a.substr(0,16))){for(var a=JSON.parse(this.response).Cu,b,e=0;e<a.length;e++)for(var g=a[e].Wt,h=0;h<g.length;h++){b=g[h].tu;for(var l=0;l<b.length;l++)d.push(b[l])}for(a=0;a<d.length;a++)z.Qk(d[a],z.Tk,d.length,c)}};g.send()}catch(l){z.S.a().b(l)}};z.f.Lj=function(a,b){try{var c=z.Ij(a,this.h),d=z.Ij(b,this.h);if(c.y>d.y)return 1;if(c.y<d.y)return-1;if(c.y===d.y){if(c.x<d.x)return-1;if(c.x>d.x)return 1}return 0}catch(e){z.S.a().b(e)}};
z.f.Ba=function(){try{return{x:this.Xf.x,y:this.Xf.y-90}}catch(a){z.S.a().b(a)}};z.f.jd=function(){try{this.ma.ua("CTRL+Shift+S",1,"keydown"),this.ma.ua("CMD+Shift+S",1,"keydown")}catch(a){z.S.a().b(a)}};z.f.kd=function(){};z.u("textHelp.parsers",z.Yj);z.u("textHelp.parsers.GoogleSlidesParser",$);$.prototype.hiliteNextSentence=$.prototype.le;$.prototype.hiliteWord=$.prototype.yb;$.prototype.highlightSelection=$.prototype.$c;$.prototype.getUserSettings=$.prototype.O;$.prototype.getCaretPosition=$.prototype.rp;
$.prototype.getSelection=$.prototype.getSelection;$.prototype.getSelectionLocal=$.prototype.Yc;$.prototype.clearHighlights=$.prototype.vc;$.prototype.getTextWithContext=$.prototype.Lg;$.prototype.getParserName=$.prototype.Xb;$.prototype.getBarConfigFromParser=$.prototype.Vb;$.prototype.getPredictionPosition=$.prototype.Ba;$.prototype.startSpeechRecognition=$.prototype.jd;$.prototype.stopSpeechRecognition=$.prototype.kd;z.Kf("GoogleSlidesParser");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_GoogleSlidesParser.js