(function(z){
z.Gj=function(a,b){var c=a.style[z.Oa(b)];return"undefined"!==typeof c?c:a.style[z.Xf(a,b)]||""};var Hj=function(a){if(1==a.nodeType)return z.hg(a);var b=z.la(a.Gm),c=a;a.targetTouches&&a.targetTouches.length?c=a.targetTouches[0]:b&&a.Xa.targetTouches&&a.Xa.targetTouches.length&&(c=a.Xa.targetTouches[0]);return new z.H(c.clientX,c.clientY)};z.Ij=function(a,b){var c=Hj(a),d=Hj(b);return new z.H(c.x-d.x,c.y-d.y)};
z.X=function(a,b){var c=b||window.document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):z.ie(window.document,"*",a,b)};z.W=function(){try{this.Ld=new Jj,null==z.J("thSpeechStreamTBPlaceHolder")&&(this.r=new Kj),this.qe=null}catch(a){z.S.a().b(a)}};var Lj=function(a){try{if(null===a.r.q())throw Error("Could not get a reference to the current parser.");a.r.q().stop();a.Ld.stop()}catch(b){z.S.a().b(b)}};z.Mj=function(){};
z.T=function(){this.Be={};this.Do=[];this.Rl=[];this.ef=z.S.a().bind(this,this.Pd);window.addEventListener("message",this.ef,!1)};z.S=function(){this.Io="thWebReaderPlaceHolder";this.vn=this.Gd=null;this.cn=!1;this.qn=this.cd=null;this.xn="";this.yn=!1};z.Nj=function(a,b){for(var c=a.length;c--;)if(a[c]===b)return!0;return!1};z.Oj=function(a,b){function c(a){if(3==a.nodeType)d.push(a);else for(var b=0,h=a.childNodes.length;b<h;++b)c(a.childNodes[b])}var d=[];c(b);return d};
z.Pj=function(){var a=z.S.a();try{return a.yn}catch(b){z.S.a().b(b)}};
var Kj=function(){try{this.Ha=null;var a=!1,b=z.gj.a().Ib().highlighterSiteMap,c;for(c in b){if("default"==c)break;var d=window.location.toString().substring(0,c.length);if(d===c){this.Ha=b[c];var e=z.Bf.a();z.Of(e,b[c].parser,this.tl,this);a=!0}else{var d=window.location.toString(),g=c.split("*");if(1<g.length){var h=!0,l;for(l in g){var m=d.indexOf(g[l]);if(-1==m){h=!1;break}d=d.substr(m+g[l].length)}h&&(d=window.location.toString(),this.Ha=b[c],e=z.Bf.a(),z.Of(e,b[c].parser,this.tl,this),a=!0)}}}!1===
a&&(this.Ha=b["default"],e=z.Bf.a(),z.Of(e,b["default"].parser,this.tl,this))}catch(n){z.S.a().b(n)}};z.Qj=function(){this.ln="ScanSoft Emily_Full_22kHz"};var Rj=function(){try{throw Error("Not implemented");}catch(a){z.S.a().b(a)}};var Jj=function(){try{this.Yf=[],this.eh=!1,this.cc=[],this.dd=[]}catch(a){z.S.a().b(a)}};
var Sj=function(){try{this.mn=[],this.W=this.Cn=this.Bn=null,this.cj=-1,this.$i=this.Nb=null,this.hh=this.fl=!1,this.cd=null,this.gn=z.gj.a().Ib().charMap,z.T.a().j("onVoices",this.Xn,this)}catch(a){z.S.a().b(a)}};var Tj=function(a,b){try{for(var c="",d="",e=0;e<b.length;e++)d=b.charCodeAt(e).toString(),c=void 0===a.gn[d]?c+b.charAt(e):c+a.gn[d];return c}catch(g){z.S.a().b(g)}};var Uj=function(){try{this.Fc=null,this.ej=!1,this.Wk=null,this.eh=!1}catch(a){z.S.a().b(a)}};
z.hj=function(a,b,c,d,e){try{this.path=b;this.Au=c;this.Mn;this.qm;this.$n;this.filename;this.speed=e;(0,window.decodeURIComponent)(d)===d&&(d=(0,window.encodeURIComponent)(d));this.Bu=d;try{"/"!=a.charAt(a.length-1)&&(a+="/"),"/"!=b.charAt(b.length-1)&&(b+="/")}catch(g){}this.Ro=a+b+"?userName\x3d"+c+"\x26voiceName\x3d"+d+"\x26speedValue\x3d"+e}catch(h){window.console.log(h)}};
var Vj=function(a,b,c){return new window.Promise(function(d,e){var g=new window.XMLHttpRequest;c=(0,window.encodeURIComponent)(c);var h="filename\x3d"+b+"\x26text\x3d"+c;g.open("POST",a);g.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset\x3dUTF-8");g.send(h);g.onload=function(){if(200==this.status){var a=JSON.parse(this.response);null==a?e(Error("Mp3 Request response is empty.")):d(a)}else e(Error(this.statusText))};g.onerror=function(){e(Error("Error converting text.\r\n"+
g.statusText))}})};var Wj=function(a,b){window.console.log("statusChecker - "+b);var c=Xj(b);try{c.then(function(c){window.console.log("File Status: "+c);100==c?a.qm(a.Mn):(a.$n(Math.round(c)),(0,window.setTimeout)(function(){try{Wj(a,b)}catch(c){a.mk(c)}},1E3))},function(b){a.mk(Error("StatusFile Error: "+b.message))})}catch(d){a.mk(d)}};
var Xj=function(a){return new window.Promise(function(b,c){var d=new window.XMLHttpRequest;window.console.log("requestStatusFile - "+a);d.open("GET",a,!0);d.send();d.onload=function(){if(200==this.status){var a=JSON.parse(this.response);window.console.log(a);null==a?c(Error("Response is empty.")):""!=a.error&&" "!=a.error?c(Error(a.error)):b(a.progress)}else window.console.log("Error - "+this.status),c(Error(this.statusText))};d.onerror=function(){window.console.log("Error - "+this.status);c(Error("Error converting text.\r\n"+
d.statusText))}})};z.Sf.prototype.Xb=z.ca(8,function(){try{if(null===this.A)throw Error("The WebReaderAPI has not been created");return this.A.Xb()}catch(a){z.S.a().b(a)}});z.Sf.prototype.Pi=z.ca(7,function(){try{if(null===this.A)throw Error("The WebReaderAPI has not been created");return this.A.Pi()}catch(a){z.S.a().b(a)}});z.Sf.prototype.Pd=z.ca(2,function(){});z.$b.prototype.Gm=z.ca(0,function(){return this.Xa});z.Yj={};
z.jb(function(a,b){this.type=a;this.currentTarget=this.target=b;this.An=null;this.Zf=0;this.kh=!1}.prototype,z.Xb.prototype);z.f=z.W.prototype;z.f.Sa=function(){try{this.Ld.Sa();var a=z.J(z.S.a().Jf());null!==a&&"true"!==a.installed&&(window.document.documentElement.setAttribute("xmlns:thRWGDns",""),a.setAttribute("installed","true"),z.T.a().j("onthAPIWord",this.Zr,this),z.T.a().j("onthAPIStop",this.xr,this),this.An=new Uj)}catch(b){z.S.a().b(b)}};
z.f.sc=function(a,b){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().sc(a,b)}catch(c){z.S.a().b(c)}};
z.f.Xd=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");Lj(this);z.S.a();this.qe=this.r.q().Pg();if(null===this.qe)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else if(0===this.qe.length)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else this.Ld.Xd(this.qe,1),window.texthelp.RW4GC.thToolbarStoreInstance.onSpeech()}catch(a){z.S.a().b(a)}};z.f.no=function(a){try{Lj(this),this.kh=!0,this.Ld.Xd(a,1,!1)}catch(b){z.S.a().b(b)}};
z.f.stop=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().stop();this.Ld.stop()}catch(a){z.S.a().b(a)}};z.f.Tn=function(a){this.qe=a;if(null===this.qe)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else if(0===this.qe.length)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else this.Ld.Xd(this.qe,1)};
z.f.forward=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().stop();this.Ld.stop();this.kh?this.kh=!1:this.r.q().le(!1,this.Tn.bind(this))}catch(a){z.S.a().b(a)}};z.f.Ns=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");}catch(a){z.S.a().b(a)}};z.f.pause=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.Ld.pause()}catch(a){z.S.a().b(a)}};
z.f.lp=function(a){0!==a.length&&(this.r.q().na(),100<a.length&&(a.length=100),window.open("http://google.com/search?q\x3d"+(0,window.encodeURIComponent)(a.join(" "))))};z.f.kp=function(){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");var a=null;this.r.q().Lf()?this.r.q().Yc(this.lp.bind(this)):(a=this.r.q().xb(),0!==a.length&&(this.r.q().na(),window.open("http://google.com/search?q\x3d"+(0,window.encodeURIComponent)(a.join(" ")))))}catch(b){z.S.a().b(b)}};
z.f.Ss=function(){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().Ts()}catch(a){z.S.a().b(a)}};z.f.Ws=function(a){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().Lf()&&this.r.q().Yc(a)}catch(b){z.S.a().b(b)}};z.f.Es=function(a){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().zi(a)}catch(b){z.S.a().b(b)}};
z.f.Ni=function(a){try{this.stop();if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().Ni(a)}catch(b){z.S.a().b(b)}};z.f.Rc=function(a,b,c,d){try{this.stop();if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().Rc(a,b,c,d)}catch(e){z.S.a().b(e)}};z.f.Gf=function(a,b,c){try{this.stop();if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().Gf(a,b,c)}catch(d){z.S.a().b(d)}};
z.f.Kb=function(a){try{return void 0==a&&(a=!1),this.Ld.Kb(a)}catch(b){z.S.a().b(b)}};z.f.Zr=function(a){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");"start"!==a[0]&&this.r.q().yb(a[0])}catch(b){z.S.a().b(b)}};z.f.xr=function(){try{this.r.q().stop(),this.kh?this.kh=!1:this.r.q().le(!0,this.Tn.bind(this))}catch(a){this.r.q().xg(),window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped(),z.S.a().b(a)}};
z.f.Wj=function(){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().$c("#FFFF00")}catch(a){z.S.a().b(a)}};z.f.Yh=function(){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().$c("#00FFFF")}catch(a){z.S.a().b(a)}};z.f.Ci=function(){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().$c("#ADFF2F")}catch(a){z.S.a().b(a)}};
z.f.xj=function(){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().$c("#FF00FF")}catch(a){z.S.a().b(a)}};z.f.vc=function(){try{Lj(this);if(null===this.r.q())throw Error("Could not get a reference to the current parser.");this.r.q().vc()}catch(a){z.S.a().b(a)}};z.f.wp=function(){try{return z.S.a().Kg()}catch(a){z.S.a().b(a)}};z.f.xp=function(){try{return z.S.a().Gd.Kb()}catch(a){z.S.a().b(a)}};z.f.jd=function(){try{Lj(this),this.r.q().jd()}catch(a){z.S.a().b(a)}};
z.f.kd=function(){try{Lj(this),this.r.q().kd()}catch(a){z.S.a().b(a)}};z.f.Pi=function(){try{return this.An.isEnabled()}catch(a){z.S.a().b(a)}};z.f.xb=function(){try{var a=this.r.q().xb();return 0===a.length?"":3>a.length?a.join(" "):a[0]}catch(b){z.S.a().b(b)}};z.f.Xb=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");return this.r.q().Xb()}catch(a){z.S.a().b(a)}};
z.f.Vb=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");return this.r.q().Vb()}catch(a){z.S.a().b(a)}};z.f.Ba=function(){try{if(null===this.r.q())throw Error("Could not get a reference to the current parser.");return this.r.q().Ba()}catch(a){z.S.a().b(a)}};z.u("textHelp.webreaderapi.WebReaderAPI",z.W);z.W.prototype.initialise=z.W.prototype.Sa;z.W.prototype.addVoiceNote=z.W.prototype.sc;z.W.prototype.speakSelection=z.W.prototype.Xd;
z.W.prototype.speakWord=z.W.prototype.no;z.W.prototype.stop=z.W.prototype.stop;z.W.prototype.getVoices=z.W.prototype.Kb;z.W.prototype.yellowHighlighter=z.W.prototype.Wj;z.W.prototype.getStaticOptionsDialog=z.W.prototype.wp;z.W.prototype.getStaticVoices=z.W.prototype.xp;z.W.prototype.startSpeechRecognition=z.W.prototype.jd;z.W.prototype.stopSpeechRecognition=z.W.prototype.kd;z.W.prototype.isSpeechRecognitionRunning=z.W.prototype.Pi;z.W.prototype.getWord=z.W.prototype.xb;
z.W.prototype.getParserName=z.W.prototype.Xb;z.W.prototype.getBarConfigFromParser=z.W.prototype.Vb;z.W.prototype.getPredictionPosition=z.W.prototype.Ba;z.f=z.Mj.prototype;z.f.Pg=function(){throw Error("Not implemented");};z.f.Lf=function(){throw Error("Not implemented");};z.f.xb=function(){throw Error("Not implemented");};z.f.getSelection=function(){throw Error("Not implemented");};z.f.yb=function(){throw Error("Not implemented");};z.f.xg=function(){throw Error("Not implemented");};z.f.Rc=function(){throw Error("Not implemented");};z.f.sc=function(){throw Error("Not implemented");};z.f.stop=function(){throw Error("Not implemented");};
z.f.da=function(a,b){z.S.a().da(a,b)};z.f.sa=function(a,b){z.S.a().sa(a,b)};z.f.P=function(a,b){return z.S.a().P(a,b)};z.f.Uc=function(a){return z.S.a().Uc(a)};z.f.qd=function(a,b,c){z.S.a().qd(a,b,c)};z.ga(z.T);z.f=z.T.prototype;
z.f.Pd=function(a){try{if(void 0!=a.source&&void 0!=a.data&&a.source==window&&"1757FROM_BGRW4G"==a.data.type){"thSetVisibility"==a.data.method&&z.T.a().u("onBarVisibilityChanged",a.data.visibility);"trialValidation"==a.data.method&&(z.S.a().Ch(a.data.payload),z.T.a().u("onLicenseReceived",a.data.payload));"thPrediction"==a.data.method&&z.T.a().u("onPredictionChanged",a.data.payload);"onGetthRWFGSettings"==a.data.method&&z.T.a().u("onGetSettingsChanged",a.data.payload);"onthRWFGPopup"==a.data.method&&
z.T.a().u("onMessagePopup",a.data.payload);"thGetVoices"==a.data.method&&z.T.a().u("onVoices",a.data.payload);"onCommand"==a.data.method&&(0,window.alert)(a.data.payload);if("onGetOAuthToken"==a.data.method){var b=[];null!=a.data.payload&&(b=a.data.payload,z.S.a().Ch(a.data.payload));z.T.a().u("onGetOAuthToken",b)}"onAddVoiceNoteToken"==a.data.method&&z.T.a().u("onAddVoiceNoteToken",a.data.parameters.token);"onGetOAuthTokenSilent"==a.data.method&&(b=[],null!=a.data.payload&&(b=a.data.payload,z.S.a().Ch(a.data.payload)),
z.T.a().u("onGetOAuthTokenSilent",b));"onCollectHighlightsWeb"==a.data.method&&z.T.a().u("onCollectHighlightsWeb",a.data.payload);"onVocabWeb"==a.data.method&&z.T.a().u("onVocabWeb",a.data.payload);"onAuthenticate"==a.data.method&&z.T.a().u("onAuthenticate",a.data.payload);"onGetLocaleDate"==a.data.method&&z.T.a().u("onGetLocaleDate",a.data.payload);"onGetLinks"==a.data.method&&z.T.a().u("onGetLinks",a.data.payload);"onRefreshLicense"==a.data.method&&z.T.a().u("onRefreshLicense",a.data.payload)}}catch(c){z.S.a().b(c)}};
z.f.j=function(a,b,c){try{if("string"!==typeof a)throw Error("textHelp.webreaderapi.EventBusSingleton.subscribe's  first parameter 'eventName' should be a string");if("function"!==typeof b)throw Error("textHelp.webreaderapi.EventBusSingleton.subscribe's  first parameter 'callback' should be a function");this.Be[a]||(this.Be[a]=[]);var d=b;null!==c&&(d=z.S.a().bind(c,b));this.Be[a].push(d);this.Zs={jp:a,Vo:this.Be[a].length-1};var e=this.Rl.length;this.Co={};this.Rl[e]=this.Zs;return this.Do[e]=this.Co}catch(g){z.S.a().b(g)}};
z.f.u=function(a,b){try{if("string"!==typeof a)throw Error("textHelp.webreaderapi.EventBusSingleton.publish's first parameter 'eventName' should be a string");if(!b)throw Error("textHelp.webreaderapi.EventBusSingleton.publish requires a second argument 'data'");var c,d;if(this.Be[a])for(c=0;c<this.Be[a].length;c++)(d=this.Be[a][c])&&d(b)}catch(e){z.S.a().b(e)}};z.f.zf=function(a){try{var b=this.Rl[this.Do.indexOf(a)];this.Be[b.jp][b.Vo]=null}catch(c){z.S.a().b(c)}};z.f.Jb=function(){try{return this.a()}catch(a){z.S.a().b(a)}};
z.u("textHelp.webreaderapi.EventBusSingleton",z.T);z.T.prototype.unsubscribe=z.T.prototype.zf;z.T.prototype.subscribe=z.T.prototype.j;z.T.prototype.publish=z.T.prototype.u;z.T.getInst=z.T.prototype.Jb;z.ga(z.S);z.f=z.S.prototype;z.f.Jb=function(){return z.S.a()};z.f.Yp=function(){try{return this.cn}catch(a){z.S.a().b(a)}};z.f.sp=function(){try{var a=this.qa();return null==a?null:a.split("@")[1]}catch(b){z.S.a().b(b)}};z.f.Kh=function(a){try{return Object.keys(a).toString()===Object.keys([]).toString()?0:Object.keys(a).length}catch(b){return z.S.a().b(b),0}};
z.f.Ms=function(a,b){try{void 0==b?window.thPostMessage({type:"1757FROM_PAGERW4G",method:"trialValidation",user:a},"*"):window.thPostMessage({type:"1757FROM_PAGERW4G",method:"trialValidation",user:a,screenScraped:b},"*")}catch(c){z.S.a().b(c)}};z.f.Jf=function(){try{return this.Io}catch(a){z.S.a().b(a)}};z.f.Ch=function(a){try{for(var b in a.pfs)a.features.hasOwnProperty(b)&&0==a.pfs[b]&&(a.features[b]=!1);this.cd=a;this.qn=a.features}catch(c){z.S.a().b(c)}};z.f.Ra=function(){try{return this.cd}catch(a){z.S.a().b(a)}};
z.f.Wb=function(){try{return this.qn}catch(a){z.S.a().b(a)}};z.f.Qe=function(){try{var a=z.J("thSpeechStreamTBPlaceHolder");if(null!==a)return z.J("thSpeechStreamTBPlaceHolder").getAttribute("data-root");a=z.J("thWebReaderPlaceHolder");return null!==a?z.J("thWebReaderPlaceHolder").getAttribute("data-root"):null}catch(b){z.S.a().b(b)}};
z.f.yd=function(){try{var a=z.J("webReaderModule").getAttribute("lang");null==a&&(a=z.J("thSpeechStreamTBPlaceHolder").getAttribute("lang"));var b=z.gj.a().Ib();"undefined"!==typeof b[a]&&(b.locale=a);return b.locale}catch(c){z.S.a().b(c)}};z.f.Wc=function(){try{return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a,c){return c=16*Math.random(),("y"==a?c&3|8:c|0).toString(16)})}catch(a){z.S.a().b(a)}};z.f.Pj=function(a){return Array.prototype.slice.call(a)};
z.f.bind=function(a,b){return function(){return b.apply(a,z.S.a().Pj(arguments))}};z.f.b=function(a){window.console.error(a.stack)};
z.f.da=function(a,b){try{if("string"==typeof a&&(a=z.J(a)),a){var c=a.className;if(c&&0<c.length){var d=b.split(" ");if(1===d.length&&-1===(" "+c+" ").lastIndexOf(" "+b+" "))a.className=a.className+" "+b;else{for(var e=c.split(" "),g=d.length,h,c=[],l=0;l<g;l++)h=d[l],-1===e.indexOf(h)&&c.push(h);a.className=a.className+" "+(1<c.length?c.join(" "):c[0])}}else a.className=b}}catch(m){z.S.a().b(m)}};
z.f.sa=function(a,b){try{if("string"==typeof a&&(a=z.J(a)),a){var c=a.className;if(c&&0<c.length){for(var d=c.split(" "),e=b.split(" "),g=d.length,h,c=[],l=0;l<g;l++)h=d[l],-1===e.indexOf(h)&&c.push(h);switch(!0){case 1<c.length:a.className=c.join(" ");break;case 1==c.length:a.className=c[0];break;case 0==c.length:a.className=""}}}}catch(m){z.S.a().b(m)}};
z.f.P=function(a,b){try{if(null===a||void 0==a)return!1;if(a.className)for(var c=a.className.split(" "),d=b.toUpperCase(),e=0;e<c.length;e++)if(c[e].toUpperCase()==d)return!0;return!1}catch(g){z.S.a().b(g)}};z.f.Uc=function(a){try{if(null===a)return!1;var b=[];a.className&&(b=a.className.split(" "));return b}catch(c){z.S.a().b(c)}};z.f.qd=function(a,b,c){try{this.sa(a,b.toString()),this.da(a,c.toString())}catch(d){z.S.a().b(d)}};z.f.trim=function(a){return a.replace(/^\s*([\S\s]*?)\s*$/,"$1")};
z.f.ht=function(a){var b=/\w/i,c=a.match(b),c=a.indexOf(c);0<c&&(a=a.substring(c).replace(/[\u200B]/g,""));a=a.split("").reverse().join("");c=a.match(b);c=a.indexOf(c);0<c&&(a=a.substring(c));return a.split("").reverse().join("")};z.f.pp=function(){return this.Gd};z.f.io=function(a){this.Gd=a};z.f.ko=function(a){this.vn=a};z.f.Kg=function(){return this.vn};z.f.Fh=function(a){try{this.xn=a}catch(b){z.S.a().b(b)}};z.f.vp=function(){try{return this.xn}catch(a){z.S.a().b(a)}};
z.f.hp=function(a){try{return a=a.replace(/\u2019/g,"'"),(0,window.encodeURIComponent)(a).replace(/\-/g,"%2D").replace(/\_/g,"%5F").replace(/\./g,"%2E").replace(/\!/g,"%21").replace(/\~/g,"%7E").replace(/\*/g,"%2A").replace(/\'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29")}catch(b){z.S.a().b(b)}};
z.f.dp=function(a){try{return(0,window.decodeURIComponent)(a.replace(/\%2D/g,"-").replace(/\%5F/g,"_").replace(/\%2E/g,".").replace(/\%21/g,"!").replace(/\%7E/g,"~").replace(/\%2A/g,"*").replace(/\%27/g,"'").replace(/\%28/g,"(").replace(/\%29/g,")"))}catch(b){z.S.a().b(b)}};z.f.Jo=function(a){try{var b=window.document.createElement("div");b.appendChild(window.document.createTextNode(a));return b.innerHTML}catch(c){z.S.a().b(c)}};
z.f.og=function(a){try{return a.replace(/[\\]/g,"\\\\").replace(/[\/]/g,"\\/").replace(/[\b]/g,"\\b").replace(/[\f]/g,"\\f").replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r").replace(/[\t]/g,"\\t").replace(/[\"]/g,'\\"').replace(/\\'/g,"\\'")}catch(b){z.S.a().b(b)}};z.f.Oa=function(a,b){try{var c=z.S.a().Ra();return void 0!==c.lt?!0:z.S.a().Wb()[a]?!0:(null!==c.upgrade_link&&b&&window.open(c.upgrade_link,"_exthtb").focus(),!1)}catch(d){z.S.a().b(d)}};z.f.Jj=function(a){try{this.yn=a}catch(b){z.S.a().b(b)}};
z.f.Jb=function(){try{return this.a()}catch(a){z.S.a().b(a)}};z.f.qa=function(){try{return null==this.cd?null:this.cd.Email}catch(a){z.S.a().b(a)}};
z.f.fireEvent=function(a,b){var c;if(a.ownerDocument)c=a.ownerDocument;else if(9==a.nodeType)c=a;else throw Error("Invalid node passed to fireEvent: "+a.id);if(a.dispatchEvent){var d="";switch(b){case "click":case "mousedown":case "mouseup":d="MouseEvents";break;case "focus":case "change":case "blur":case "select":d="HTMLEvents";break;default:throw"fireEvent: Couldn't find an event class for event '"+b+"'.";}c=c.createEvent(d);c.initEvent(b,"change"==b?!1:!0,!0);c.$s=!0;a.dispatchEvent(c,!0)}else a.fireEvent&&
(c=c.createEventObject(),c.$s=!0,a.fireEvent("on"+b,c))};z.f.gt=function(a,b){b=b.replace(/[\[\](){}?*+\^$\\.|\-]/g,"\\$\x26");return a.replace(new RegExp("^["+b+"]+|["+b+"]+$","g"),"")};z.f.Um=function(a){var b=a.getBoundingClientRect().top;a=a.getBoundingClientRect().bottom;return 0<=b&&a<=window.innerHeight};
z.f.vo=function(a){return"en_US"==a||"en-US"==a||"ENGLISH_US"==a?"en-US":"en-GB"==a||"en_GB"==a||"ENGLISH_GB"==a?"en-GB":"FRENCH"==a||"fr"==a||"FRAN\ufffdAIS"==a?"fr":"fr-CA"==a||"fr_CA"==a?"fr-CA":"PORTUGUESE"==a||"pt"==a?"pt":"PORTUGU\ufffdS (BRASILEIRA)"==a||"pt-BR"==a||"pt_BR"==a?"pt-BR":"MALAYSIAN"==a||"ms"==a?"ms":"SPANISH"==a||"es"==a||"ESPA\ufffdOL"==a?"es":"nl"};z.f.If=z.aa(18);z.u("textHelp.webreaderapi.HelpersSingleton",z.S);z.S.prototype.isAuthenticated=z.S.prototype.Yp;
z.S.prototype.getPlaceHolder=z.S.prototype.Jf;z.S.prototype.getRootLocation=z.S.prototype.Qe;z.S.prototype.setPredictionVisible=z.S.prototype.Jj;z.S.prototype.getGuid=z.S.prototype.Wc;z.S.prototype.logError=z.S.prototype.b;z.S.prototype.toArray=z.S.prototype.Pj;z.S.prototype.bind=z.S.prototype.bind;z.S.prototype.addClassName=z.S.prototype.da;z.S.prototype.removeClassName=z.S.prototype.sa;z.S.prototype.hasClassName=z.S.prototype.P;z.S.prototype.getClassName=z.S.prototype.Rt;
z.S.prototype.changeClassName=z.S.prototype.qd;z.S.prototype.trim=z.S.prototype.trim;z.S.prototype.trimPunctuation=z.S.prototype.ht;z.S.prototype.trimChars=z.S.prototype.gt;z.S.prototype.getAPI=z.S.prototype.pp;z.S.prototype.setAPI=z.S.prototype.io;z.S.prototype.getOptionsDialog=z.S.prototype.Kg;z.S.prototype.setOptionsDialog=z.S.prototype.ko;z.S.prototype.getLicense=z.S.prototype.Ra;z.S.prototype.setLicense=z.S.prototype.Ch;z.S.prototype.getFeatures=z.S.prototype.Wb;
z.S.prototype.retrieveLicense=z.S.prototype.Ms;z.S.prototype.CheckLicense=z.S.prototype.Oa;z.S.prototype.setPredictionSequence=z.S.prototype.Fh;z.S.prototype.getPredictionSequence=z.S.prototype.vp;z.S.prototype.encodeString=z.S.prototype.hp;z.S.prototype.HTMLEscape=z.S.prototype.Jo;z.S.prototype.JSONEscape=z.S.prototype.og;z.S.prototype.decodeString=z.S.prototype.dp;z.S.getInst=z.S.prototype.Jb;z.S.prototype.getIDFromDoc=z.S.prototype.qa;z.S.prototype.getDomainFromDoc=z.S.prototype.sp;
z.S.prototype.sturdyArrayLength=z.S.prototype.Kh;z.S.prototype.fireEvent=z.S.prototype.fireEvent;z.S.prototype.isScrolledIntoView=z.S.prototype.Um;z.S.prototype.toLang=z.S.prototype.vo;Kj.prototype.q=function(){try{if(null===this.Dl)throw Error("The parser is currently null.");return this.Dl}catch(a){z.S.a().b(a)}};Kj.prototype.tl=function(){try{this.Dl=new window.textHelp.parsers[z.Yj.vj],this.Dl.Eh(this.Ha)}catch(a){z.S.a().b(a)}};z.u("textHelp.webreaderapi.ParserFactory",Kj);Kj.prototype.getParser=Kj.prototype.q;z.ga(z.Qj);z.f=z.Qj.prototype;z.f.Se=function(){try{return this.ln}catch(a){z.S.a().b(a)}};z.f.Hh=function(a){try{this.ln=a}catch(b){z.S.a().b(b)}};z.f.Kg=function(){try{return z.S.a().Kg()}catch(a){z.S.a().b(a)}};z.f.Kb=function(){try{return z.S.a().Gd.Kb()}catch(a){z.S.a().b(a)}};z.f.Jb=function(){try{return z.Qj.a()}catch(a){z.S.a().b(a)}};z.u("textHelp.webreaderapi.SettingsSingleton",z.Qj);z.Qj.prototype.get_Voice=z.Qj.prototype.Se;z.Qj.prototype.set_Voice=z.Qj.prototype.Hh;
z.Qj.prototype.getOptionsDialog=z.Qj.prototype.Kg;z.Qj.prototype.getVoices=z.Qj.prototype.Kb;z.Qj.getInst=z.Qj.prototype.Jb;z.f=Rj.prototype;z.f.Sa=function(){try{throw Error("Not implemented");}catch(a){z.S.a().b(a)}};z.f.Kb=function(){try{throw Error("Not implemented");}catch(a){z.S.a().b(a)}};z.f.Xd=function(){try{throw Error("Not implemented");}catch(a){z.S.a().b(a)}};z.f.stop=function(){try{throw Error("Not implemented");}catch(a){z.S.a().b(a)}};z.f.pause=function(){try{throw Error("Not implemented");}catch(a){z.S.a().b(a)}};z.f=Jj.prototype;z.f.Sa=function(){try{this.eh||(this.Yf.Xs=new Sj,this.Yf.Xs.Sa(),this.eh=!0)}catch(a){z.S.a().b(a)}};z.f.Kb=function(a){try{if(!this.eh)return null;void 0==a&&(a=!1);a&&(this.cc=[],this.dd=[]);if(0<z.S.a().Kh(this.cc))return this.cc;for(var b in this.Yf)if(this.Yf.hasOwnProperty(b)){var c=this.Yf[b].Kb(),d;for(d in c)c.hasOwnProperty(d)&&(this.cc[d]=c[d],this.dd[d]=this.Yf[b])}return this.cc}catch(e){z.S.a().b(e)}};
z.f.Xd=function(a,b,c){try{0==z.S.a().Kh(this.cc)&&this.Kb();var d=this.dd[z.Qj.a().Se()];if(void 0===d){var e=z.S.a().yd(),g=z.gj.a().Ib();z.Qj.a().Hh(g[e].speechoptions.voice);d=this.dd[z.Qj.a().Se()]}d.Xd(a,b,c)}catch(h){z.S.a().b(h)}};z.f.stop=function(){try{if(0!=z.S.a().Kh(this.dd)){var a=this.dd[z.Qj.a().Se()];if(void 0===a){var b=z.S.a().yd(),c=z.gj.a().Ib();z.Qj.a().Hh(c[b].speechoptions.voice);a=this.dd[z.Qj.a().Se()]}null!==a&&a.stop()}}catch(d){z.S.a().b(d)}};
z.f.pause=function(){try{if(0!=z.S.a().Kh(this.dd)){var a=this.dd[z.Qj.a().Se()];if(void 0===a){var b=z.S.a().yd(),c=z.gj.a().Ib();z.Qj.a().Hh(c[b].voice);a=this.dd[z.Qj.a().Se()]}null!==a&&a.pause()}}catch(d){z.S.a().b(d)}};z.B(Sj,Rj);z.f=Sj.prototype;z.f.Sa=function(){try{z.S.a().Qe();z.S.a().Jf();var a=!1;void 0==a&&(a=!1);var b=z.gj.a().Ib();this.Bn=b.serversettings.speechserver;this.Cn=b.serversettings.userspeech;a='{"refresh":"'+a+'"}';a=z.od(a);window.thPostMessage({method:"thGetVoices",type:"1757FROM_PAGERW4G",payload:a},"*");this.$i=z.S.a().bind(this,this.Qo)}catch(c){z.S.a().b(c)}};z.f.Kb=function(){try{return this.mn}catch(a){z.S.a().b(a)}};
z.f.Xd=function(a,b,c){try{void 0==c&&(c=!0);this.hh=this.fl=!1;null===this.W&&(this.W=z.J("thWebAudio"));this.cj=0;var d=this.Bn+"index.html";b="";for(var e=0;e<a.length;e++){var g=a[e];b=" "===g||""===g?b+" ":c?b+("\x3cbookmark mark\x3d'"+e+"'/\x3e"+Tj(this,a[e])+" "):b+Tj(this,a[e])}b+="\x3cbookmark mark\x3d'"+e+"'/\x3e";z.T.a().u("onthAPIWord",["start"]);var h="text\x3d"+(0,window.encodeURIComponent)(b)+"\x26userName\x3d"+(0,window.encodeURIComponent)(this.Cn)+"\x26voiceName\x3d"+(0,window.encodeURIComponent)(z.V.a().O().speechoptions.voice)+
"\x26speedValue\x3d"+(0,window.encodeURIComponent)(z.V.a().O().speechoptions.speed)+"\x26usePron\x3dY",l=new z.xd;z.E(l,"complete",this.wr,!1,this);var m=new z.Wc;m.set("Content-Type","application/x-www-form-urlencoded;charset\x3dUTF-8");l.send(d,"POST",h,m);null===this.cd&&(this.cd=z.S.a().Ra());a=[];a.push("on speech");a.push(this.cd.Email);a.push(this.cd.Email.split("@")[1]);window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",parameters:a},"*");a[0]="speech request timer";
window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"StartTiming",parameters:a},"*")}catch(n){z.S.a().b(n)}};z.f.stop=function(){try{if(null!==this.W&&null!==this.Nb){this.fl=!0;this.hh=!1;this.Nb.length=0;try{this.W.pause(),this.W.currentTime=0,this.W.src=""}catch(a){}}}catch(b){z.S.a().b(b)}};z.f.pause=function(){try{null!==this.W&&0!==this.W.currentTime&&(this.hh?(this.W.play(),this.hh=!1):(this.W.pause(),this.hh=!0))}catch(a){z.S.a().b(a)}};
z.f.Qo=function(){try{if(null!==this.Nb)if(this.W.ended)this.W.pause(),this.W.currentTime=0,this.W.src="",this.$i.length=0,z.T.a().u("onthAPIStop",[]);else{if(0<this.Nb.length&&this.Nb[this.cj]<this.W.currentTime){var a=[];a.push(this.cj);z.T.a().u("onthAPIWord",a);this.cj++}(0,window.setTimeout)(this.$i,50)}}catch(b){z.S.a().b(b)}};
z.f.Xn=function(a){try{for(var b=a.response.split("\x26voiceName"),c,d=a="",e=0;e<b.length;e++)c=b[e].split("\x3d"),a=c[1].split("\x26voice"),a=(0,window.decodeURIComponent)(a[0]).replace(/\+/gi," "),d=(0,window.decodeURIComponent)(c[2]).replace(/\+/gi," "),this.mn[a]=d;z.T.a().u("onRefreshedVoices",[])}catch(g){z.S.a().b(g)}};
z.f.wr=function(a){try{var b=[];b.push("speech request timer");window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"EndTiming",parameters:b},"*");var c=z.Md(a.currentTarget),d=c.indexOf("\x26mp3"),e=c.substring(c.indexOf("xml\x3d")+4,d),g=c.substring(d+5,c.length);if("error"==e||"error"==g)throw this.stop(),Error("Speech request error. Error response from the server.");if("busy"==e||"busy"==g)throw this.stop(),Error("Speech request error. Speech server busy.");try{this.W.src=g;var h=
new z.xd;z.E(h,"complete",this.zs,!1,this);h.send(e,"POST")}catch(l){z.S.a().b(l)}}catch(m){z.S.a().b(m)}};
z.f.zs=function(a){try{var b;var c=a.target;try{b=c.H?c.H.responseXML:null}catch(d){z.ld(c.C,"Can not get responseXML: "+d.message),b=null}this.Nb=[];if(b&&b.documentElement&&b.documentElement.childNodes){var e=b.documentElement.childNodes;for(b=a=0;b<e.length;b++)1==e[b].nodeType&&(this.Nb[a]=(0,window.parseFloat)(e[b].getAttribute("time")/1E3),0<a&&this.Nb[a]<=this.Nb[a-1]&&(this.Nb[a]=this.Nb[a-1]+.01),a+=1);.1>this.Nb[this.Nb.length-1]&&(this.Nb.length=0)}this.fl||(window.setTimeout(this.$i,50),
this.W.play())}catch(g){z.S.a().b(g)}};Uj.prototype.isEnabled=function(){try{return this.ej}catch(a){z.S.a().b(a)}};
Uj.prototype.start=function(){try{var a=this;this.Fc=new window.webkitSpeechRecognition;this.Fc.Ht=!0;this.Fc.Zt=!0;var b=z.V.a().O().language.services;this.Fc.lang=z.S.a().vo(b);this.Fc.onstart=function(){};this.Fc.onresult=function(a){for(var b="",c="",h=a.resultIndex;h<a.results.length;++h)a.results[h].isFinal?b+=a.results[h][0].transcript:c+=a.results[h][0].transcript;0<b.length?(a=[],a.push(b+" "),z.T.a().u("onSpeechRecognitionResponse",a)):0<c.length&&(a=[],a.push(c+" "),z.T.a().u("onSpeechRecognitionInterimResponse",
a))};this.Fc.onerror=function(){};this.Fc.onend=function(){a.ej&&a.Fc.start()};this.ej=this.eh=!0;this.Fc.start()}catch(c){z.S.a().b(c)}};Uj.prototype.stop=function(){try{this.ej=!1,this.Fc.stop()}catch(a){z.S.a().b(a)}};z.u("textHelp.webreaderapi.SpeechRecognition",Uj);Uj.prototype.isEnabled=Uj.prototype.isEnabled;Uj.prototype.start=Uj.prototype.start;Uj.prototype.stop=Uj.prototype.stop;z.hj.prototype.pm=function(a,b,c,d,e){var g=this.Ro;this.qm=c;this.$n=d;this.mk=e;this.filename=a;var h=this;Vj(g,a,b).then(function(a){var b=a.statusFileLocation;""!=b?(h.Mn=a.mp3Location,(0,window.setTimeout)(function(){try{Wj(h,b)}catch(a){e(a)}},1E3)):e(Error("Status file returned empty."))},function(a){e(a)})};z.u("textHelp.RW4GC.AudioMaker",z.hj);z.hj.prototype.convert=z.hj.prototype.pm;z.Kf("WebReaderAPI");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_WebReaderAPI.js